// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Tue Dec 24 18:55:59 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 8301402
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "800" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 2
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [31.8515205383,5135.92919922]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [13.9813117981,4877.60791016]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 2 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[2];
   double fVmax[2];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[2];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.729901090211804);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.779652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414028,-99) , 
1, 99.2799, 1, 0, 0.734077,-99) , 
NN(
0, 
0, 
-1, 221.994, 1, -1, 0.197606,-99) , 
0, 205.46, 1, 0, 0.633255,-99) , 
NN(
0, 
0, 
-1, 506.38, 1, -1, 0.0177473,-99) , 
0, 274.903, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.535043);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249228,-99) , 
0, 137.67, 0, 0, 0.622088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235505,-99) , 
0, 217.033, 1, 0, 0.572918,-99) , 
NN(
0, 
0, 
-1, 247.208, 1, -1, 0.0361966,-99) , 
0, 274.903, 1, 0, 0.474512,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.382685);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241707,-99) , 
1, 117.514, 1, 0, 0.545235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.21052,-99) , 
1, 60.7381, 0, 0, 0.504662,-99) , 
NN(
0, 
0, 
-1, 247.208, 1, -1, 0.0602833,-99) , 
0, 274.903, 1, 0, 0.433907,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.202783);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 1, -1, 0.399976,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.23183);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310154,-99) , 
1, 126.977, 1, 0, 0.524972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324157,-99) , 
1, 60.7381, 0, 0, 0.502938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.103314,-99) , 
0, 274.903, 1, 0, 0.449672,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.225218);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404913,-99) , 
0, 190.028, 1, 0, 0.48814,-99) , 
NN(
0, 
0, 
-1, 71.9035, 1, -1, 0.372054,-99) , 
0, 147.59, 0, 0, 0.466104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.126853,-99) , 
0, 274.903, 1, 0, 0.423919,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.187837);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328656,-99) , 
0, 156.096, 0, 0, 0.483961,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.180358,-99) , 
0, 170.738, 1, 0, 0.411048,-99) , 
1, 72.4273, 0, 0, 0.465456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153964,-99) , 
0, 274.903, 1, 0, 0.429063,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.183809);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 1, -1, 0.409117,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.113131);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.301716,-99) , 
1, 54.8488, 0, 0, 0.491992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343799,-99) , 
0, 240.181, 1, 0, 0.483505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208798,-99) , 
0, 274.903, 1, 0, 0.45427,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.124735);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 1, -1, 0.437954,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.123297);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332645,-99) , 
1, 54.0585, 0, 0, 0.504309,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.281153,-99) , 
0, 200.365, 0, 0, 0.435875,-99) , 
1, 107.495, 1, 0, 0.493362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250806,-99) , 
0, 274.903, 1, 0, 0.468902,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0989339);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 1, -1, 0.450694,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0791407);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395364,-99) , 
0, 131.056, 0, 0, 0.500613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394333,-99) , 
0, 240.181, 1, 0, 0.494651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294821,-99) , 
0, 274.903, 1, 0, 0.475315,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0724158);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 1, -1, 0.463855,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0724317);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370831,-99) , 
1, 52.9453, 0, 0, 0.502984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4271,-99) , 
1, 130.873, 1, 0, 0.498047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327277,-99) , 
0, 274.903, 1, 0, 0.481921,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.10741);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4012,-99) , 
0, 156.096, 0, 0, 0.49311,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254186,-99) , 
0, 170.738, 1, 0, 0.457433,-99) , 
1, 72.4273, 0, 0, 0.484289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343419,-99) , 
0, 274.903, 1, 0, 0.471119,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0948454);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 193.886, 1, -1, 0.475324,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330044,-99) , 
0, 215.272, 0, 0, 0.430106,-99) , 
1, 107.495, 1, 0, 0.468099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368029,-99) , 
0, 274.903, 1, 0, 0.458847,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.079219);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429313,-99) , 
0, 193.886, 1, 0, 0.499038,-99) , 
NN(
0, 
0, 
-1, 200.365, 0, -1, 0.431047,-99) , 
1, 107.495, 1, 0, 0.488251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390351,-99) , 
0, 274.903, 1, 0, 0.479273,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0788445);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437543,-99) , 
0, 165.235, 0, 0, 0.490558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289383,-99) , 
0, 170.738, 1, 0, 0.451431,-99) , 
1, 72.4273, 0, 0, 0.480938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409359,-99) , 
0, 274.903, 1, 0, 0.474411,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0636234);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 1, -1, 0.468231,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0451311);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39417,-99) , 
1, 110.125, 1, 0, 0.493441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429424,-99) , 
0, 228.607, 1, 0, 0.488085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444196,-99) , 
0, 274.903, 1, 0, 0.484109,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.068857);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469489,-99) , 
1, 90.2394, 1, 0, 0.491908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345631,-99) , 
0, 159.164, 1, 0, 0.446402,-99) , 
1, 72.4273, 0, 0, 0.480736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455365,-99) , 
0, 274.903, 1, 0, 0.478441,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0555335);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453856,-99) , 
0, 165.235, 0, 0, 0.491621,-99) , 
NN(
0, 
0, 
-1, 170.738, 1, -1, 0.442532,-99) , 
1, 72.4273, 0, 0, 0.479599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472488,-99) , 
0, 274.903, 1, 0, 0.478956,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0415947);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 0, -1, 0.479215,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0275711);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496742,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428643,-99) , 
1, 134.77, 1, 0, 0.4961,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348136,-99) , 
0, 170.738, 1, 0, 0.46662,-99) , 
1, 72.4273, 0, 0, 0.488899,-99) , 
0, 274.903, 0, 0, 0.489608,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0373018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503635,-99) , 
NN(
NN(
0, 
0, 
-1, 134.77, 1, -1, 0.490225,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385525,-99) , 
0, 159.164, 1, 0, 0.463022,-99) , 
1, 72.4273, 0, 0, 0.483584,-99) , 
0, 274.903, 0, 0, 0.485398,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0290132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494224,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444599,-99) , 
1, 134.77, 1, 0, 0.499554,-99) , 
NN(
0, 
0, 
-1, 170.738, 1, -1, 0.460887,-99) , 
1, 72.4273, 0, 0, 0.490127,-99) , 
0, 274.903, 0, 0, 0.490497,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0263887);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501477,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473253,-99) , 
0, 165.235, 0, 0, 0.493368,-99) , 
NN(
0, 
0, 
-1, 170.738, 1, -1, 0.468106,-99) , 
1, 72.4273, 0, 0, 0.487213,-99) , 
0, 274.903, 0, 0, 0.488504,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.025156);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 0, -1, 0.487425,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0170281);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501112,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426542,-99) , 
0, 131.056, 0, 0, 0.495554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449566,-99) , 
0, 240.181, 1, 0, 0.492977,-99) , 
0, 274.903, 0, 0, 0.493714,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0209833);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.49682,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418869,-99) , 
1, 110.125, 1, 0, 0.492547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459992,-99) , 
0, 228.607, 1, 0, 0.489811,-99) , 
0, 274.903, 0, 0, 0.490446,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0368668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502065,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481835,-99) , 
1, 99.1454, 0, 0, 0.490528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374182,-99) , 
0, 170.738, 1, 0, 0.473556,-99) , 
1, 72.4273, 0, 0, 0.486393,-99) , 
0, 274.903, 0, 0, 0.487813,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0340066);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.492777,-99) , 
NN(
NN(
0, 
0, 
-1, 134.77, 1, -1, 0.494051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423483,-99) , 
0, 147.59, 1, 0, 0.468711,-99) , 
1, 72.4273, 0, 0, 0.487881,-99) , 
0, 274.903, 0, 0, 0.488325,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0261373);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501278,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455589,-99) , 
1, 134.77, 1, 0, 0.502557,-99) , 
NN(
0, 
0, 
-1, 170.738, 1, -1, 0.469777,-99) , 
1, 72.4273, 0, 0, 0.494585,-99) , 
0, 274.903, 0, 0, 0.495192,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0282171);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494696,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490121,-99) , 
1, 81.3333, 1, 0, 0.496985,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397165,-99) , 
0, 170.738, 1, 0, 0.476294,-99) , 
1, 72.4273, 0, 0, 0.491955,-99) , 
0, 274.903, 0, 0, 0.492204,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0293959);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50175,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481411,-99) , 
0, 156.096, 0, 0, 0.500456,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437069,-99) , 
0, 147.59, 1, 0, 0.472571,-99) , 
1, 72.4273, 0, 0, 0.49368,-99) , 
0, 274.903, 0, 0, 0.494412,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0186104);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 0, -1, 0.490696,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0171756);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499003,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466412,-99) , 
1, 134.77, 1, 0, 0.500385,-99) , 
NN(
0, 
0, 
-1, 170.738, 1, -1, 0.478137,-99) , 
1, 72.4273, 0, 0, 0.494984,-99) , 
0, 274.903, 0, 0, 0.495349,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0161276);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419246,-99) , 
0, 131.056, 0, 0, 0.49476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467867,-99) , 
0, 240.181, 1, 0, 0.493253,-99) , 
0, 274.903, 0, 0, 0.494165,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0392014);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499238,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422474,-99) , 
1, 120.58, 0, 0, 0.506246,-99) , 
NN(
0, 
0, 
-1, 111.858, 1, -1, 0.488021,-99) , 
0, 217.033, 0, 0, 0.490255,-99) , 
0, 274.903, 0, 0, 0.491071,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0321465);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509038,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425412,-99) , 
1, 110.125, 1, 0, 0.501235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473838,-99) , 
0, 228.607, 1, 0, 0.498943,-99) , 
0, 274.903, 0, 0, 0.499861,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0345682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500951,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434883,-99) , 
1, 120.58, 0, 0, 0.512323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370269,-99) , 
1, 111.858, 1, 0, 0.491102,-99) , 
0, 217.033, 0, 0, 0.493697,-99) , 
0, 274.903, 0, 0, 0.494357,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0437463);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.492259,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443397,-99) , 
1, 120.58, 0, 0, 0.512968,-99) , 
NN(
0, 
0, 
-1, 111.858, 1, -1, 0.483722,-99) , 
0, 217.033, 0, 0, 0.48729,-99) , 
0, 274.903, 0, 0, 0.487742,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0296505);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503194,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49368,-99) , 
1, 99.1454, 0, 0, 0.50081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454885,-99) , 
0, 147.59, 1, 0, 0.48508,-99) , 
1, 72.4273, 0, 0, 0.496986,-99) , 
0, 274.903, 0, 0, 0.497551,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0224816);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457888,-99) , 
1, 134.77, 1, 0, 0.503665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430978,-99) , 
0, 170.738, 1, 0, 0.486016,-99) , 
1, 72.4273, 0, 0, 0.499377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495741,-99) , 
0, 274.903, 1, 0, 0.499046,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.01161);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501361,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456303,-99) , 
1, 61.2089, 0, 0, 0.497472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472688,-99) , 
0, 136.016, 0, 0, 0.495021,-99) , 
0, 274.903, 0, 0, 0.495598,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0128656);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 0, -1, 0.493568,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0103016);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50166,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462382,-99) , 
1, 61.2089, 0, 0, 0.498216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478793,-99) , 
0, 136.016, 0, 0, 0.496296,-99) , 
0, 274.903, 0, 0, 0.496784,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0409641);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499071,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458638,-99) , 
0, 193.886, 1, 0, 0.497194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36583,-99) , 
0, 200.365, 0, 0, 0.480525,-99) , 
1, 107.495, 1, 0, 0.494572,-99) , 
0, 274.903, 0, 0, 0.494982,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0438331);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509311,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418058,-99) , 
1, 97.0312, 0, 0, 0.504659,-99) , 
NN(
0, 
0, 
-1, 107.81, 1, -1, 0.485186,-99) , 
0, 205.46, 0, 0, 0.488661,-99) , 
0, 274.903, 0, 0, 0.490544,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0171989);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.4983,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481705,-99) , 
1, 69.6441, 0, 0, 0.499526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461145,-99) , 
1, 130.873, 1, 0, 0.497066,-99) , 
0, 274.903, 0, 0, 0.497178,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0316849);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502599,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437942,-99) , 
1, 54.0585, 0, 0, 0.498809,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409445,-99) , 
0, 215.272, 0, 0, 0.474612,-99) , 
1, 107.495, 1, 0, 0.495019,-99) , 
0, 274.903, 0, 0, 0.495711,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0277496);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494642,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520124,-99) , 
NN(
0, 
0, 
-1, 148.15, 0, -1, 0.485878,-99) , 
1, 60.7381, 1, 0, 0.489326,-99) , 
0, 274.903, 0, 0, 0.489811,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0191342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501579,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44425,-99) , 
1, 110.125, 1, 0, 0.497451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466196,-99) , 
0, 228.607, 1, 0, 0.494865,-99) , 
0, 274.903, 0, 0, 0.495478,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0156343);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 0, -1, 0.492183,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0178267);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500684,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425677,-99) , 
0, 131.056, 0, 0, 0.497141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4697,-99) , 
0, 240.181, 1, 0, 0.495631,-99) , 
0, 274.903, 0, 0, 0.496092,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0185939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496208,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510715,-99) , 
NN(
0, 
0, 
-1, 148.15, 0, -1, 0.490248,-99) , 
1, 60.7381, 1, 0, 0.492309,-99) , 
0, 274.903, 0, 0, 0.492665,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0463873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500857,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428697,-99) , 
1, 97.0312, 0, 0, 0.508635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454941,-99) , 
1, 90.7501, 1, 0, 0.493286,-99) , 
0, 205.46, 0, 0, 0.496021,-99) , 
0, 274.903, 0, 0, 0.496463,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0306046);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488733,-99) , 
1, 99.1454, 0, 0, 0.495981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453472,-99) , 
0, 147.59, 1, 0, 0.476109,-99) , 
1, 72.4273, 0, 0, 0.491147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489216,-99) , 
0, 274.903, 1, 0, 0.49097,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0190437);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496866,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451178,-99) , 
1, 134.77, 1, 0, 0.49894,-99) , 
NN(
0, 
0, 
-1, 55.7284, 0, -1, 0.477079,-99) , 
1, 72.4273, 0, 0, 0.493624,-99) , 
0, 274.903, 0, 0, 0.49392,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0153751);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501627,-99) , 
NN(
0, 
0, 
-1, 136.016, 0, -1, 0.491703,-99) , 
0, 274.903, 0, 0, 0.492611,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0110635);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497769,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459777,-99) , 
1, 61.2089, 0, 0, 0.497809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474924,-99) , 
0, 136.016, 0, 0, 0.495547,-99) , 
0, 274.903, 0, 0, 0.49575,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0140004);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500534,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44612,-99) , 
1, 110.125, 1, 0, 0.495525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47335,-99) , 
0, 228.607, 1, 0, 0.493696,-99) , 
0, 274.903, 0, 0, 0.494321,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0309567);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497022,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445345,-99) , 
1, 97.0312, 0, 0, 0.503905,-99) , 
NN(
0, 
0, 
-1, 131.056, 0, -1, 0.488688,-99) , 
0, 205.46, 0, 0, 0.491393,-99) , 
0, 274.903, 0, 0, 0.491908,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0150324);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504761,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483294,-99) , 
1, 69.6441, 0, 0, 0.499206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469885,-99) , 
1, 130.873, 1, 0, 0.497334,-99) , 
0, 274.903, 0, 0, 0.498014,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.016325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50099,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449479,-99) , 
1, 110.125, 1, 0, 0.497541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473326,-99) , 
0, 228.607, 1, 0, 0.495543,-99) , 
0, 274.903, 0, 0, 0.496042,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0174295);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510597,-99) , 
NN(
0, 
0, 
-1, 148.15, 0, -1, 0.490868,-99) , 
1, 60.7381, 1, 0, 0.492856,-99) , 
0, 274.903, 0, 0, 0.493226,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0098765);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46287,-99) , 
1, 61.2089, 0, 0, 0.498167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479639,-99) , 
0, 136.016, 0, 0, 0.496336,-99) , 
0, 274.903, 0, 0, 0.496786,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0130736);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498775,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508709,-99) , 
NN(
0, 
0, 
-1, 148.15, 0, -1, 0.493111,-99) , 
1, 60.7381, 1, 0, 0.494683,-99) , 
0, 274.903, 0, 0, 0.495058,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0263227);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502043,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4659,-99) , 
1, 120.58, 0, 0, 0.510242,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399326,-99) , 
0, 128.852, 0, 0, 0.495515,-99) , 
0, 217.033, 0, 0, 0.497293,-99) , 
0, 274.903, 0, 0, 0.497728,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0258188);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495442,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472455,-99) , 
1, 120.58, 0, 0, 0.510698,-99) , 
NN(
0, 
0, 
-1, 128.852, 0, -1, 0.489868,-99) , 
0, 217.033, 0, 0, 0.492381,-99) , 
0, 274.903, 0, 0, 0.492661,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0126856);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501897,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486538,-99) , 
1, 69.6441, 0, 0, 0.499772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473699,-99) , 
1, 130.873, 1, 0, 0.49811,-99) , 
0, 274.903, 0, 0, 0.498457,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0121523);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512251,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463338,-99) , 
0, 148.15, 0, 0, 0.494841,-99) , 
1, 60.7381, 1, 0, 0.496598,-99) , 
0, 274.903, 0, 0, 0.496792,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0105236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501754,-99) , 
NN(
0, 
0, 
-1, 130.873, 1, -1, 0.494384,-99) , 
0, 274.903, 0, 0, 0.49506,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0055841);
  fForest.push_back( 
NN(
0, 
0, 
-1, 274.903, 0, -1, 0.497208,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.00657337);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500511,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486208,-99) , 
1, 58.5115, 0, 0, 0.499812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477848,-99) , 
1, 130.873, 1, 0, 0.498412,-99) , 
0, 274.903, 0, 0, 0.498604,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.010647);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498863,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514353,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468736,-99) , 
0, 148.15, 0, 0, 0.495338,-99) , 
1, 60.7381, 1, 0, 0.497256,-99) , 
0, 274.903, 0, 0, 0.497403,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0130736);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511692,-99) , 
NN(
0, 
0, 
-1, 148.15, 0, -1, 0.493479,-99) , 
1, 60.7381, 1, 0, 0.495316,-99) , 
0, 274.903, 0, 0, 0.495885,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0217622);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498247,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476082,-99) , 
1, 120.58, 0, 0, 0.511682,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414325,-99) , 
1, 111.858, 1, 0, 0.496038,-99) , 
0, 217.033, 0, 0, 0.497926,-99) , 
0, 274.903, 0, 0, 0.497955,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0227274);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503687,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475408,-99) , 
0, 236.323, 1, 0, 0.512061,-99) , 
NN(
0, 
0, 
-1, 128.852, 0, -1, 0.491376,-99) , 
0, 217.033, 0, 0, 0.49387,-99) , 
0, 274.903, 0, 0, 0.49477,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0214386);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480636,-99) , 
1, 120.58, 0, 0, 0.512326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417733,-99) , 
0, 128.852, 0, 0, 0.497058,-99) , 
0, 217.033, 0, 0, 0.498898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49799,-99) , 
0, 274.903, 1, 0, 0.498814,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0199415);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503349,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480345,-99) , 
0, 236.323, 1, 0, 0.512694,-99) , 
NN(
0, 
0, 
-1, 111.858, 1, -1, 0.492453,-99) , 
0, 217.033, 0, 0, 0.494891,-99) , 
0, 274.903, 0, 0, 0.495667,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.00865393);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484986,-99) , 
1, 58.5115, 0, 0, 0.500726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478381,-99) , 
1, 130.873, 1, 0, 0.499303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498351,-99) , 
0, 274.903, 1, 0, 0.499215,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0173357);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500514,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483215,-99) , 
1, 120.58, 0, 0, 0.512439,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423944,-99) , 
1, 111.858, 1, 0, 0.495774,-99) , 
0, 217.033, 0, 0, 0.497781,-99) , 
0, 274.903, 0, 0, 0.498032,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0196661);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496169,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484719,-99) , 
0, 236.323, 1, 0, 0.512733,-99) , 
NN(
0, 
0, 
-1, 128.852, 0, -1, 0.492058,-99) , 
0, 217.033, 0, 0, 0.494547,-99) , 
0, 274.903, 0, 0, 0.494696,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0174985);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501086,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48678,-99) , 
1, 120.58, 0, 0, 0.512954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427898,-99) , 
0, 128.852, 0, 0, 0.496975,-99) , 
0, 217.033, 0, 0, 0.498898,-99) , 
0, 274.903, 0, 0, 0.499099,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0168428);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.4967,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489028,-99) , 
0, 236.323, 1, 0, 0.513246,-99) , 
NN(
0, 
0, 
-1, 111.858, 1, -1, 0.493215,-99) , 
0, 217.033, 0, 0, 0.495625,-99) , 
0, 274.903, 0, 0, 0.495724,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0098487);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500911,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477937,-99) , 
0, 148.15, 0, 0, 0.497511,-99) , 
1, 60.7381, 1, 0, 0.499351,-99) , 
0, 274.903, 0, 0, 0.499494,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0208672);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498443,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463796,-99) , 
0, 131.056, 0, 0, 0.510027,-99) , 
NN(
0, 
0, 
-1, 72.8704, 0, -1, 0.494727,-99) , 
0, 147.59, 1, 0, 0.497556,-99) , 
0, 274.903, 0, 0, 0.497637,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0198115);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50366,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493249,-99) , 
1, 120.58, 0, 0, 0.516184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435512,-99) , 
1, 111.858, 1, 0, 0.499595,-99) , 
0, 217.033, 0, 0, 0.50159,-99) , 
0, 274.903, 0, 0, 0.501781,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0123505);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498695,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495306,-99) , 
0, 236.323, 1, 0, 0.51651,-99) , 
NN(
0, 
0, 
-1, 128.852, 0, -1, 0.495347,-99) , 
0, 217.033, 0, 0, 0.497892,-99) , 
0, 274.903, 0, 0, 0.497966,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0154566);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501783,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497719,-99) , 
1, 120.58, 0, 0, 0.516643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439946,-99) , 
0, 128.852, 0, 0, 0.498435,-99) , 
0, 217.033, 0, 0, 0.500624,-99) , 
0, 274.903, 0, 0, 0.500731,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.00450487);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.497748,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00225218);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.498874,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00112597);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499437,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.000562921);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499719,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.000281429);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499859,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.000140699);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.49993,-99)    );
  // itree = 98
  fBoostWeights.push_back(7.03418e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499965,-99)    );
  // itree = 99
  fBoostWeights.push_back(3.5167e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499982,-99)    );
  // itree = 100
  fBoostWeights.push_back(1.75816e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499991,-99)    );
  // itree = 101
  fBoostWeights.push_back(8.78982e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499996,-99)    );
  // itree = 102
  fBoostWeights.push_back(4.39443e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499998,-99)    );
  // itree = 103
  fBoostWeights.push_back(2.19697e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499999,-99)    );
  // itree = 104
  fBoostWeights.push_back(1.09836e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.499999,-99)    );
  // itree = 105
  fBoostWeights.push_back(5.49122e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 106
  fBoostWeights.push_back(2.74531e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 107
  fBoostWeights.push_back(1.3725e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 108
  fBoostWeights.push_back(6.86174e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 109
  fBoostWeights.push_back(3.4305e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 110
  fBoostWeights.push_back(1.71507e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 111
  fBoostWeights.push_back(8.57445e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 112
  fBoostWeights.push_back(4.2865e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 113
  fBoostWeights.push_back(2.14328e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 114
  fBoostWeights.push_back(1.0714e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 115
  fBoostWeights.push_back(5.35727e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 116
  fBoostWeights.push_back(2.678e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 117
  fBoostWeights.push_back(1.33819e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 118
  fBoostWeights.push_back(6.68827e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 119
  fBoostWeights.push_back(3.34774e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 120
  fBoostWeights.push_back(1.68172e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 121
  fBoostWeights.push_back(8.42271e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 122
  fBoostWeights.push_back(4.22107e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 123
  fBoostWeights.push_back(2.12419e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 124
  fBoostWeights.push_back(1.0798e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 125
  fBoostWeights.push_back(5.30909e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 126
  fBoostWeights.push_back(2.68896e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 127
  fBoostWeights.push_back(1.2923e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 128
  fBoostWeights.push_back(5.9508e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 129
  fBoostWeights.push_back(3.17524e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 130
  fBoostWeights.push_back(1.74305e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 131
  fBoostWeights.push_back(8.88178e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 132
  fBoostWeights.push_back(5.44009e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 133
  fBoostWeights.push_back(1.77636e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 134
  fBoostWeights.push_back(8.88178e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 135
  fBoostWeights.push_back(4.44089e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 136
  fBoostWeights.push_back(1.11022e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 137
  fBoostWeights.push_back(4.44089e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 138
  fBoostWeights.push_back(2.22045e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 139
  fBoostWeights.push_back(2.22045e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 140
  fBoostWeights.push_back(2.22045e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
  // itree = 141
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 274.903, 0, -1, 0.5,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
