// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Mon Jan  6 22:12:16 2020
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 8293545
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "800" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 2
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [31.8515205383,5348.45361328]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [13.9813117981,4877.60791016]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 2 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[2];
   double fVmax[2];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[2];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.747985691612952);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.771457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358839,-99) , 
1, 101.93, 1, 0, 0.723503,-99) , 
NN(
0, 
0, 
-1, 233.355, 1, -1, 0.138357,-99) , 
0, 212.688, 1, 0, 0.623425,-99) , 
NN(
0, 
0, 
-1, 247.208, 1, -1, 0.0156955,-99) , 
0, 285.023, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.496644);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.220872,-99) , 
1, 60.2124, 0, 0, 0.598166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182236,-99) , 
0, 224.744, 1, 0, 0.549918,-99) , 
NN(
0, 
0, 
-1, 247.208, 1, -1, 0.0326622,-99) , 
0, 285.023, 1, 0, 0.46117,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.344548);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302459,-99) , 
0, 202.929, 1, 0, 0.506647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.143592,-99) , 
0, 128.298, 0, 0, 0.479393,-99) , 
NN(
0, 
0, 
-1, 247.208, 1, -1, 0.0525865,-99) , 
0, 285.023, 1, 0, 0.415714,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.234813);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.23103,-99) , 
1, 123.596, 1, 0, 0.472809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237935,-99) , 
0, 140.354, 0, 0, 0.440585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0726547,-99) , 
0, 285.023, 1, 0, 0.391287,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.268002);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.369117,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.18659);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303437,-99) , 
0, 143.276, 0, 0, 0.494653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332372,-99) , 
1, 62.5514, 0, 0, 0.47482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.114689,-99) , 
0, 285.023, 1, 0, 0.433643,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.172817);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.414442,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.176407);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320269,-99) , 
1, 55.6128, 0, 0, 0.514081,-99) , 
NN(
0, 
0, 
-1, 208.158, 0, -1, 0.358423,-99) , 
1, 111.121, 1, 0, 0.491387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.156529,-99) , 
0, 285.023, 1, 0, 0.457,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.12432);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.438158,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.115563);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364825,-99) , 
1, 54.4564, 0, 0, 0.506682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349426,-99) , 
1, 135.406, 1, 0, 0.497146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.200439,-99) , 
0, 285.023, 1, 0, 0.46901,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.193706);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344878,-99) , 
1, 90.8413, 1, 0, 0.497786,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236885,-99) , 
1, 87.6536, 0, 0, 0.429697,-99) , 
0, 188.577, 1, 0, 0.475267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.219602,-99) , 
0, 285.023, 1, 0, 0.451705,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.158575);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406462,-99) , 
0, 190.299, 1, 0, 0.47065,-99) , 
NN(
0, 
0, 
-1, 74.6475, 1, -1, 0.386275,-99) , 
0, 152.409, 0, 0, 0.450994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254591,-99) , 
0, 285.023, 1, 0, 0.433552,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.121441);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.439576,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.060659);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.469708,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0702614);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410005,-99) , 
1, 135.711, 1, 0, 0.505875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399745,-99) , 
0, 128.298, 0, 0, 0.499563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324406,-99) , 
0, 285.023, 1, 0, 0.484853,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0574579);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458762,-99) , 
1, 75.137, 0, 0, 0.490522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416719,-99) , 
0, 128.298, 0, 0, 0.486157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339991,-99) , 
0, 285.023, 1, 0, 0.474002,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0597251);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.470173,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0437152);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437503,-99) , 
1, 54.4564, 0, 0, 0.499912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428697,-99) , 
1, 135.406, 1, 0, 0.495645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366758,-99) , 
0, 285.023, 1, 0, 0.485084,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0437077);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404518,-99) , 
1, 113.572, 1, 0, 0.49121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438029,-99) , 
0, 236.8, 1, 0, 0.487368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376968,-99) , 
0, 285.023, 1, 0, 0.478365,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0552916);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.472382,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0285576);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45006,-99) , 
0, 240.244, 1, 0, 0.496848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443879,-99) , 
0, 128.298, 0, 0, 0.493723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400487,-99) , 
0, 285.023, 1, 0, 0.486189,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.150467);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314633,-99) , 
1, 75.137, 0, 0, 0.497333,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253017,-99) , 
1, 84.9086, 1, 0, 0.473215,-99) , 
0, 164.465, 0, 0, 0.488343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407362,-99) , 
0, 285.023, 1, 0, 0.481816,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0729546);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.463587,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0364582);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.481779,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0182205);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 1, -1, 0.490891,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0194599);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457563,-99) , 
0, 240.244, 1, 0, 0.500074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450763,-99) , 
0, 128.298, 0, 0, 0.497158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475824,-99) , 
0, 285.023, 1, 0, 0.495447,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0253517);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484629,-99) , 
1, 87.2518, 1, 0, 0.495877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455585,-99) , 
0, 128.298, 0, 0, 0.493496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48068,-99) , 
0, 285.023, 1, 0, 0.492468,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.116852);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367438,-99) , 
1, 75.137, 0, 0, 0.501332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358399,-99) , 
1, 78.4607, 1, 0, 0.479943,-99) , 
0, 164.465, 0, 0, 0.493409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487011,-99) , 
0, 285.023, 1, 0, 0.492897,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0693723);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516216,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33226,-99) , 
1, 98.5273, 1, 0, 0.486468,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330837,-99) , 
1, 87.6536, 0, 0, 0.46258,-99) , 
0, 188.577, 1, 0, 0.478613,-99) , 
0, 285.023, 0, 0, 0.481643,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0607318);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 0, -1, 0.469671,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0348526);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513897,-99) , 
NN(
0, 
0, 
-1, 135.406, 1, -1, 0.482271,-99) , 
0, 285.023, 0, 0, 0.484827,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0192149);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505114,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47335,-99) , 
0, 152.409, 0, 0, 0.494022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444305,-99) , 
1, 135.406, 1, 0, 0.490981,-99) , 
0, 285.023, 0, 0, 0.492124,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0203359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500272,-99) , 
NN(
0, 
0, 
-1, 135.406, 1, -1, 0.488963,-99) , 
0, 285.023, 0, 0, 0.489877,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0117278);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 0, -1, 0.494136,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0127652);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498082,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461556,-99) , 
0, 128.298, 0, 0, 0.499579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456999,-99) , 
1, 135.406, 1, 0, 0.49698,-99) , 
0, 285.023, 0, 0, 0.497069,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0704704);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501273,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371429,-99) , 
1, 98.5273, 1, 0, 0.500934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368344,-99) , 
1, 87.6536, 0, 0, 0.481483,-99) , 
0, 188.577, 1, 0, 0.494555,-99) , 
0, 285.023, 0, 0, 0.495098,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0396478);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.483539,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480319,-99) , 
1, 100.714, 0, 0, 0.485277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44469,-99) , 
1, 135.406, 1, 0, 0.482793,-99) , 
0, 285.023, 0, 0, 0.482853,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.08273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.493445,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41527,-99) , 
0, 176.521, 1, 0, 0.499706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342811,-99) , 
0, 168.843, 0, 0, 0.476754,-99) , 
1, 86.8364, 1, 0, 0.489471,-99) , 
0, 285.023, 0, 0, 0.489793,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0518382);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514124,-99) , 
NN(
NN(
0, 
0, 
-1, 200.633, 1, -1, 0.48483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305637,-99) , 
0, 208.158, 0, 0, 0.443979,-99) , 
1, 111.121, 1, 0, 0.478903,-99) , 
0, 285.023, 0, 0, 0.481768,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0414037);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501088,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449407,-99) , 
0, 200.633, 1, 0, 0.497789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316748,-99) , 
0, 208.158, 0, 0, 0.440877,-99) , 
1, 111.121, 1, 0, 0.489561,-99) , 
0, 285.023, 0, 0, 0.490499,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0362043);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.49068,-99) , 
NN(
NN(
0, 
0, 
-1, 152.409, 0, -1, 0.490355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325776,-99) , 
0, 208.158, 0, 0, 0.438379,-99) , 
1, 111.121, 1, 0, 0.48286,-99) , 
0, 285.023, 0, 0, 0.483497,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0427811);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.49973,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475703,-99) , 
0, 152.409, 0, 0, 0.499408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362152,-99) , 
0, 223.531, 0, 0, 0.436183,-99) , 
1, 111.121, 1, 0, 0.490308,-99) , 
0, 285.023, 0, 0, 0.491076,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0271007);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510424,-99) , 
NN(
0, 
0, 
-1, 123.264, 1, -1, 0.486176,-99) , 
0, 285.023, 0, 0, 0.488154,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0284488);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503615,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482162,-99) , 
1, 92.0403, 1, 0, 0.499583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428269,-99) , 
1, 123.264, 1, 0, 0.492949,-99) , 
0, 285.023, 0, 0, 0.49382,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.028989);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496468,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491979,-99) , 
1, 102.448, 0, 0, 0.496369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435249,-99) , 
1, 123.264, 1, 0, 0.490693,-99) , 
0, 285.023, 0, 0, 0.491164,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0368897);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503715,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468658,-99) , 
0, 200.633, 1, 0, 0.503563,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355206,-99) , 
0, 208.158, 0, 0, 0.452849,-99) , 
1, 111.121, 1, 0, 0.496307,-99) , 
0, 285.023, 0, 0, 0.496911,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0186971);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 0, -1, 0.490653,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0147408);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499124,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463469,-99) , 
0, 128.298, 0, 0, 0.499246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429198,-99) , 
1, 135.406, 1, 0, 0.494989,-99) , 
0, 285.023, 0, 0, 0.495327,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0242912);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502809,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485945,-99) , 
0, 164.465, 0, 0, 0.497119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443803,-99) , 
1, 123.264, 1, 0, 0.49219,-99) , 
0, 285.023, 0, 0, 0.493057,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0339633);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.49671,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493697,-99) , 
1, 60.2385, 1, 0, 0.497547,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391334,-99) , 
0, 223.531, 0, 0, 0.456749,-99) , 
1, 111.121, 1, 0, 0.491728,-99) , 
0, 285.023, 0, 0, 0.492135,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0350848);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505201,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486677,-99) , 
0, 188.577, 1, 0, 0.504101,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399453,-99) , 
0, 223.531, 0, 0, 0.457401,-99) , 
1, 111.121, 1, 0, 0.497452,-99) , 
0, 285.023, 0, 0, 0.498086,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0150997);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496394,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451802,-99) , 
1, 54.4564, 0, 0, 0.497676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432176,-99) , 
1, 135.406, 1, 0, 0.493723,-99) , 
0, 285.023, 0, 0, 0.493942,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0167914);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500169,-99) , 
NN(
0, 
0, 
-1, 135.406, 1, -1, 0.490872,-99) , 
0, 285.023, 0, 0, 0.491633,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0140647);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495955,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459712,-99) , 
1, 54.4564, 0, 0, 0.498599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440018,-99) , 
1, 135.406, 1, 0, 0.49507,-99) , 
0, 285.023, 0, 0, 0.495142,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0182119);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499471,-99) , 
NN(
NN(
0, 
0, 
-1, 128.298, 0, -1, 0.497591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398435,-99) , 
0, 215.844, 0, 0, 0.461128,-99) , 
1, 111.121, 1, 0, 0.492413,-99) , 
0, 285.023, 0, 0, 0.492991,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0251494);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504024,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471437,-99) , 
0, 128.298, 0, 0, 0.502145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411282,-99) , 
0, 223.531, 0, 0, 0.46074,-99) , 
1, 111.121, 1, 0, 0.49627,-99) , 
0, 285.023, 0, 0, 0.496905,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0221256);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497713,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43054,-99) , 
1, 113.572, 1, 0, 0.495631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441366,-99) , 
0, 236.8, 1, 0, 0.491696,-99) , 
0, 285.023, 0, 0, 0.492189,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0227701);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503244,-99) , 
NN(
0, 
0, 
-1, 236.8, 1, -1, 0.487891,-99) , 
0, 285.023, 0, 0, 0.489148,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0191947);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497532,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44158,-99) , 
1, 113.572, 1, 0, 0.49679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452463,-99) , 
0, 236.8, 1, 0, 0.493582,-99) , 
0, 285.023, 0, 0, 0.493906,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0182333);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50233,-99) , 
NN(
0, 
0, 
-1, 236.8, 1, -1, 0.490279,-99) , 
0, 285.023, 0, 0, 0.491266,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0161123);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497756,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450829,-99) , 
1, 113.572, 1, 0, 0.497414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461751,-99) , 
0, 236.8, 1, 0, 0.494837,-99) , 
0, 285.023, 0, 0, 0.495076,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0334545);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501784,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442914,-99) , 
0, 243.689, 1, 0, 0.511848,-99) , 
NN(
0, 
0, 
-1, 110.725, 1, -1, 0.488601,-99) , 
0, 212.688, 0, 0, 0.492062,-99) , 
0, 285.023, 0, 0, 0.492859,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0155777);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496853,-99) , 
1, 100.714, 0, 0, 0.501006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465789,-99) , 
1, 135.406, 1, 0, 0.4989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493394,-99) , 
0, 285.023, 1, 0, 0.498449,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0242226);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455212,-99) , 
1, 113.572, 1, 0, 0.503789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472582,-99) , 
0, 236.8, 1, 0, 0.501537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497288,-99) , 
0, 285.023, 1, 0, 0.501189,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0215135);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503344,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459216,-99) , 
0, 243.689, 1, 0, 0.51373,-99) , 
NN(
0, 
0, 
-1, 110.725, 1, -1, 0.494505,-99) , 
0, 212.688, 0, 0, 0.497363,-99) , 
0, 285.023, 0, 0, 0.497853,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0677888);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45176,-99) , 
0, 176.521, 1, 0, 0.50744,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387541,-99) , 
0, 168.843, 0, 0, 0.494619,-99) , 
1, 86.8364, 1, 0, 0.501763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497949,-99) , 
0, 285.023, 1, 0, 0.50145,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.015174);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514892,-99) , 
NN(
0, 
0, 
-1, 135.406, 1, -1, 0.493068,-99) , 
0, 285.023, 0, 0, 0.494862,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0117849);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51109,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465301,-99) , 
1, 54.4564, 0, 0, 0.498921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464579,-99) , 
1, 135.406, 1, 0, 0.496861,-99) , 
0, 285.023, 0, 0, 0.498031,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0477652);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508136,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469854,-99) , 
0, 176.521, 1, 0, 0.501443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421556,-99) , 
0, 177.78, 0, 0, 0.486064,-99) , 
1, 86.8364, 1, 0, 0.494635,-99) , 
0, 285.023, 0, 0, 0.495744,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0482217);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496163,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431731,-99) , 
1, 75.137, 0, 0, 0.496307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420692,-99) , 
1, 78.4607, 1, 0, 0.478323,-99) , 
0, 164.465, 0, 0, 0.489626,-99) , 
0, 285.023, 0, 0, 0.490164,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0318256);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508218,-99) , 
NN(
0, 
0, 
-1, 135.406, 1, -1, 0.483403,-99) , 
0, 285.023, 0, 0, 0.485446,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0159077);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500242,-99) , 
NN(
0, 
0, 
-1, 135.406, 1, -1, 0.491355,-99) , 
0, 285.023, 0, 0, 0.492087,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.00938394);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496256,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465223,-99) , 
0, 128.298, 0, 0, 0.49785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456016,-99) , 
1, 135.406, 1, 0, 0.495331,-99) , 
0, 285.023, 0, 0, 0.495408,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0262302);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498602,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493464,-99) , 
1, 79.8978, 0, 0, 0.501668,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442908,-99) , 
0, 177.78, 0, 0, 0.483322,-99) , 
1, 86.8364, 1, 0, 0.493547,-99) , 
0, 285.023, 0, 0, 0.493964,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0287286);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505159,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475095,-99) , 
0, 188.577, 1, 0, 0.50446,-99) , 
NN(
0, 
0, 
-1, 168.843, 0, -1, 0.480758,-99) , 
1, 86.8364, 1, 0, 0.493969,-99) , 
0, 285.023, 0, 0, 0.494891,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0185087);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497961,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485666,-99) , 
0, 164.465, 0, 0, 0.4966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459213,-99) , 
1, 135.406, 1, 0, 0.494349,-99) , 
0, 285.023, 0, 0, 0.494647,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0253864);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502588,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493943,-99) , 
1, 60.2385, 1, 0, 0.497016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430141,-99) , 
0, 223.531, 0, 0, 0.473686,-99) , 
1, 111.121, 1, 0, 0.493713,-99) , 
0, 285.023, 0, 0, 0.494444,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.014038);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471998,-99) , 
0, 128.298, 0, 0, 0.501082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467242,-99) , 
1, 123.264, 1, 0, 0.497991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496228,-99) , 
0, 285.023, 1, 0, 0.497846,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0156452);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499737,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476243,-99) , 
1, 55.6128, 0, 0, 0.498896,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436293,-99) , 
0, 223.531, 0, 0, 0.47517,-99) , 
1, 111.121, 1, 0, 0.49554,-99) , 
0, 285.023, 0, 0, 0.495886,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0138899);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503648,-99) , 
NN(
0, 
0, 
-1, 236.8, 1, -1, 0.492759,-99) , 
0, 285.023, 0, 0, 0.493657,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0160067);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500169,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453363,-99) , 
1, 113.572, 1, 0, 0.498484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467536,-99) , 
0, 236.8, 1, 0, 0.496232,-99) , 
0, 285.023, 0, 0, 0.496556,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0126052);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 0, -1, 0.493698,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0127324);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.49931,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460463,-99) , 
1, 113.572, 1, 0, 0.49835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474665,-99) , 
0, 236.8, 1, 0, 0.496628,-99) , 
0, 285.023, 0, 0, 0.496849,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0109799);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502493,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482466,-99) , 
0, 158.15, 0, 0, 0.495757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473586,-99) , 
0, 128.298, 0, 0, 0.494436,-99) , 
0, 285.023, 0, 0, 0.4951,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.012343);
  fForest.push_back( 
NN(
0, 
0, 
-1, 285.023, 0, -1, 0.493829,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0105875);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502829,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464088,-99) , 
1, 113.572, 1, 0, 0.49781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478181,-99) , 
0, 236.8, 1, 0, 0.496383,-99) , 
0, 285.023, 0, 0, 0.496915,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0216311);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500177,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463655,-99) , 
0, 243.689, 1, 0, 0.507067,-99) , 
NN(
0, 
0, 
-1, 110.725, 1, -1, 0.492366,-99) , 
0, 212.688, 0, 0, 0.49456,-99) , 
0, 285.023, 0, 0, 0.495023,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0252493);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486186,-99) , 
0, 176.521, 1, 0, 0.503268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46275,-99) , 
0, 177.78, 0, 0, 0.493571,-99) , 
1, 86.8364, 1, 0, 0.498982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494759,-99) , 
0, 285.023, 1, 0, 0.498633,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00692809);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501071,-99) , 
NN(
0, 
0, 
-1, 135.406, 1, -1, 0.496321,-99) , 
0, 285.023, 0, 0, 0.496713,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.008653);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468713,-99) , 
1, 54.4564, 0, 0, 0.499364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477487,-99) , 
1, 135.406, 1, 0, 0.498053,-99) , 
0, 285.023, 0, 0, 0.498159,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00681897);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501499,-99) , 
NN(
0, 
0, 
-1, 128.298, 0, -1, 0.496419,-99) , 
0, 285.023, 0, 0, 0.496838,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.00836242);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499792,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478682,-99) , 
1, 63.0222, 0, 0, 0.499336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479001,-99) , 
0, 128.298, 0, 0, 0.498124,-99) , 
0, 285.023, 0, 0, 0.498261,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0205387);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512162,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42319,-99) , 
0, 143.276, 0, 0, 0.494622,-99) , 
1, 62.5514, 1, 0, 0.496666,-99) , 
0, 285.023, 0, 0, 0.497096,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0188387);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486882,-99) , 
1, 69.49, 0, 0, 0.497563,-99) , 
NN(
0, 
0, 
-1, 177.78, 0, -1, 0.486087,-99) , 
1, 86.8364, 1, 0, 0.492489,-99) , 
0, 285.023, 0, 0, 0.49284,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0166324);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501448,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511737,-99) , 
NN(
0, 
0, 
-1, 143.276, 0, -1, 0.491436,-99) , 
1, 62.5514, 1, 0, 0.493803,-99) , 
0, 285.023, 0, 0, 0.494434,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.00596947);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.497015,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00298452);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.498508,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00149215);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499254,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00074602);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499627,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.000372983);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499813,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.000186478);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499907,-99)    );
  // itree = 101
  fBoostWeights.push_back(9.32321e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499953,-99)    );
  // itree = 102
  fBoostWeights.push_back(4.66127e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499977,-99)    );
  // itree = 103
  fBoostWeights.push_back(2.33047e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499988,-99)    );
  // itree = 104
  fBoostWeights.push_back(1.16515e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499994,-99)    );
  // itree = 105
  fBoostWeights.push_back(5.82532e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499997,-99)    );
  // itree = 106
  fBoostWeights.push_back(2.91245e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499999,-99)    );
  // itree = 107
  fBoostWeights.push_back(1.45612e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.499999,-99)    );
  // itree = 108
  fBoostWeights.push_back(7.28006e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 109
  fBoostWeights.push_back(3.63976e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 110
  fBoostWeights.push_back(1.81975e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 111
  fBoostWeights.push_back(9.0981e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 112
  fBoostWeights.push_back(4.54872e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 113
  fBoostWeights.push_back(2.27419e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 114
  fBoostWeights.push_back(1.13701e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 115
  fBoostWeights.push_back(5.68469e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 116
  fBoostWeights.push_back(2.84203e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 117
  fBoostWeights.push_back(1.42095e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 118
  fBoostWeights.push_back(7.10394e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 119
  fBoostWeights.push_back(3.55086e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 120
  fBoostWeights.push_back(1.77515e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 121
  fBoostWeights.push_back(8.88105e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 122
  fBoostWeights.push_back(4.45231e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 123
  fBoostWeights.push_back(2.22321e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 124
  fBoostWeights.push_back(1.11171e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 125
  fBoostWeights.push_back(5.57432e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 126
  fBoostWeights.push_back(2.77733e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 127
  fBoostWeights.push_back(1.37002e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 128
  fBoostWeights.push_back(6.83009e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 129
  fBoostWeights.push_back(3.31069e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 130
  fBoostWeights.push_back(1.6398e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 131
  fBoostWeights.push_back(8.22675e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 132
  fBoostWeights.push_back(3.91909e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 133
  fBoostWeights.push_back(2.13163e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 134
  fBoostWeights.push_back(9.88098e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 135
  fBoostWeights.push_back(5.77316e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 136
  fBoostWeights.push_back(2.66454e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 137
  fBoostWeights.push_back(9.99201e-16);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
  // itree = 138
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 285.023, 0, -1, 0.5,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
