// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Tue Jan  7 09:40:12 2020
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 8293545
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "550" [Number of training cycles]
HiddenLayers: "N,N+5,3" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 2
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [31.8515205383,5348.45361328]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [13.9813117981,4877.60791016]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 2 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][2];
   double fMax_1[3][2];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[2];
   double fVmax[2];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[2];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[3][3];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[8][3];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[4][8];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][4];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 3; fWeights[0] = new double[3]; 
   fLayerSize[1] = 3; fWeights[1] = new double[3]; 
   fLayerSize[2] = 8; fWeights[2] = new double[8]; 
   fLayerSize[3] = 4; fWeights[3] = new double[4]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -82.1924387648409;
   fWeightMatrix0to1[1][0] = 77.3845964301291;
   fWeightMatrix0to1[0][1] = -23.2803162890064;
   fWeightMatrix0to1[1][1] = -119.732866050802;
   fWeightMatrix0to1[0][2] = -99.7556862829603;
   fWeightMatrix0to1[1][2] = -43.4229042493967;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -4.96744173229579;
   fWeightMatrix1to2[1][0] = 6.21623033833293;
   fWeightMatrix1to2[2][0] = -1.24315700207774;
   fWeightMatrix1to2[3][0] = -31.522224270911;
   fWeightMatrix1to2[4][0] = -1.98361737370929;
   fWeightMatrix1to2[5][0] = 18.2245175865598;
   fWeightMatrix1to2[6][0] = -5.03930704881502;
   fWeightMatrix1to2[0][1] = -6.41599168266832;
   fWeightMatrix1to2[1][1] = -14.0177884070378;
   fWeightMatrix1to2[2][1] = 8.1572544740134;
   fWeightMatrix1to2[3][1] = 5.84105711532286;
   fWeightMatrix1to2[4][1] = 12.8607800107379;
   fWeightMatrix1to2[5][1] = 2.27861912585406;
   fWeightMatrix1to2[6][1] = 6.02738900284669;
   fWeightMatrix1to2[0][2] = 3.93252111845815;
   fWeightMatrix1to2[1][2] = -5.56818383554783;
   fWeightMatrix1to2[2][2] = -3.93788841007723;
   fWeightMatrix1to2[3][2] = -4.04586884741625;
   fWeightMatrix1to2[4][2] = -13.351114940295;
   fWeightMatrix1to2[5][2] = -18.4007219079566;
   fWeightMatrix1to2[6][2] = 1.70680817485476;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -27.0558371649844;
   fWeightMatrix2to3[1][0] = -10.7458265744418;
   fWeightMatrix2to3[2][0] = -3.36279335580493;
   fWeightMatrix2to3[0][1] = 7.03592694157104;
   fWeightMatrix2to3[1][1] = 2.52133380317574;
   fWeightMatrix2to3[2][1] = -4.60184685585986;
   fWeightMatrix2to3[0][2] = -5.37305706426639;
   fWeightMatrix2to3[1][2] = 3.03447868576579;
   fWeightMatrix2to3[2][2] = -3.46188979507663;
   fWeightMatrix2to3[0][3] = -23.3355594911852;
   fWeightMatrix2to3[1][3] = 1.12926638035332;
   fWeightMatrix2to3[2][3] = -2.78386743634328;
   fWeightMatrix2to3[0][4] = -0.404120352891908;
   fWeightMatrix2to3[1][4] = -0.464646490190905;
   fWeightMatrix2to3[2][4] = -10.4851285235159;
   fWeightMatrix2to3[0][5] = 3.70058717764349;
   fWeightMatrix2to3[1][5] = 10.64748105708;
   fWeightMatrix2to3[2][5] = -1.78122033956373;
   fWeightMatrix2to3[0][6] = 6.96912194301593;
   fWeightMatrix2to3[1][6] = -6.01204592539083;
   fWeightMatrix2to3[2][6] = 2.00600568317357;
   fWeightMatrix2to3[0][7] = 22.102959109657;
   fWeightMatrix2to3[1][7] = -5.13474434970964;
   fWeightMatrix2to3[2][7] = 0.33905277104324;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 10.2648971006294;
   fWeightMatrix3to4[0][1] = -10.8145841671626;
   fWeightMatrix3to4[0][2] = 10.1117376988828;
   fWeightMatrix3to4[0][3] = -14.2141252814906;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 66.8327102661;
   fMax_1[0][0] = 2426.51416016;
   fMin_1[1][0] = 31.8515205383;
   fMax_1[1][0] = 5348.45361328;
   fMin_1[2][0] = 31.8515205383;
   fMax_1[2][0] = 5348.45361328;
   fMin_1[0][1] = 17.2699775696;
   fMax_1[0][1] = 2311.00366211;
   fMin_1[1][1] = 13.9813117981;
   fMax_1[1][1] = 4877.60791016;
   fMin_1[2][1] = 13.9813117981;
   fMax_1[2][1] = 4877.60791016;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 2;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<2;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
