// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Wed Jan  8 04:57:14 2020
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 13632727
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "800" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 2
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [33.2677688599,5507.72949219]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [13.9813117981,4909.22119141]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 2 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[2];
   double fVmax[2];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[2];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.753496143036615);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.782895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393301,-99) , 
1, 100.506, 1, 0, 0.737422,-99) , 
NN(
0, 
0, 
-1, 227.75, 1, -1, 0.165755,-99) , 
0, 207.06, 1, 0, 0.620704,-99) , 
NN(
0, 
0, 
-1, 249.207, 1, -1, 0.0138156,-99) , 
0, 293.956, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.545918);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202664,-99) , 
1, 59.5272, 0, 0, 0.618423,-99) , 
NN(
0, 
0, 
-1, 244.301, 1, -1, 0.201217,-99) , 
0, 219.474, 1, 0, 0.559411,-99) , 
NN(
0, 
0, 
-1, 249.207, 1, -1, 0.0289591,-99) , 
0, 293.956, 1, 0, 0.470475,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.35552);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245034,-99) , 
1, 114.433, 1, 0, 0.522017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.175878,-99) , 
0, 132.578, 0, 0, 0.489582,-99) , 
NN(
0, 
0, 
-1, 249.207, 1, -1, 0.0489776,-99) , 
0, 293.956, 1, 0, 0.425813,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.218562);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.392426,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.22079);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253201,-99) , 
1, 137.452, 1, 0, 0.515867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177458,-99) , 
1, 51.5593, 0, 0, 0.495214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0837881,-99) , 
0, 293.956, 1, 0, 0.445793,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.256168);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375625,-99) , 
0, 194.646, 1, 0, 0.484934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296461,-99) , 
0, 144.991, 0, 0, 0.45338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.102372,-99) , 
0, 293.956, 1, 0, 0.414141,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.176828);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.412496,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.147811);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362307,-99) , 
0, 138.954, 0, 0, 0.503374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253649,-99) , 
1, 51.5593, 0, 0, 0.489484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.149551,-99) , 
0, 293.956, 1, 0, 0.456009,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.129302);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.435707,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.138975);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406714,-99) , 
1, 65.3608, 0, 0, 0.506966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339269,-99) , 
0, 244.301, 1, 0, 0.495789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.188314,-99) , 
0, 293.956, 1, 0, 0.467772,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0953992);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.452445,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.101476);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403237,-99) , 
1, 116.74, 1, 0, 0.507021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393608,-99) , 
0, 244.301, 1, 0, 0.49966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.226772,-99) , 
0, 293.956, 1, 0, 0.476198,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.150666);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245964,-99) , 
1, 64.5561, 0, 0, 0.49976,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295001,-99) , 
1, 76.399, 1, 0, 0.43645,-99) , 
0, 157.405, 0, 0, 0.481775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245057,-99) , 
0, 293.956, 1, 0, 0.461885,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.116809);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.44186,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0629111);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415554,-99) , 
1, 64.4037, 0, 0, 0.492148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413312,-99) , 
0, 132.578, 0, 0, 0.485926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297825,-99) , 
0, 293.956, 1, 0, 0.470859,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0746139);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.462762,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0601929);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423637,-99) , 
1, 116.74, 1, 0, 0.499791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417302,-99) , 
0, 244.301, 1, 0, 0.49446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32736,-99) , 
0, 293.956, 1, 0, 0.48137,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.126881);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332458,-99) , 
0, 155.79, 0, 0, 0.494925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189024,-99) , 
0, 182.233, 1, 0, 0.461156,-99) , 
1, 76.6113, 0, 0, 0.483862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340749,-99) , 
0, 293.956, 1, 0, 0.472747,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.090176);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.455034,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0450591);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.477486,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0389069);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412672,-99) , 
0, 231.888, 1, 0, 0.499647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434591,-99) , 
1, 139.241, 1, 0, 0.495874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401832,-99) , 
0, 293.956, 1, 0, 0.488743,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.103877);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412803,-99) , 
0, 165.659, 0, 0, 0.499662,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227761,-99) , 
0, 182.233, 1, 0, 0.464909,-99) , 
1, 76.6113, 0, 0, 0.48833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411218,-99) , 
0, 293.956, 1, 0, 0.482502,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0934757);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4631,-99) , 
1, 86.155, 1, 0, 0.486764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305853,-99) , 
0, 169.819, 1, 0, 0.447615,-99) , 
1, 76.6113, 0, 0, 0.474012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43658,-99) , 
0, 293.956, 1, 0, 0.471194,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0723518);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405388,-99) , 
0, 155.79, 0, 0, 0.495638,-99) , 
NN(
0, 
0, 
-1, 169.819, 1, -1, 0.437527,-99) , 
1, 76.6113, 0, 0, 0.476738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459693,-99) , 
0, 293.956, 1, 0, 0.475456,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0517349);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 0, -1, 0.474156,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0258567);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 0, -1, 0.487075,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0217384);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497091,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454616,-99) , 
1, 64.4037, 0, 0, 0.497765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440185,-99) , 
0, 132.578, 0, 0, 0.49325,-99) , 
0, 293.956, 0, 0, 0.493539,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0312385);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502526,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465879,-99) , 
1, 73.0325, 0, 0, 0.493907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447483,-99) , 
1, 126.715, 1, 0, 0.489728,-99) , 
0, 293.956, 0, 0, 0.490691,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.114827);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494644,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359784,-99) , 
0, 182.233, 1, 0, 0.496684,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304192,-99) , 
0, 173.274, 0, 0, 0.473602,-99) , 
1, 89.1373, 1, 0, 0.487323,-99) , 
0, 293.956, 0, 0, 0.487874,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0562954);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523334,-99) , 
NN(
0, 
0, 
-1, 132.578, 0, -1, 0.47149,-99) , 
0, 293.956, 0, 0, 0.475414,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0281202);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509158,-99) , 
NN(
0, 
0, 
-1, 132.578, 0, -1, 0.485542,-99) , 
0, 293.956, 0, 0, 0.48733,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0198749);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502074,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449094,-99) , 
1, 126.94, 1, 0, 0.496746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443836,-99) , 
0, 132.578, 0, 0, 0.492571,-99) , 
0, 293.956, 0, 0, 0.493291,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0286819);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497069,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477397,-99) , 
1, 89.4183, 1, 0, 0.492745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448748,-99) , 
0, 132.578, 0, 0, 0.489277,-99) , 
0, 293.956, 0, 0, 0.489867,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0515487);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504239,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45373,-99) , 
0, 165.659, 0, 0, 0.496516,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372215,-99) , 
0, 169.819, 1, 0, 0.473108,-99) , 
1, 76.6113, 0, 0, 0.488916,-99) , 
0, 293.956, 0, 0, 0.490077,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0334452);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 0, -1, 0.483284,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.016718);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 0, -1, 0.491642,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0159151);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503805,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433804,-99) , 
0, 231.888, 1, 0, 0.498011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449756,-99) , 
1, 139.241, 1, 0, 0.495166,-99) , 
0, 293.956, 0, 0, 0.495822,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0431724);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499801,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479726,-99) , 
1, 95.6986, 1, 0, 0.499764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393127,-99) , 
0, 169.819, 1, 0, 0.476092,-99) , 
1, 76.6113, 0, 0, 0.492088,-99) , 
0, 293.956, 0, 0, 0.492674,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0507074);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510592,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428283,-99) , 
1, 102.58, 0, 0, 0.516489,-99) , 
NN(
0, 
0, 
-1, 109.158, 1, -1, 0.483441,-99) , 
0, 207.06, 0, 0, 0.48961,-99) , 
0, 293.956, 0, 0, 0.491204,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0208762);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454396,-99) , 
1, 139.447, 1, 0, 0.502776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458924,-99) , 
0, 132.578, 0, 0, 0.499321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497841,-99) , 
0, 293.956, 1, 0, 0.499208,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0359611);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50306,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459804,-99) , 
0, 155.79, 0, 0, 0.502644,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410677,-99) , 
0, 169.819, 1, 0, 0.480707,-99) , 
1, 76.6113, 0, 0, 0.495532,-99) , 
0, 293.956, 0, 0, 0.496105,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0196505);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 0, -1, 0.490176,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0129382);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498933,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435668,-99) , 
0, 231.888, 1, 0, 0.497181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456223,-99) , 
1, 139.241, 1, 0, 0.494772,-99) , 
0, 293.956, 0, 0, 0.495089,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0235376);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502167,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467876,-99) , 
1, 124.329, 1, 0, 0.498873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421581,-99) , 
0, 169.819, 1, 0, 0.478492,-99) , 
1, 76.6113, 0, 0, 0.492269,-99) , 
0, 293.956, 0, 0, 0.493022,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0491882);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496253,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405046,-99) , 
1, 115.04, 0, 0, 0.516425,-99) , 
NN(
0, 
0, 
-1, 114.182, 1, -1, 0.484395,-99) , 
0, 219.474, 0, 0, 0.488582,-99) , 
0, 293.956, 0, 0, 0.489166,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0209427);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508549,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452048,-99) , 
1, 55.7346, 0, 0, 0.50155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458543,-99) , 
1, 139.241, 1, 0, 0.499033,-99) , 
0, 293.956, 0, 0, 0.499758,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0118752);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503288,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453211,-99) , 
0, 247.848, 1, 0, 0.497745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464773,-99) , 
0, 132.578, 0, 0, 0.495145,-99) , 
0, 293.956, 0, 0, 0.495766,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0381816);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500305,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411372,-99) , 
1, 115.04, 0, 0, 0.512935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35421,-99) , 
1, 114.182, 1, 0, 0.490003,-99) , 
0, 219.474, 0, 0, 0.49299,-99) , 
0, 293.956, 0, 0, 0.493547,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0497502);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.490717,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420647,-99) , 
1, 115.04, 0, 0, 0.51157,-99) , 
NN(
0, 
0, 
-1, 114.182, 1, -1, 0.481791,-99) , 
0, 219.474, 0, 0, 0.485659,-99) , 
0, 293.956, 0, 0, 0.486045,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0225324);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503154,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481161,-99) , 
1, 73.6289, 0, 0, 0.499005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451491,-99) , 
1, 139.241, 1, 0, 0.496239,-99) , 
0, 293.956, 0, 0, 0.496767,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0201143);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497496,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49358,-99) , 
1, 99.8739, 0, 0, 0.497369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462474,-99) , 
1, 126.715, 1, 0, 0.494265,-99) , 
0, 293.956, 0, 0, 0.494511,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0853663);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502525,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366353,-99) , 
0, 194.646, 1, 0, 0.50641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391942,-99) , 
0, 182.558, 0, 0, 0.484955,-99) , 
1, 89.1373, 1, 0, 0.497759,-99) , 
0, 293.956, 0, 0, 0.498123,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0303212);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 1, -1, 0.484844,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.020613);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481098,-99) , 
1, 73.0325, 0, 0, 0.496294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456336,-99) , 
1, 126.715, 1, 0, 0.492732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488683,-99) , 
0, 293.956, 1, 0, 0.492422,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0173066);
  fForest.push_back( 
NN(
0, 
0, 
-1, 293.956, 0, -1, 0.491348,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0111621);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498161,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472739,-99) , 
0, 132.578, 0, 0, 0.498372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465758,-99) , 
1, 126.715, 1, 0, 0.495468,-99) , 
0, 293.956, 0, 0, 0.495674,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0198295);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500952,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454887,-99) , 
1, 106.464, 1, 0, 0.495742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462897,-99) , 
0, 244.301, 1, 0, 0.493616,-99) , 
0, 293.956, 0, 0, 0.494179,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0346319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495977,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458892,-99) , 
1, 102.58, 0, 0, 0.50914,-99) , 
NN(
0, 
0, 
-1, 109.158, 1, -1, 0.486447,-99) , 
0, 207.06, 0, 0, 0.490644,-99) , 
0, 293.956, 0, 0, 0.491052,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0175979);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504635,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48801,-99) , 
1, 91.5232, 1, 0, 0.499602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459969,-99) , 
1, 139.241, 1, 0, 0.497294,-99) , 
0, 293.956, 0, 0, 0.497857,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.00866975);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500221,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468237,-99) , 
1, 55.7346, 0, 0, 0.498003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464343,-99) , 
1, 139.241, 1, 0, 0.496043,-99) , 
0, 293.956, 0, 0, 0.496364,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0162531);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498047,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463493,-99) , 
1, 106.464, 1, 0, 0.496368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466452,-99) , 
0, 244.301, 1, 0, 0.494434,-99) , 
0, 293.956, 0, 0, 0.494711,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0349521);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50211,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436832,-99) , 
1, 115.04, 0, 0, 0.514503,-99) , 
NN(
0, 
0, 
-1, 114.182, 1, -1, 0.488637,-99) , 
0, 219.474, 0, 0, 0.491993,-99) , 
0, 293.956, 0, 0, 0.492769,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0138102);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475168,-99) , 
1, 55.7346, 0, 0, 0.501513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465596,-99) , 
1, 139.241, 1, 0, 0.499428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493345,-99) , 
0, 293.956, 1, 0, 0.498961,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0062841);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.496858,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00314165);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.498429,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.00157063);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499215,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.000785217);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499607,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00039256);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499804,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.000196255);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499902,-99)    );
  // itree = 69
  fBoostWeights.push_back(9.81155e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499951,-99)    );
  // itree = 70
  fBoostWeights.push_back(4.90517e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499975,-99)    );
  // itree = 71
  fBoostWeights.push_back(2.45228e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499988,-99)    );
  // itree = 72
  fBoostWeights.push_back(1.22599e-05);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499994,-99)    );
  // itree = 73
  fBoostWeights.push_back(6.12917e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499997,-99)    );
  // itree = 74
  fBoostWeights.push_back(3.06421e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499998,-99)    );
  // itree = 75
  fBoostWeights.push_back(1.53191e-06);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.499999,-99)    );
  // itree = 76
  fBoostWeights.push_back(7.65861e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 77
  fBoostWeights.push_back(3.82883e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 78
  fBoostWeights.push_back(1.91418e-07);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 79
  fBoostWeights.push_back(9.56968e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 80
  fBoostWeights.push_back(4.78423e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 81
  fBoostWeights.push_back(2.39186e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 82
  fBoostWeights.push_back(1.19576e-08);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 83
  fBoostWeights.push_back(5.97812e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 84
  fBoostWeights.push_back(2.9885e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 85
  fBoostWeights.push_back(1.49415e-09);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 86
  fBoostWeights.push_back(7.47021e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 87
  fBoostWeights.push_back(3.73566e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 88
  fBoostWeights.push_back(1.86747e-10);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 89
  fBoostWeights.push_back(9.34208e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 90
  fBoostWeights.push_back(4.67147e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 91
  fBoostWeights.push_back(2.33071e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 92
  fBoostWeights.push_back(1.16773e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 93
  fBoostWeights.push_back(5.84688e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 94
  fBoostWeights.push_back(2.92077e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 95
  fBoostWeights.push_back(1.44307e-12);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 96
  fBoostWeights.push_back(7.12319e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 97
  fBoostWeights.push_back(3.49942e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 98
  fBoostWeights.push_back(1.69642e-13);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 99
  fBoostWeights.push_back(8.53762e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 100
  fBoostWeights.push_back(4.57412e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 101
  fBoostWeights.push_back(2.40918e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 102
  fBoostWeights.push_back(1.4766e-14);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 103
  fBoostWeights.push_back(7.66054e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 104
  fBoostWeights.push_back(5.32907e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 105
  fBoostWeights.push_back(3.55271e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 106
  fBoostWeights.push_back(1.77636e-15);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
  // itree = 107
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 293.956, 1, -1, 0.5,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
