// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Tue Jan 14 12:34:51 2020
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 13632727
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "550" [Number of training cycles]
HiddenLayers: "N,N+5,3" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [33.2677688599,5507.72949219]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [13.9813117981,4909.22119141]
j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                                                      'D'    [60.0252151489,2812.28125]
j1j2_absdelPt                 j1j2_absdelPt                 j1j2_absdelPt                 j1j2_absdelPt                                                   'D'    [3.81469726562e-06,1695.02734375]
j1j2_delR                     j1j2_delR                     j1j2_delR                     j1j2_delR                                                       'D'    [0.379585266113,5.68194293976]
whadb_sumPt                   whadb_sumPt                   whadb_sumPt                   whadb_sumPt                                                     'D'    [30.3689727783,3027.66625977]
whadb_delPt                   whadb_delPt                   whadb_delPt                   whadb_delPt                                                     'D'    [-1362.64111328,1719.17687988]
whadb_delR                    whadb_delR                    whadb_delR                    whadb_delR                                                      'D'    [0.00215380825102,10.4536933899]
hadblepton_sumPt              hadblepton_sumPt              hadblepton_sumPt              hadblepton_sumPt                                                'D'    [60.0203704834,1963.10424805]
hadblepton_delPt              hadblepton_delPt              hadblepton_delPt              hadblepton_delPt                                                'D'    [-961.891723633,1489.59179688]
hadblepton_delR               hadblepton_delR               hadblepton_delR               hadblepton_delR                                                 'D'    [0.500000059605,5.66989469528]
hadwlepton_sumPt              hadwlepton_sumPt              hadwlepton_sumPt              hadwlepton_sumPt                                                'D'    [30.1282482147,2222.31030273]
hadwlepton_delPt              hadwlepton_delPt              hadwlepton_delPt              hadwlepton_delPt                                                'D'    [-895.672058105,1644.93835449]
hadwlepton_delR               hadwlepton_delR               hadwlepton_delR               hadwlepton_delR                                                 'D'    [0.00147921941243,10.1729364395]
hadbmet_delPhi                hadbmet_delPhi                hadbmet_delPhi                hadbmet_delPhi                                                  'D'    [-3.14159226418,3.14159178734]
hadbmet_sumPt                 hadbmet_sumPt                 hadbmet_sumPt                 hadbmet_sumPt                                                   'D'    [30.5801753998,2064.86572266]
hadbmet_delPt                 hadbmet_delPt                 hadbmet_delPt                 hadbmet_delPt                                                   'D'    [-985.94921875,1453.90917969]
hadwmet_delPhi                hadwmet_delPhi                hadwmet_delPhi                hadwmet_delPhi                                                  'D'    [-3.14159250259,3.14159202576]
hadwmet_sumPt                 hadwmet_sumPt                 hadwmet_sumPt                 hadwmet_sumPt                                                   'D'    [0.611416637897,2497.38452148]
hadwmet_delPt                 hadwmet_delPt                 hadwmet_delPt                 hadwmet_delPt                                                   'D'    [-940.587097168,1612.18518066]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass", "j1j2_sumPt", "j1j2_absdelPt", "j1j2_delR", "whadb_sumPt", "whadb_delPt", "whadb_delR", "hadblepton_sumPt", "hadblepton_delPt", "hadblepton_delR", "hadwlepton_sumPt", "hadwlepton_delPt", "hadwlepton_delR", "hadbmet_delPhi", "hadbmet_sumPt", "hadbmet_delPt", "hadwmet_delPhi", "hadwmet_sumPt", "hadwmet_delPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';
      fType[16] = 'D';
      fType[17] = 'D';
      fType[18] = 'D';
      fType[19] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][20];
   double fMax_1[3][20];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[21][21];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[26][21];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[4][26];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][4];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 21; fWeights[0] = new double[21]; 
   fLayerSize[1] = 21; fWeights[1] = new double[21]; 
   fLayerSize[2] = 26; fWeights[2] = new double[26]; 
   fLayerSize[3] = 4; fWeights[3] = new double[4]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 14.8348411221558;
   fWeightMatrix0to1[1][0] = 88.5314881193061;
   fWeightMatrix0to1[2][0] = -2.13975451600204;
   fWeightMatrix0to1[3][0] = 3.85855087954746;
   fWeightMatrix0to1[4][0] = -39.3925141656661;
   fWeightMatrix0to1[5][0] = -19.3978098439256;
   fWeightMatrix0to1[6][0] = 13.8718808439572;
   fWeightMatrix0to1[7][0] = 39.8566145880405;
   fWeightMatrix0to1[8][0] = -25.6272826903915;
   fWeightMatrix0to1[9][0] = -24.6975469676918;
   fWeightMatrix0to1[10][0] = -59.1956595366197;
   fWeightMatrix0to1[11][0] = -26.3085566785865;
   fWeightMatrix0to1[12][0] = 11.5646842259533;
   fWeightMatrix0to1[13][0] = 2.7273294109787;
   fWeightMatrix0to1[14][0] = -24.8906476087952;
   fWeightMatrix0to1[15][0] = -4.44618463241855;
   fWeightMatrix0to1[16][0] = 78.0146317397964;
   fWeightMatrix0to1[17][0] = -20.2407425682813;
   fWeightMatrix0to1[18][0] = 19.7977621218285;
   fWeightMatrix0to1[19][0] = -27.0982102985225;
   fWeightMatrix0to1[0][1] = -3.93611289711354;
   fWeightMatrix0to1[1][1] = -50.1354836021789;
   fWeightMatrix0to1[2][1] = -12.1741384851777;
   fWeightMatrix0to1[3][1] = 1.27424636222517;
   fWeightMatrix0to1[4][1] = 28.1168522290687;
   fWeightMatrix0to1[5][1] = -12.8168705867515;
   fWeightMatrix0to1[6][1] = 22.0800745194383;
   fWeightMatrix0to1[7][1] = -27.9968090924756;
   fWeightMatrix0to1[8][1] = -5.61192690191712;
   fWeightMatrix0to1[9][1] = 3.65456699636517;
   fWeightMatrix0to1[10][1] = 26.6176729397293;
   fWeightMatrix0to1[11][1] = 8.94469238277806;
   fWeightMatrix0to1[12][1] = -7.39205275682343;
   fWeightMatrix0to1[13][1] = 2.24104164731009;
   fWeightMatrix0to1[14][1] = -2.28816856512381;
   fWeightMatrix0to1[15][1] = 0.864954677909326;
   fWeightMatrix0to1[16][1] = -27.2065773038922;
   fWeightMatrix0to1[17][1] = -9.19510669506424;
   fWeightMatrix0to1[18][1] = -8.60510706148391;
   fWeightMatrix0to1[19][1] = 29.8160811090912;
   fWeightMatrix0to1[0][2] = -9.90460258149645;
   fWeightMatrix0to1[1][2] = 7.52820212511368;
   fWeightMatrix0to1[2][2] = -3.87723695779916;
   fWeightMatrix0to1[3][2] = -2.84876824720967;
   fWeightMatrix0to1[4][2] = 7.59669341994526;
   fWeightMatrix0to1[5][2] = -31.1612993300013;
   fWeightMatrix0to1[6][2] = -5.16245069974638;
   fWeightMatrix0to1[7][2] = 4.82826923824882;
   fWeightMatrix0to1[8][2] = 23.2557349327368;
   fWeightMatrix0to1[9][2] = 32.8218668782904;
   fWeightMatrix0to1[10][2] = 37.8789893963678;
   fWeightMatrix0to1[11][2] = 13.9362227162915;
   fWeightMatrix0to1[12][2] = 3.41951776773414;
   fWeightMatrix0to1[13][2] = 2.18033876360907;
   fWeightMatrix0to1[14][2] = -3.31170462407724;
   fWeightMatrix0to1[15][2] = 3.7269341971113;
   fWeightMatrix0to1[16][2] = -16.2997468387045;
   fWeightMatrix0to1[17][2] = 0.574013343821543;
   fWeightMatrix0to1[18][2] = -2.63366248119303;
   fWeightMatrix0to1[19][2] = -9.4830984015224;
   fWeightMatrix0to1[0][3] = 6.57336183332636;
   fWeightMatrix0to1[1][3] = 9.90588391984489;
   fWeightMatrix0to1[2][3] = 16.1249572893144;
   fWeightMatrix0to1[3][3] = -0.155260547299902;
   fWeightMatrix0to1[4][3] = -10.8799127509015;
   fWeightMatrix0to1[5][3] = 30.1747887555482;
   fWeightMatrix0to1[6][3] = -20.2363640149816;
   fWeightMatrix0to1[7][3] = -0.641747611290745;
   fWeightMatrix0to1[8][3] = 9.46094076222664;
   fWeightMatrix0to1[9][3] = -1.32855032391368;
   fWeightMatrix0to1[10][3] = -7.62178759407618;
   fWeightMatrix0to1[11][3] = -3.35012128275285;
   fWeightMatrix0to1[12][3] = -0.126447780249791;
   fWeightMatrix0to1[13][3] = -1.55937493863698;
   fWeightMatrix0to1[14][3] = 1.04304020798484;
   fWeightMatrix0to1[15][3] = 1.55821209967396;
   fWeightMatrix0to1[16][3] = -8.63089752438461;
   fWeightMatrix0to1[17][3] = 12.4414984704775;
   fWeightMatrix0to1[18][3] = 0.819015870170018;
   fWeightMatrix0to1[19][3] = 1.32925739081467;
   fWeightMatrix0to1[0][4] = 2.51022072123379;
   fWeightMatrix0to1[1][4] = -0.0790869469274196;
   fWeightMatrix0to1[2][4] = 6.96457267543213;
   fWeightMatrix0to1[3][4] = -1.06318177434094;
   fWeightMatrix0to1[4][4] = 7.45933654097696;
   fWeightMatrix0to1[5][4] = -1.15320961915572;
   fWeightMatrix0to1[6][4] = 1.70957544385248;
   fWeightMatrix0to1[7][4] = -3.66963482106219;
   fWeightMatrix0to1[8][4] = -1.21514513462099;
   fWeightMatrix0to1[9][4] = -0.857879348994949;
   fWeightMatrix0to1[10][4] = 8.0507409187199;
   fWeightMatrix0to1[11][4] = -1.99156431811948;
   fWeightMatrix0to1[12][4] = 10.0585718256166;
   fWeightMatrix0to1[13][4] = -0.766437893877351;
   fWeightMatrix0to1[14][4] = -2.75151527836515;
   fWeightMatrix0to1[15][4] = 5.24414351024842;
   fWeightMatrix0to1[16][4] = 0.939042438542135;
   fWeightMatrix0to1[17][4] = -5.07784384281292;
   fWeightMatrix0to1[18][4] = -8.45092865212916;
   fWeightMatrix0to1[19][4] = 0.25773496110128;
   fWeightMatrix0to1[0][5] = -4.26158219994529;
   fWeightMatrix0to1[1][5] = -5.74601174091541;
   fWeightMatrix0to1[2][5] = -0.975602183534494;
   fWeightMatrix0to1[3][5] = 1.8784831666677;
   fWeightMatrix0to1[4][5] = 5.00113283687622;
   fWeightMatrix0to1[5][5] = -0.0188527155348762;
   fWeightMatrix0to1[6][5] = -0.729185578954347;
   fWeightMatrix0to1[7][5] = -1.00795906588426;
   fWeightMatrix0to1[8][5] = -0.127196211202009;
   fWeightMatrix0to1[9][5] = -2.65597266345879;
   fWeightMatrix0to1[10][5] = 4.18692014722766;
   fWeightMatrix0to1[11][5] = 2.87403558270189;
   fWeightMatrix0to1[12][5] = -1.10466142852687;
   fWeightMatrix0to1[13][5] = -1.090807911217;
   fWeightMatrix0to1[14][5] = 1.34498781825524;
   fWeightMatrix0to1[15][5] = 5.25880885069263;
   fWeightMatrix0to1[16][5] = 1.35170664858934;
   fWeightMatrix0to1[17][5] = -1.33750564096134;
   fWeightMatrix0to1[18][5] = -0.581473594584668;
   fWeightMatrix0to1[19][5] = -3.7322828822563;
   fWeightMatrix0to1[0][6] = 0.449025364391492;
   fWeightMatrix0to1[1][6] = -2.16164581412334;
   fWeightMatrix0to1[2][6] = -1.70718391303814;
   fWeightMatrix0to1[3][6] = 0.711863047776279;
   fWeightMatrix0to1[4][6] = 4.52095248362526;
   fWeightMatrix0to1[5][6] = -2.56186291094232;
   fWeightMatrix0to1[6][6] = 2.52395559394538;
   fWeightMatrix0to1[7][6] = -0.940846554921952;
   fWeightMatrix0to1[8][6] = -4.11378257999269;
   fWeightMatrix0to1[9][6] = -2.64081466892936;
   fWeightMatrix0to1[10][6] = 8.17533317467046;
   fWeightMatrix0to1[11][6] = -5.13139992642347;
   fWeightMatrix0to1[12][6] = 0.148148318284145;
   fWeightMatrix0to1[13][6] = -1.22055735081177;
   fWeightMatrix0to1[14][6] = -5.93623719670793;
   fWeightMatrix0to1[15][6] = 1.51290698344218;
   fWeightMatrix0to1[16][6] = 3.56529841044957;
   fWeightMatrix0to1[17][6] = -6.62389261960229;
   fWeightMatrix0to1[18][6] = 0.472323143401308;
   fWeightMatrix0to1[19][6] = 10.2321067454115;
   fWeightMatrix0to1[0][7] = 1.91878054477619;
   fWeightMatrix0to1[1][7] = -1.35855255202697;
   fWeightMatrix0to1[2][7] = 0.554111876108218;
   fWeightMatrix0to1[3][7] = -1.08803060403879;
   fWeightMatrix0to1[4][7] = 0.465190604130219;
   fWeightMatrix0to1[5][7] = 0.123403811588753;
   fWeightMatrix0to1[6][7] = 0.548739782387149;
   fWeightMatrix0to1[7][7] = 6.3166299504081;
   fWeightMatrix0to1[8][7] = -0.333018151566241;
   fWeightMatrix0to1[9][7] = 2.7488357933339;
   fWeightMatrix0to1[10][7] = -0.271806408660569;
   fWeightMatrix0to1[11][7] = 0.608924070702599;
   fWeightMatrix0to1[12][7] = 3.04607893956615;
   fWeightMatrix0to1[13][7] = -0.790281990552256;
   fWeightMatrix0to1[14][7] = 0.313417510723963;
   fWeightMatrix0to1[15][7] = 2.57837121420084;
   fWeightMatrix0to1[16][7] = -0.1366135867239;
   fWeightMatrix0to1[17][7] = 3.072846778588;
   fWeightMatrix0to1[18][7] = 0.42555402981362;
   fWeightMatrix0to1[19][7] = 1.86474829442263;
   fWeightMatrix0to1[0][8] = 1.6885378452745;
   fWeightMatrix0to1[1][8] = 1.02065213571706;
   fWeightMatrix0to1[2][8] = 0.412323524698451;
   fWeightMatrix0to1[3][8] = -0.934580558326158;
   fWeightMatrix0to1[4][8] = 0.959591552571783;
   fWeightMatrix0to1[5][8] = -1.42422170627197;
   fWeightMatrix0to1[6][8] = -2.42098559156071;
   fWeightMatrix0to1[7][8] = 1.99287980180628;
   fWeightMatrix0to1[8][8] = -8.94607202321689;
   fWeightMatrix0to1[9][8] = 1.48151688362856;
   fWeightMatrix0to1[10][8] = -0.774483859652973;
   fWeightMatrix0to1[11][8] = -2.7426702286218;
   fWeightMatrix0to1[12][8] = -0.494797772346956;
   fWeightMatrix0to1[13][8] = 0.892663516372145;
   fWeightMatrix0to1[14][8] = 14.4260381342655;
   fWeightMatrix0to1[15][8] = -3.8583495774274;
   fWeightMatrix0to1[16][8] = -0.500109715188069;
   fWeightMatrix0to1[17][8] = 2.73105066965973;
   fWeightMatrix0to1[18][8] = -0.732368533086777;
   fWeightMatrix0to1[19][8] = -11.0697671534683;
   fWeightMatrix0to1[0][9] = -6.80073791662447;
   fWeightMatrix0to1[1][9] = 1.23170042729691;
   fWeightMatrix0to1[2][9] = 0.717518544722536;
   fWeightMatrix0to1[3][9] = 0.865787008495186;
   fWeightMatrix0to1[4][9] = 3.5165147825289;
   fWeightMatrix0to1[5][9] = -1.87673832147713;
   fWeightMatrix0to1[6][9] = -0.882997285487103;
   fWeightMatrix0to1[7][9] = 3.2454772985362;
   fWeightMatrix0to1[8][9] = 7.7689672537445;
   fWeightMatrix0to1[9][9] = -1.0551653726502;
   fWeightMatrix0to1[10][9] = 0.147441470221192;
   fWeightMatrix0to1[11][9] = 10.3025247606901;
   fWeightMatrix0to1[12][9] = 1.55100467496731;
   fWeightMatrix0to1[13][9] = -0.891082991796034;
   fWeightMatrix0to1[14][9] = 1.10637415629672;
   fWeightMatrix0to1[15][9] = 4.8413756736813;
   fWeightMatrix0to1[16][9] = -0.0996458019222469;
   fWeightMatrix0to1[17][9] = 2.94264400182866;
   fWeightMatrix0to1[18][9] = -0.650282366513352;
   fWeightMatrix0to1[19][9] = -10.068926143113;
   fWeightMatrix0to1[0][10] = -0.248730367889015;
   fWeightMatrix0to1[1][10] = -0.0410973733433049;
   fWeightMatrix0to1[2][10] = -0.346182121144715;
   fWeightMatrix0to1[3][10] = -0.0177386844367186;
   fWeightMatrix0to1[4][10] = -0.163566815434735;
   fWeightMatrix0to1[5][10] = 0.288314771039047;
   fWeightMatrix0to1[6][10] = -0.0317149360736598;
   fWeightMatrix0to1[7][10] = 0.454245279124907;
   fWeightMatrix0to1[8][10] = 2.45524136440962;
   fWeightMatrix0to1[9][10] = 0.11526868798996;
   fWeightMatrix0to1[10][10] = -0.16482193077868;
   fWeightMatrix0to1[11][10] = -0.963425766638921;
   fWeightMatrix0to1[12][10] = -0.236474218431224;
   fWeightMatrix0to1[13][10] = -9.44134745870799;
   fWeightMatrix0to1[14][10] = 4.97825396425277;
   fWeightMatrix0to1[15][10] = 0.657461648073623;
   fWeightMatrix0to1[16][10] = -0.373835416099105;
   fWeightMatrix0to1[17][10] = 0.264113536004977;
   fWeightMatrix0to1[18][10] = -0.0907292924266953;
   fWeightMatrix0to1[19][10] = -2.66949212389871;
   fWeightMatrix0to1[0][11] = 1.96056543463531;
   fWeightMatrix0to1[1][11] = -0.855814687169477;
   fWeightMatrix0to1[2][11] = -4.18647801205736;
   fWeightMatrix0to1[3][11] = -2.07195615986042;
   fWeightMatrix0to1[4][11] = 7.76983684497441;
   fWeightMatrix0to1[5][11] = -8.45599541413364;
   fWeightMatrix0to1[6][11] = 3.94229663755974;
   fWeightMatrix0to1[7][11] = 0.132488812820265;
   fWeightMatrix0to1[8][11] = -12.7944808949765;
   fWeightMatrix0to1[9][11] = -4.47468106604936;
   fWeightMatrix0to1[10][11] = 12.3076171455257;
   fWeightMatrix0to1[11][11] = -8.84551464869379;
   fWeightMatrix0to1[12][11] = 0.927667603274252;
   fWeightMatrix0to1[13][11] = -1.69116361387249;
   fWeightMatrix0to1[14][11] = 3.84914955174862;
   fWeightMatrix0to1[15][11] = -2.60413158115936;
   fWeightMatrix0to1[16][11] = 4.26718844726132;
   fWeightMatrix0to1[17][11] = -5.64898468828564;
   fWeightMatrix0to1[18][11] = -2.59067002082817;
   fWeightMatrix0to1[19][11] = 1.12146460691525;
   fWeightMatrix0to1[0][12] = -4.2753068214473;
   fWeightMatrix0to1[1][12] = -1.0533146371816;
   fWeightMatrix0to1[2][12] = -5.2751746540188;
   fWeightMatrix0to1[3][12] = -0.545438688547024;
   fWeightMatrix0to1[4][12] = 6.98681869200337;
   fWeightMatrix0to1[5][12] = -6.97121523198205;
   fWeightMatrix0to1[6][12] = 1.95019228512997;
   fWeightMatrix0to1[7][12] = -0.578671477384686;
   fWeightMatrix0to1[8][12] = 5.71697734737583;
   fWeightMatrix0to1[9][12] = -5.86805490618837;
   fWeightMatrix0to1[10][12] = 12.9241718629102;
   fWeightMatrix0to1[11][12] = 2.95373338465044;
   fWeightMatrix0to1[12][12] = 0.272650337072947;
   fWeightMatrix0to1[13][12] = -0.0318292157865981;
   fWeightMatrix0to1[14][12] = -5.41773203770056;
   fWeightMatrix0to1[15][12] = 5.30647356162305;
   fWeightMatrix0to1[16][12] = 4.23598540478645;
   fWeightMatrix0to1[17][12] = -6.34490983757326;
   fWeightMatrix0to1[18][12] = -1.9990829495649;
   fWeightMatrix0to1[19][12] = -0.983821230349009;
   fWeightMatrix0to1[0][13] = 1.61549582726314;
   fWeightMatrix0to1[1][13] = 0.594668535624585;
   fWeightMatrix0to1[2][13] = 0.196673637912983;
   fWeightMatrix0to1[3][13] = 0.433853438635865;
   fWeightMatrix0to1[4][13] = -0.206915902841794;
   fWeightMatrix0to1[5][13] = -0.162024937951195;
   fWeightMatrix0to1[6][13] = 0.537088656500495;
   fWeightMatrix0to1[7][13] = 0.442694874459946;
   fWeightMatrix0to1[8][13] = 2.04044682308037;
   fWeightMatrix0to1[9][13] = -1.51047081554783;
   fWeightMatrix0to1[10][13] = 0.32334636786345;
   fWeightMatrix0to1[11][13] = 1.22838774663887;
   fWeightMatrix0to1[12][13] = 0.409580333864378;
   fWeightMatrix0to1[13][13] = 0.728075920831752;
   fWeightMatrix0to1[14][13] = 1.94627918572801;
   fWeightMatrix0to1[15][13] = -2.69137012947513;
   fWeightMatrix0to1[16][13] = -0.777232616021615;
   fWeightMatrix0to1[17][13] = -1.14090335596924;
   fWeightMatrix0to1[18][13] = -0.319387523396778;
   fWeightMatrix0to1[19][13] = -1.86008635882284;
   fWeightMatrix0to1[0][14] = -0.0119819850069432;
   fWeightMatrix0to1[1][14] = 0.00582194295054345;
   fWeightMatrix0to1[2][14] = 0.0028926143801786;
   fWeightMatrix0to1[3][14] = -0.541908758279985;
   fWeightMatrix0to1[4][14] = 0.00968488087846701;
   fWeightMatrix0to1[5][14] = -0.00148444045718894;
   fWeightMatrix0to1[6][14] = -0.00914763473652343;
   fWeightMatrix0to1[7][14] = 0.00841202835763881;
   fWeightMatrix0to1[8][14] = -0.0140427495278842;
   fWeightMatrix0to1[9][14] = -0.149260411397119;
   fWeightMatrix0to1[10][14] = -0.0135805823510759;
   fWeightMatrix0to1[11][14] = 0.0200807508813244;
   fWeightMatrix0to1[12][14] = -0.00607774447318662;
   fWeightMatrix0to1[13][14] = -0.0272407443191439;
   fWeightMatrix0to1[14][14] = 0.0601364574378682;
   fWeightMatrix0to1[15][14] = -0.00900960076141271;
   fWeightMatrix0to1[16][14] = -0.0188775200584079;
   fWeightMatrix0to1[17][14] = 0.0216371282458167;
   fWeightMatrix0to1[18][14] = -0.00218157219763544;
   fWeightMatrix0to1[19][14] = 0.0173619684801806;
   fWeightMatrix0to1[0][15] = 0.464527947607993;
   fWeightMatrix0to1[1][15] = -0.0199127023448428;
   fWeightMatrix0to1[2][15] = -0.024156265533994;
   fWeightMatrix0to1[3][15] = 0.200956926746052;
   fWeightMatrix0to1[4][15] = 2.25869404771077;
   fWeightMatrix0to1[5][15] = -2.22256054538014;
   fWeightMatrix0to1[6][15] = -0.655281694700091;
   fWeightMatrix0to1[7][15] = 0.541594013813582;
   fWeightMatrix0to1[8][15] = 0.750002314410298;
   fWeightMatrix0to1[9][15] = 1.02766898514316;
   fWeightMatrix0to1[10][15] = 0.724066655128249;
   fWeightMatrix0to1[11][15] = -3.68003240359651;
   fWeightMatrix0to1[12][15] = -1.59285366575622;
   fWeightMatrix0to1[13][15] = -1.92901557200754;
   fWeightMatrix0to1[14][15] = 7.58505079815549;
   fWeightMatrix0to1[15][15] = -0.794184564292435;
   fWeightMatrix0to1[16][15] = 2.95418384499903;
   fWeightMatrix0to1[17][15] = 0.744384226213826;
   fWeightMatrix0to1[18][15] = -0.493987327170838;
   fWeightMatrix0to1[19][15] = -10.8786948041328;
   fWeightMatrix0to1[0][16] = -8.04294511257067;
   fWeightMatrix0to1[1][16] = -1.38795532130926;
   fWeightMatrix0to1[2][16] = 0.470143371201955;
   fWeightMatrix0to1[3][16] = -0.365495201534438;
   fWeightMatrix0to1[4][16] = 2.45138728180399;
   fWeightMatrix0to1[5][16] = 1.32973428533756;
   fWeightMatrix0to1[6][16] = -1.80873871254095;
   fWeightMatrix0to1[7][16] = 1.82823358008635;
   fWeightMatrix0to1[8][16] = -0.834584806184882;
   fWeightMatrix0to1[9][16] = 0.0442487272140945;
   fWeightMatrix0to1[10][16] = -2.53183821814122;
   fWeightMatrix0to1[11][16] = 8.9967169167257;
   fWeightMatrix0to1[12][16] = -1.70351658460235;
   fWeightMatrix0to1[13][16] = -1.22484313697511;
   fWeightMatrix0to1[14][16] = 4.53874121563974;
   fWeightMatrix0to1[15][16] = 5.6319110464938;
   fWeightMatrix0to1[16][16] = 0.357868556472338;
   fWeightMatrix0to1[17][16] = 3.05293026279819;
   fWeightMatrix0to1[18][16] = -0.212770005661107;
   fWeightMatrix0to1[19][16] = -6.18333495859553;
   fWeightMatrix0to1[0][17] = -0.0203302986391454;
   fWeightMatrix0to1[1][17] = -0.00635151849313213;
   fWeightMatrix0to1[2][17] = 0.0648714689666638;
   fWeightMatrix0to1[3][17] = -5.70295373105875;
   fWeightMatrix0to1[4][17] = -0.0538618973223771;
   fWeightMatrix0to1[5][17] = -0.100492335980343;
   fWeightMatrix0to1[6][17] = -0.0668229575052077;
   fWeightMatrix0to1[7][17] = -0.0227326115834026;
   fWeightMatrix0to1[8][17] = 0.0680824517673415;
   fWeightMatrix0to1[9][17] = -1.4901162920746;
   fWeightMatrix0to1[10][17] = -0.0372448777314801;
   fWeightMatrix0to1[11][17] = 0.0497801667100631;
   fWeightMatrix0to1[12][17] = -0.0367294565510444;
   fWeightMatrix0to1[13][17] = -0.0450086651363199;
   fWeightMatrix0to1[14][17] = 0.00492479757111764;
   fWeightMatrix0to1[15][17] = -0.135584916829512;
   fWeightMatrix0to1[16][17] = -0.152694794173532;
   fWeightMatrix0to1[17][17] = 0.215141662288527;
   fWeightMatrix0to1[18][17] = 0.0166532407074919;
   fWeightMatrix0to1[19][17] = -0.0475975243211794;
   fWeightMatrix0to1[0][18] = 4.72453924488555;
   fWeightMatrix0to1[1][18] = -4.59863345446821;
   fWeightMatrix0to1[2][18] = -4.14759024051837;
   fWeightMatrix0to1[3][18] = -2.2836830496407;
   fWeightMatrix0to1[4][18] = 6.99095165595839;
   fWeightMatrix0to1[5][18] = -4.62434723008371;
   fWeightMatrix0to1[6][18] = 2.01564256450394;
   fWeightMatrix0to1[7][18] = -0.426987356419544;
   fWeightMatrix0to1[8][18] = -2.1298824406541;
   fWeightMatrix0to1[9][18] = -4.22605918615219;
   fWeightMatrix0to1[10][18] = 10.2797067443557;
   fWeightMatrix0to1[11][18] = -7.10587904954529;
   fWeightMatrix0to1[12][18] = -2.4128725879287;
   fWeightMatrix0to1[13][18] = -0.915940149230304;
   fWeightMatrix0to1[14][18] = -0.825315722376411;
   fWeightMatrix0to1[15][18] = 0.385526801230748;
   fWeightMatrix0to1[16][18] = 2.57267807676519;
   fWeightMatrix0to1[17][18] = -1.96753181732261;
   fWeightMatrix0to1[18][18] = 0.387709701005568;
   fWeightMatrix0to1[19][18] = 2.11203094531256;
   fWeightMatrix0to1[0][19] = -4.89946659223992;
   fWeightMatrix0to1[1][19] = -1.70195928554518;
   fWeightMatrix0to1[2][19] = -3.67970312874221;
   fWeightMatrix0to1[3][19] = 0.184315142111936;
   fWeightMatrix0to1[4][19] = 8.18521405307997;
   fWeightMatrix0to1[5][19] = -6.56533053083175;
   fWeightMatrix0to1[6][19] = 2.28740151157722;
   fWeightMatrix0to1[7][19] = 0.902798116728687;
   fWeightMatrix0to1[8][19] = -1.51285691295235;
   fWeightMatrix0to1[9][19] = -6.73196217239359;
   fWeightMatrix0to1[10][19] = 12.9519046043041;
   fWeightMatrix0to1[11][19] = 3.77652135092726;
   fWeightMatrix0to1[12][19] = -1.71002145386399;
   fWeightMatrix0to1[13][19] = 0.267493190263381;
   fWeightMatrix0to1[14][19] = -4.24446853029899;
   fWeightMatrix0to1[15][19] = 5.89319047890381;
   fWeightMatrix0to1[16][19] = 4.53186044411295;
   fWeightMatrix0to1[17][19] = -4.26657769225386;
   fWeightMatrix0to1[18][19] = 1.26843254028983;
   fWeightMatrix0to1[19][19] = 2.63280221440186;
   fWeightMatrix0to1[0][20] = 6.43479751864424;
   fWeightMatrix0to1[1][20] = 40.5693881583808;
   fWeightMatrix0to1[2][20] = -12.6418556580589;
   fWeightMatrix0to1[3][20] = -4.44687511951521;
   fWeightMatrix0to1[4][20] = 15.7114942774493;
   fWeightMatrix0to1[5][20] = -52.4921333672807;
   fWeightMatrix0to1[6][20] = 12.6490682508527;
   fWeightMatrix0to1[7][20] = 19.1129677143293;
   fWeightMatrix0to1[8][20] = -14.8903685671783;
   fWeightMatrix0to1[9][20] = -0.392160030780058;
   fWeightMatrix0to1[10][20] = 35.123654455666;
   fWeightMatrix0to1[11][20] = -17.9180492943585;
   fWeightMatrix0to1[12][20] = 14.2850301335171;
   fWeightMatrix0to1[13][20] = -6.81210316145458;
   fWeightMatrix0to1[14][20] = -5.37359398661365;
   fWeightMatrix0to1[15][20] = 6.18079871641234;
   fWeightMatrix0to1[16][20] = 34.6288500940254;
   fWeightMatrix0to1[17][20] = -23.4751626618325;
   fWeightMatrix0to1[18][20] = -1.88614457352452;
   fWeightMatrix0to1[19][20] = -29.2653689065383;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 2.98100048135249;
   fWeightMatrix1to2[1][0] = -0.889344371149745;
   fWeightMatrix1to2[2][0] = -1.95075453645169;
   fWeightMatrix1to2[3][0] = -0.398365044720877;
   fWeightMatrix1to2[4][0] = -0.336759115303148;
   fWeightMatrix1to2[5][0] = 1.06293968234367;
   fWeightMatrix1to2[6][0] = -1.13479588756993;
   fWeightMatrix1to2[7][0] = -3.82429432991205;
   fWeightMatrix1to2[8][0] = -1.94541254239803;
   fWeightMatrix1to2[9][0] = -0.53830208391709;
   fWeightMatrix1to2[10][0] = -0.961967500543537;
   fWeightMatrix1to2[11][0] = -0.725811140416357;
   fWeightMatrix1to2[12][0] = 0.619263424930887;
   fWeightMatrix1to2[13][0] = 1.25609469498097;
   fWeightMatrix1to2[14][0] = 0.177002779196059;
   fWeightMatrix1to2[15][0] = 0.0239588767943003;
   fWeightMatrix1to2[16][0] = -1.02961587467563;
   fWeightMatrix1to2[17][0] = 0.872887274023313;
   fWeightMatrix1to2[18][0] = -0.106251846755873;
   fWeightMatrix1to2[19][0] = -0.718073356023613;
   fWeightMatrix1to2[20][0] = 0.269363689020468;
   fWeightMatrix1to2[21][0] = -4.21386467143618;
   fWeightMatrix1to2[22][0] = -0.0825219084568034;
   fWeightMatrix1to2[23][0] = -5.03506773158887;
   fWeightMatrix1to2[24][0] = -0.0245033313216406;
   fWeightMatrix1to2[0][1] = 4.49984518496824;
   fWeightMatrix1to2[1][1] = 3.56586529304346;
   fWeightMatrix1to2[2][1] = -0.172150596669179;
   fWeightMatrix1to2[3][1] = 3.26948722318674;
   fWeightMatrix1to2[4][1] = -3.71354205915125;
   fWeightMatrix1to2[5][1] = 4.67744880953072;
   fWeightMatrix1to2[6][1] = -0.992585385489926;
   fWeightMatrix1to2[7][1] = 1.86225953786492;
   fWeightMatrix1to2[8][1] = -1.30445942225902;
   fWeightMatrix1to2[9][1] = 8.59671996876622;
   fWeightMatrix1to2[10][1] = -0.930162535561827;
   fWeightMatrix1to2[11][1] = -1.26614760541347;
   fWeightMatrix1to2[12][1] = -3.04581124305879;
   fWeightMatrix1to2[13][1] = -4.1714678888042;
   fWeightMatrix1to2[14][1] = 2.52366415446622;
   fWeightMatrix1to2[15][1] = -4.97140881423454;
   fWeightMatrix1to2[16][1] = 0.819262867854726;
   fWeightMatrix1to2[17][1] = -2.03563172459402;
   fWeightMatrix1to2[18][1] = -2.05634135082029;
   fWeightMatrix1to2[19][1] = 0.529530784873107;
   fWeightMatrix1to2[20][1] = -12.5305740938003;
   fWeightMatrix1to2[21][1] = -0.0729053946357683;
   fWeightMatrix1to2[22][1] = -6.54146527906544;
   fWeightMatrix1to2[23][1] = -2.75974742584135;
   fWeightMatrix1to2[24][1] = -8.08101015729563;
   fWeightMatrix1to2[0][2] = 2.49861627867649;
   fWeightMatrix1to2[1][2] = 3.22814739159838;
   fWeightMatrix1to2[2][2] = -0.962122124313522;
   fWeightMatrix1to2[3][2] = 0.635236990238671;
   fWeightMatrix1to2[4][2] = -1.48761073076934;
   fWeightMatrix1to2[5][2] = -0.838114941064314;
   fWeightMatrix1to2[6][2] = 0.403164381429917;
   fWeightMatrix1to2[7][2] = 0.040699679933385;
   fWeightMatrix1to2[8][2] = -1.39528137947586;
   fWeightMatrix1to2[9][2] = 3.96837210189052;
   fWeightMatrix1to2[10][2] = 0.23418204086587;
   fWeightMatrix1to2[11][2] = -2.33833649606499;
   fWeightMatrix1to2[12][2] = -0.75712569283681;
   fWeightMatrix1to2[13][2] = 2.10341782189864;
   fWeightMatrix1to2[14][2] = 0.328108516438381;
   fWeightMatrix1to2[15][2] = 2.34280154027306;
   fWeightMatrix1to2[16][2] = 1.85124758205892;
   fWeightMatrix1to2[17][2] = -0.00540188982308523;
   fWeightMatrix1to2[18][2] = 4.51257309342148;
   fWeightMatrix1to2[19][2] = 2.78930821619702;
   fWeightMatrix1to2[20][2] = 1.4967179744556;
   fWeightMatrix1to2[21][2] = -2.87573435916515;
   fWeightMatrix1to2[22][2] = -3.42871299989576;
   fWeightMatrix1to2[23][2] = 1.1767862546716;
   fWeightMatrix1to2[24][2] = -2.39687301271641;
   fWeightMatrix1to2[0][3] = -0.162704748617515;
   fWeightMatrix1to2[1][3] = 0.568187171672644;
   fWeightMatrix1to2[2][3] = -0.786660008330296;
   fWeightMatrix1to2[3][3] = -0.129605662403375;
   fWeightMatrix1to2[4][3] = -0.418240734162237;
   fWeightMatrix1to2[5][3] = 0.366139530328679;
   fWeightMatrix1to2[6][3] = 1.06166723246518;
   fWeightMatrix1to2[7][3] = 2.01621493204589;
   fWeightMatrix1to2[8][3] = 0.708545436841725;
   fWeightMatrix1to2[9][3] = -0.980969791750146;
   fWeightMatrix1to2[10][3] = 0.55098675554172;
   fWeightMatrix1to2[11][3] = 1.00460991586867;
   fWeightMatrix1to2[12][3] = 1.20285536748541;
   fWeightMatrix1to2[13][3] = 0.132772636678831;
   fWeightMatrix1to2[14][3] = -1.62228413469971;
   fWeightMatrix1to2[15][3] = 2.33427562069346;
   fWeightMatrix1to2[16][3] = 0.827424149059191;
   fWeightMatrix1to2[17][3] = 0.773037592465697;
   fWeightMatrix1to2[18][3] = 1.14463990429302;
   fWeightMatrix1to2[19][3] = -0.826987455771976;
   fWeightMatrix1to2[20][3] = -1.32038708459163;
   fWeightMatrix1to2[21][3] = 0.750129269846738;
   fWeightMatrix1to2[22][3] = 0.17608694822834;
   fWeightMatrix1to2[23][3] = 1.25055550215229;
   fWeightMatrix1to2[24][3] = 2.116560708217;
   fWeightMatrix1to2[0][4] = 0.598091381796026;
   fWeightMatrix1to2[1][4] = -2.0286495981071;
   fWeightMatrix1to2[2][4] = -0.832031792471369;
   fWeightMatrix1to2[3][4] = -0.0688533505594581;
   fWeightMatrix1to2[4][4] = 3.45073894779242;
   fWeightMatrix1to2[5][4] = -1.42492732276005;
   fWeightMatrix1to2[6][4] = 1.9201279371889;
   fWeightMatrix1to2[7][4] = 1.04806917631643;
   fWeightMatrix1to2[8][4] = -0.0373062373648944;
   fWeightMatrix1to2[9][4] = -4.12288517816956;
   fWeightMatrix1to2[10][4] = -1.08015560525652;
   fWeightMatrix1to2[11][4] = -2.65002115893509;
   fWeightMatrix1to2[12][4] = 4.25951637434727;
   fWeightMatrix1to2[13][4] = 0.437330287450675;
   fWeightMatrix1to2[14][4] = 2.6227776614604;
   fWeightMatrix1to2[15][4] = -2.50997826926935;
   fWeightMatrix1to2[16][4] = -0.248680242141684;
   fWeightMatrix1to2[17][4] = -1.58541060042488;
   fWeightMatrix1to2[18][4] = -4.53125141921501;
   fWeightMatrix1to2[19][4] = -2.20646836466107;
   fWeightMatrix1to2[20][4] = 0.960333449607939;
   fWeightMatrix1to2[21][4] = -0.237183617453062;
   fWeightMatrix1to2[22][4] = 2.39554467583132;
   fWeightMatrix1to2[23][4] = 2.9588096351628;
   fWeightMatrix1to2[24][4] = 2.92894817320874;
   fWeightMatrix1to2[0][5] = 0.147851578644696;
   fWeightMatrix1to2[1][5] = 1.63931025943772;
   fWeightMatrix1to2[2][5] = -3.47543790640644;
   fWeightMatrix1to2[3][5] = 3.18173643059497;
   fWeightMatrix1to2[4][5] = -5.00322831922344;
   fWeightMatrix1to2[5][5] = 0.398451245649596;
   fWeightMatrix1to2[6][5] = -0.659990725757745;
   fWeightMatrix1to2[7][5] = 0.469858884780941;
   fWeightMatrix1to2[8][5] = -2.67980713025668;
   fWeightMatrix1to2[9][5] = -0.0932221780106124;
   fWeightMatrix1to2[10][5] = -1.44073387956274;
   fWeightMatrix1to2[11][5] = 1.34461409076013;
   fWeightMatrix1to2[12][5] = -3.75431791450443;
   fWeightMatrix1to2[13][5] = 4.58389548061878;
   fWeightMatrix1to2[14][5] = -9.46846319442898;
   fWeightMatrix1to2[15][5] = -0.827601753698658;
   fWeightMatrix1to2[16][5] = 0.81250809535701;
   fWeightMatrix1to2[17][5] = 1.3141680538403;
   fWeightMatrix1to2[18][5] = 2.31234995614859;
   fWeightMatrix1to2[19][5] = -0.121432660079888;
   fWeightMatrix1to2[20][5] = 0.74593460600234;
   fWeightMatrix1to2[21][5] = -5.65996362769676;
   fWeightMatrix1to2[22][5] = -6.99963434702421;
   fWeightMatrix1to2[23][5] = -1.9730624744378;
   fWeightMatrix1to2[24][5] = 0.323530899145418;
   fWeightMatrix1to2[0][6] = -8.3586677477696;
   fWeightMatrix1to2[1][6] = 1.73361966063935;
   fWeightMatrix1to2[2][6] = -1.79603388649441;
   fWeightMatrix1to2[3][6] = 1.23444816590084;
   fWeightMatrix1to2[4][6] = 0.664000254378455;
   fWeightMatrix1to2[5][6] = 1.93570207725062;
   fWeightMatrix1to2[6][6] = -1.30997116612595;
   fWeightMatrix1to2[7][6] = -0.267505031652061;
   fWeightMatrix1to2[8][6] = -2.53100939281351;
   fWeightMatrix1to2[9][6] = -3.29684632754666;
   fWeightMatrix1to2[10][6] = 0.552257519729955;
   fWeightMatrix1to2[11][6] = -0.368867095145401;
   fWeightMatrix1to2[12][6] = -0.24206793073288;
   fWeightMatrix1to2[13][6] = 2.08341811827666;
   fWeightMatrix1to2[14][6] = 0.655064886359298;
   fWeightMatrix1to2[15][6] = 1.05032345805624;
   fWeightMatrix1to2[16][6] = -0.145759973551283;
   fWeightMatrix1to2[17][6] = 0.900019008448938;
   fWeightMatrix1to2[18][6] = 2.19137164302189;
   fWeightMatrix1to2[19][6] = -0.356688504493935;
   fWeightMatrix1to2[20][6] = -2.02344818331881;
   fWeightMatrix1to2[21][6] = -0.81139198448546;
   fWeightMatrix1to2[22][6] = 3.64681256446201;
   fWeightMatrix1to2[23][6] = -2.06927325364759;
   fWeightMatrix1to2[24][6] = 0.0804272519227935;
   fWeightMatrix1to2[0][7] = -2.42260264837557;
   fWeightMatrix1to2[1][7] = 1.30834586648169;
   fWeightMatrix1to2[2][7] = -1.28335462892755;
   fWeightMatrix1to2[3][7] = -0.286134713325176;
   fWeightMatrix1to2[4][7] = -0.28952936758276;
   fWeightMatrix1to2[5][7] = 1.10713069449194;
   fWeightMatrix1to2[6][7] = 4.60121318384243;
   fWeightMatrix1to2[7][7] = 2.17350460118994;
   fWeightMatrix1to2[8][7] = -2.31431812512874;
   fWeightMatrix1to2[9][7] = 2.82077878474855;
   fWeightMatrix1to2[10][7] = 2.03225115453819;
   fWeightMatrix1to2[11][7] = 4.65586348060883;
   fWeightMatrix1to2[12][7] = -2.54928700185054;
   fWeightMatrix1to2[13][7] = 0.153542380455224;
   fWeightMatrix1to2[14][7] = 0.110930933746563;
   fWeightMatrix1to2[15][7] = -1.17257006079247;
   fWeightMatrix1to2[16][7] = 0.734572757174086;
   fWeightMatrix1to2[17][7] = -0.56539677969171;
   fWeightMatrix1to2[18][7] = -1.42940306774572;
   fWeightMatrix1to2[19][7] = 0.905422744388563;
   fWeightMatrix1to2[20][7] = -2.11940712250619;
   fWeightMatrix1to2[21][7] = 1.68684039035675;
   fWeightMatrix1to2[22][7] = -0.642528576967821;
   fWeightMatrix1to2[23][7] = 1.53321852438215;
   fWeightMatrix1to2[24][7] = -7.82125656289166;
   fWeightMatrix1to2[0][8] = -0.0217229830809293;
   fWeightMatrix1to2[1][8] = -0.0395497217791439;
   fWeightMatrix1to2[2][8] = -0.749087958334537;
   fWeightMatrix1to2[3][8] = 0.798704019328036;
   fWeightMatrix1to2[4][8] = -0.0530437262397602;
   fWeightMatrix1to2[5][8] = -0.509276794542699;
   fWeightMatrix1to2[6][8] = -0.218030015809645;
   fWeightMatrix1to2[7][8] = 1.25612206797761;
   fWeightMatrix1to2[8][8] = -1.59623182705913;
   fWeightMatrix1to2[9][8] = 0.840456987405551;
   fWeightMatrix1to2[10][8] = 2.77614929258475;
   fWeightMatrix1to2[11][8] = -0.302868282639425;
   fWeightMatrix1to2[12][8] = 0.0162647777089907;
   fWeightMatrix1to2[13][8] = -0.426236307165708;
   fWeightMatrix1to2[14][8] = 0.333530683142742;
   fWeightMatrix1to2[15][8] = 0.046748797810955;
   fWeightMatrix1to2[16][8] = -6.38909583727644;
   fWeightMatrix1to2[17][8] = 3.05295941756651;
   fWeightMatrix1to2[18][8] = -0.171928501169622;
   fWeightMatrix1to2[19][8] = -4.46889971101704;
   fWeightMatrix1to2[20][8] = -0.29146091101165;
   fWeightMatrix1to2[21][8] = 0.141893349767173;
   fWeightMatrix1to2[22][8] = -0.391889141936339;
   fWeightMatrix1to2[23][8] = 0.239583573173983;
   fWeightMatrix1to2[24][8] = -0.562888833953706;
   fWeightMatrix1to2[0][9] = 0.710373172313437;
   fWeightMatrix1to2[1][9] = -1.08068114335825;
   fWeightMatrix1to2[2][9] = 1.08214458100191;
   fWeightMatrix1to2[3][9] = 0.526328974353002;
   fWeightMatrix1to2[4][9] = 0.565141036969351;
   fWeightMatrix1to2[5][9] = -1.24381734400243;
   fWeightMatrix1to2[6][9] = -1.4607041994547;
   fWeightMatrix1to2[7][9] = -3.52811294698935;
   fWeightMatrix1to2[8][9] = -1.6876070910334;
   fWeightMatrix1to2[9][9] = 1.38020516555329;
   fWeightMatrix1to2[10][9] = -0.726775918720542;
   fWeightMatrix1to2[11][9] = -1.85260673095987;
   fWeightMatrix1to2[12][9] = -1.80515392796155;
   fWeightMatrix1to2[13][9] = -1.06637045705365;
   fWeightMatrix1to2[14][9] = 2.53015544146383;
   fWeightMatrix1to2[15][9] = -3.5030898229459;
   fWeightMatrix1to2[16][9] = -0.842850007618066;
   fWeightMatrix1to2[17][9] = -1.39303510056763;
   fWeightMatrix1to2[18][9] = -0.66375848275568;
   fWeightMatrix1to2[19][9] = 1.36063586428939;
   fWeightMatrix1to2[20][9] = 2.33662941616141;
   fWeightMatrix1to2[21][9] = -1.37960178848422;
   fWeightMatrix1to2[22][9] = -0.349034164458797;
   fWeightMatrix1to2[23][9] = -1.0900299239807;
   fWeightMatrix1to2[24][9] = -2.8126998710997;
   fWeightMatrix1to2[0][10] = 2.9686319884848;
   fWeightMatrix1to2[1][10] = -2.14186260037736;
   fWeightMatrix1to2[2][10] = 0.533417316452489;
   fWeightMatrix1to2[3][10] = 0.0762052922313507;
   fWeightMatrix1to2[4][10] = 7.21720688602571;
   fWeightMatrix1to2[5][10] = -1.07356854560689;
   fWeightMatrix1to2[6][10] = 1.04881992660624;
   fWeightMatrix1to2[7][10] = -0.533448670429126;
   fWeightMatrix1to2[8][10] = 1.41441036133311;
   fWeightMatrix1to2[9][10] = -3.67256310639778;
   fWeightMatrix1to2[10][10] = 1.4347926506762;
   fWeightMatrix1to2[11][10] = 0.713104147051752;
   fWeightMatrix1to2[12][10] = 5.17198919704248;
   fWeightMatrix1to2[13][10] = -7.99841080408183;
   fWeightMatrix1to2[14][10] = 0.792352560872972;
   fWeightMatrix1to2[15][10] = -2.12953944533264;
   fWeightMatrix1to2[16][10] = 1.95085994947045;
   fWeightMatrix1to2[17][10] = -0.851719003437487;
   fWeightMatrix1to2[18][10] = -3.61158698853996;
   fWeightMatrix1to2[19][10] = 0.775668813108761;
   fWeightMatrix1to2[20][10] = -1.28002607009821;
   fWeightMatrix1to2[21][10] = 4.12704662224059;
   fWeightMatrix1to2[22][10] = 0.68790212582592;
   fWeightMatrix1to2[23][10] = -0.424694380318697;
   fWeightMatrix1to2[24][10] = 2.74978155910623;
   fWeightMatrix1to2[0][11] = 0.412679827916725;
   fWeightMatrix1to2[1][11] = 0.0279311320807651;
   fWeightMatrix1to2[2][11] = -2.19214338565547;
   fWeightMatrix1to2[3][11] = 0.547844054367298;
   fWeightMatrix1to2[4][11] = 0.284453442452407;
   fWeightMatrix1to2[5][11] = -1.24823666965387;
   fWeightMatrix1to2[6][11] = 0.339170541911053;
   fWeightMatrix1to2[7][11] = 4.38932916490414;
   fWeightMatrix1to2[8][11] = -3.23579486392314;
   fWeightMatrix1to2[9][11] = -1.07467601337945;
   fWeightMatrix1to2[10][11] = 2.34923737937239;
   fWeightMatrix1to2[11][11] = -1.14353588731578;
   fWeightMatrix1to2[12][11] = 0.488376388851887;
   fWeightMatrix1to2[13][11] = 0.759541330840861;
   fWeightMatrix1to2[14][11] = 0.496569502351831;
   fWeightMatrix1to2[15][11] = -1.25718674221038;
   fWeightMatrix1to2[16][11] = 3.28195442459468;
   fWeightMatrix1to2[17][11] = 1.6458493829905;
   fWeightMatrix1to2[18][11] = 0.347073548110657;
   fWeightMatrix1to2[19][11] = 0.783360977274736;
   fWeightMatrix1to2[20][11] = 2.36937449907595;
   fWeightMatrix1to2[21][11] = 0.120620697622743;
   fWeightMatrix1to2[22][11] = 0.612407195233081;
   fWeightMatrix1to2[23][11] = 1.17304595736868;
   fWeightMatrix1to2[24][11] = 1.53686693295229;
   fWeightMatrix1to2[0][12] = -0.648832627868969;
   fWeightMatrix1to2[1][12] = -3.26973120388309;
   fWeightMatrix1to2[2][12] = -1.16133272670275;
   fWeightMatrix1to2[3][12] = -3.01028568843406;
   fWeightMatrix1to2[4][12] = 1.22620640713871;
   fWeightMatrix1to2[5][12] = 1.79675760313316;
   fWeightMatrix1to2[6][12] = -0.435497542692517;
   fWeightMatrix1to2[7][12] = -0.829205143220701;
   fWeightMatrix1to2[8][12] = -0.542187581821645;
   fWeightMatrix1to2[9][12] = 1.8228171766308;
   fWeightMatrix1to2[10][12] = 0.325580653021573;
   fWeightMatrix1to2[11][12] = 0.0497969207748462;
   fWeightMatrix1to2[12][12] = -0.753640920779731;
   fWeightMatrix1to2[13][12] = 1.10181461729469;
   fWeightMatrix1to2[14][12] = -0.317084590791117;
   fWeightMatrix1to2[15][12] = -1.22831098023201;
   fWeightMatrix1to2[16][12] = -1.06017698185107;
   fWeightMatrix1to2[17][12] = 0.323944902717031;
   fWeightMatrix1to2[18][12] = -6.13548961161501;
   fWeightMatrix1to2[19][12] = 0.421583741288599;
   fWeightMatrix1to2[20][12] = -0.0216354610157577;
   fWeightMatrix1to2[21][12] = -0.841621556167647;
   fWeightMatrix1to2[22][12] = -0.534051861638183;
   fWeightMatrix1to2[23][12] = -1.29179104273435;
   fWeightMatrix1to2[24][12] = -3.16352727460116;
   fWeightMatrix1to2[0][13] = -0.22163965974514;
   fWeightMatrix1to2[1][13] = -0.27078229641399;
   fWeightMatrix1to2[2][13] = -1.18517639086284;
   fWeightMatrix1to2[3][13] = 0.320109104221605;
   fWeightMatrix1to2[4][13] = -0.17889880331812;
   fWeightMatrix1to2[5][13] = 0.145729666680855;
   fWeightMatrix1to2[6][13] = -0.586003262910494;
   fWeightMatrix1to2[7][13] = -1.26037757738401;
   fWeightMatrix1to2[8][13] = -1.38901580597172;
   fWeightMatrix1to2[9][13] = 0.421310883250396;
   fWeightMatrix1to2[10][13] = 3.65620491072589;
   fWeightMatrix1to2[11][13] = 0.907224855958525;
   fWeightMatrix1to2[12][13] = -0.0199455394822286;
   fWeightMatrix1to2[13][13] = 0.427684815062541;
   fWeightMatrix1to2[14][13] = -0.326982207133038;
   fWeightMatrix1to2[15][13] = 0.409721916866554;
   fWeightMatrix1to2[16][13] = 0.352216007957154;
   fWeightMatrix1to2[17][13] = 8.03932779092031;
   fWeightMatrix1to2[18][13] = 0.0286486503361692;
   fWeightMatrix1to2[19][13] = 3.22098951914914;
   fWeightMatrix1to2[20][13] = -0.553692359614304;
   fWeightMatrix1to2[21][13] = -0.0240863663340223;
   fWeightMatrix1to2[22][13] = -0.320577314416518;
   fWeightMatrix1to2[23][13] = -0.501961269934593;
   fWeightMatrix1to2[24][13] = 0.0278838817613511;
   fWeightMatrix1to2[0][14] = -0.319260225845688;
   fWeightMatrix1to2[1][14] = -0.154082898113976;
   fWeightMatrix1to2[2][14] = -1.01331436466674;
   fWeightMatrix1to2[3][14] = 0.781688172449717;
   fWeightMatrix1to2[4][14] = -0.0132617328297904;
   fWeightMatrix1to2[5][14] = -0.111200609246151;
   fWeightMatrix1to2[6][14] = -3.38139903154174;
   fWeightMatrix1to2[7][14] = 0.548946295937013;
   fWeightMatrix1to2[8][14] = 2.42219683619852;
   fWeightMatrix1to2[9][14] = 0.293783982902813;
   fWeightMatrix1to2[10][14] = -1.73462874732183;
   fWeightMatrix1to2[11][14] = -2.31077256263566;
   fWeightMatrix1to2[12][14] = 0.630306621857891;
   fWeightMatrix1to2[13][14] = 0.395789470747343;
   fWeightMatrix1to2[14][14] = 0.296061573584924;
   fWeightMatrix1to2[15][14] = -0.301174430226601;
   fWeightMatrix1to2[16][14] = -3.99583044453077;
   fWeightMatrix1to2[17][14] = -3.98794603453641;
   fWeightMatrix1to2[18][14] = -0.444940739011864;
   fWeightMatrix1to2[19][14] = -5.99464469196393;
   fWeightMatrix1to2[20][14] = 0.771828164576145;
   fWeightMatrix1to2[21][14] = -0.524837531496805;
   fWeightMatrix1to2[22][14] = -0.0990457130554502;
   fWeightMatrix1to2[23][14] = -0.521471531444737;
   fWeightMatrix1to2[24][14] = -0.0423737934045968;
   fWeightMatrix1to2[0][15] = 1.44428437218455;
   fWeightMatrix1to2[1][15] = -1.27401678461339;
   fWeightMatrix1to2[2][15] = -9.58482605779144;
   fWeightMatrix1to2[3][15] = -3.30397837186738;
   fWeightMatrix1to2[4][15] = 0.679270499905971;
   fWeightMatrix1to2[5][15] = 1.44470473448194;
   fWeightMatrix1to2[6][15] = -2.61936652659782;
   fWeightMatrix1to2[7][15] = 3.49468645007201;
   fWeightMatrix1to2[8][15] = 3.68609705680208;
   fWeightMatrix1to2[9][15] = 0.46026532962961;
   fWeightMatrix1to2[10][15] = 0.443920806591786;
   fWeightMatrix1to2[11][15] = -0.148550446256689;
   fWeightMatrix1to2[12][15] = 0.0308426170724058;
   fWeightMatrix1to2[13][15] = -0.881667609456727;
   fWeightMatrix1to2[14][15] = 1.26357537332235;
   fWeightMatrix1to2[15][15] = -6.48636914275113;
   fWeightMatrix1to2[16][15] = -2.32191479412917;
   fWeightMatrix1to2[17][15] = 1.0687900031897;
   fWeightMatrix1to2[18][15] = -1.44931852614163;
   fWeightMatrix1to2[19][15] = -4.84513956412417;
   fWeightMatrix1to2[20][15] = -0.80599048308116;
   fWeightMatrix1to2[21][15] = -3.19612861057566;
   fWeightMatrix1to2[22][15] = 0.564485856900901;
   fWeightMatrix1to2[23][15] = -3.24311442169299;
   fWeightMatrix1to2[24][15] = -0.857700856970462;
   fWeightMatrix1to2[0][16] = -8.89406020637818;
   fWeightMatrix1to2[1][16] = 4.01625876431863;
   fWeightMatrix1to2[2][16] = 0.904055346458721;
   fWeightMatrix1to2[3][16] = -2.08627277890862;
   fWeightMatrix1to2[4][16] = -2.88037135836646;
   fWeightMatrix1to2[5][16] = 0.771753470249452;
   fWeightMatrix1to2[6][16] = -1.35081091253346;
   fWeightMatrix1to2[7][16] = -2.21024861567881;
   fWeightMatrix1to2[8][16] = 3.10643133673924;
   fWeightMatrix1to2[9][16] = 6.25655744909043;
   fWeightMatrix1to2[10][16] = 0.199587773569817;
   fWeightMatrix1to2[11][16] = 0.678784418534621;
   fWeightMatrix1to2[12][16] = -3.17863796385468;
   fWeightMatrix1to2[13][16] = 4.22292650740844;
   fWeightMatrix1to2[14][16] = 1.50372617908299;
   fWeightMatrix1to2[15][16] = -2.61436652196431;
   fWeightMatrix1to2[16][16] = -4.00278050069278;
   fWeightMatrix1to2[17][16] = 1.60392738504027;
   fWeightMatrix1to2[18][16] = -1.61664374982793;
   fWeightMatrix1to2[19][16] = -2.65824133722562;
   fWeightMatrix1to2[20][16] = -1.06626351569404;
   fWeightMatrix1to2[21][16] = -0.0893075940785434;
   fWeightMatrix1to2[22][16] = -1.83355645027;
   fWeightMatrix1to2[23][16] = -3.12886886928939;
   fWeightMatrix1to2[24][16] = -5.00962785719174;
   fWeightMatrix1to2[0][17] = -1.14124401884072;
   fWeightMatrix1to2[1][17] = 2.50119196211464;
   fWeightMatrix1to2[2][17] = -0.157732453048538;
   fWeightMatrix1to2[3][17] = 2.23181456081763;
   fWeightMatrix1to2[4][17] = -2.13751504937488;
   fWeightMatrix1to2[5][17] = -2.00075251999275;
   fWeightMatrix1to2[6][17] = -1.93519029554426;
   fWeightMatrix1to2[7][17] = -2.24934141124785;
   fWeightMatrix1to2[8][17] = 1.99533032711462;
   fWeightMatrix1to2[9][17] = -0.646714967763148;
   fWeightMatrix1to2[10][17] = 0.181719676463632;
   fWeightMatrix1to2[11][17] = -1.61671634227136;
   fWeightMatrix1to2[12][17] = -1.53796191990309;
   fWeightMatrix1to2[13][17] = -2.7352206363392;
   fWeightMatrix1to2[14][17] = 2.22634353887468;
   fWeightMatrix1to2[15][17] = -0.348039706498611;
   fWeightMatrix1to2[16][17] = 0.807284267126303;
   fWeightMatrix1to2[17][17] = -0.135528756858045;
   fWeightMatrix1to2[18][17] = 3.94338114518345;
   fWeightMatrix1to2[19][17] = -1.37976151838437;
   fWeightMatrix1to2[20][17] = 0.750410048606725;
   fWeightMatrix1to2[21][17] = 0.26973518370365;
   fWeightMatrix1to2[22][17] = -1.12288490269707;
   fWeightMatrix1to2[23][17] = 3.59219483408941;
   fWeightMatrix1to2[24][17] = 2.6994546241117;
   fWeightMatrix1to2[0][18] = -4.89235946106729;
   fWeightMatrix1to2[1][18] = 2.80450043206311;
   fWeightMatrix1to2[2][18] = -0.930537069358505;
   fWeightMatrix1to2[3][18] = 4.27444693284744;
   fWeightMatrix1to2[4][18] = -8.08836829452059;
   fWeightMatrix1to2[5][18] = 0.0432764292194455;
   fWeightMatrix1to2[6][18] = -4.97790086937574;
   fWeightMatrix1to2[7][18] = -1.21034442668813;
   fWeightMatrix1to2[8][18] = -3.02868739191318;
   fWeightMatrix1to2[9][18] = 5.00291731646029;
   fWeightMatrix1to2[10][18] = -0.533425808642854;
   fWeightMatrix1to2[11][18] = -0.0993375962036653;
   fWeightMatrix1to2[12][18] = -12.978606438595;
   fWeightMatrix1to2[13][18] = 0.164532842845556;
   fWeightMatrix1to2[14][18] = 0.673630183876999;
   fWeightMatrix1to2[15][18] = 2.02946430123712;
   fWeightMatrix1to2[16][18] = -1.95610583323632;
   fWeightMatrix1to2[17][18] = 1.10884109826103;
   fWeightMatrix1to2[18][18] = 7.1316743964774;
   fWeightMatrix1to2[19][18] = 0.475564989702005;
   fWeightMatrix1to2[20][18] = 0.0387586573730908;
   fWeightMatrix1to2[21][18] = -0.213435324699625;
   fWeightMatrix1to2[22][18] = -4.3702188459759;
   fWeightMatrix1to2[23][18] = -0.947427061492812;
   fWeightMatrix1to2[24][18] = -2.60217063318189;
   fWeightMatrix1to2[0][19] = 0.663707431876142;
   fWeightMatrix1to2[1][19] = -0.0744846570962958;
   fWeightMatrix1to2[2][19] = -3.25903986110513;
   fWeightMatrix1to2[3][19] = 1.07932773031692;
   fWeightMatrix1to2[4][19] = -0.104411390433443;
   fWeightMatrix1to2[5][19] = 0.57410716224096;
   fWeightMatrix1to2[6][19] = 0.0971407363599088;
   fWeightMatrix1to2[7][19] = -0.000139239381301668;
   fWeightMatrix1to2[8][19] = 0.133477181305105;
   fWeightMatrix1to2[9][19] = 0.619465696481804;
   fWeightMatrix1to2[10][19] = 1.28250761260942;
   fWeightMatrix1to2[11][19] = -2.32116077844548;
   fWeightMatrix1to2[12][19] = 0.610018653552044;
   fWeightMatrix1to2[13][19] = -0.964846640122717;
   fWeightMatrix1to2[14][19] = -0.633965209746874;
   fWeightMatrix1to2[15][19] = 0.179799062282642;
   fWeightMatrix1to2[16][19] = -2.62974324504397;
   fWeightMatrix1to2[17][19] = 6.0248408436385;
   fWeightMatrix1to2[18][19] = -0.415525065855234;
   fWeightMatrix1to2[19][19] = 0.303050290284562;
   fWeightMatrix1to2[20][19] = 0.810551626149296;
   fWeightMatrix1to2[21][19] = 0.0317646590821951;
   fWeightMatrix1to2[22][19] = -0.853758619070316;
   fWeightMatrix1to2[23][19] = -0.635456549444077;
   fWeightMatrix1to2[24][19] = -0.810274076213549;
   fWeightMatrix1to2[0][20] = -3.55494724799947;
   fWeightMatrix1to2[1][20] = -1.4239156902263;
   fWeightMatrix1to2[2][20] = 3.14659445249942;
   fWeightMatrix1to2[3][20] = -5.35905730210099;
   fWeightMatrix1to2[4][20] = -6.58525474787276;
   fWeightMatrix1to2[5][20] = -3.35754482843868;
   fWeightMatrix1to2[6][20] = -2.0658410529648;
   fWeightMatrix1to2[7][20] = 0.893977158933717;
   fWeightMatrix1to2[8][20] = -1.3739861704632;
   fWeightMatrix1to2[9][20] = -2.30987819702042;
   fWeightMatrix1to2[10][20] = -6.16000327186776;
   fWeightMatrix1to2[11][20] = -1.99935169703632;
   fWeightMatrix1to2[12][20] = -5.25287599837529;
   fWeightMatrix1to2[13][20] = -0.81189195889206;
   fWeightMatrix1to2[14][20] = -7.38545644703006;
   fWeightMatrix1to2[15][20] = 5.18042280005617;
   fWeightMatrix1to2[16][20] = 0.868244836467217;
   fWeightMatrix1to2[17][20] = -1.06721692484526;
   fWeightMatrix1to2[18][20] = 10.2546698944005;
   fWeightMatrix1to2[19][20] = -1.5363276003704;
   fWeightMatrix1to2[20][20] = -2.75381713205319;
   fWeightMatrix1to2[21][20] = -5.02833678332176;
   fWeightMatrix1to2[22][20] = 1.20325248897051;
   fWeightMatrix1to2[23][20] = -0.517159516198573;
   fWeightMatrix1to2[24][20] = 1.74292511342608;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 1.10896753351431;
   fWeightMatrix2to3[1][0] = -3.19075551945787;
   fWeightMatrix2to3[2][0] = -0.357578432039089;
   fWeightMatrix2to3[0][1] = -1.35404328157817;
   fWeightMatrix2to3[1][1] = 2.44254536254419;
   fWeightMatrix2to3[2][1] = 1.09213162343387;
   fWeightMatrix2to3[0][2] = 1.6282966360273;
   fWeightMatrix2to3[1][2] = 0.0977210873867637;
   fWeightMatrix2to3[2][2] = -2.13232875653669;
   fWeightMatrix2to3[0][3] = -2.71041563966145;
   fWeightMatrix2to3[1][3] = -3.97304320218593;
   fWeightMatrix2to3[2][3] = 1.87972250763272;
   fWeightMatrix2to3[0][4] = -1.92568353244041;
   fWeightMatrix2to3[1][4] = 2.05116065969736;
   fWeightMatrix2to3[2][4] = 1.30333861804768;
   fWeightMatrix2to3[0][5] = 0.287687647592525;
   fWeightMatrix2to3[1][5] = 4.50342130947606;
   fWeightMatrix2to3[2][5] = 1.80487049596021;
   fWeightMatrix2to3[0][6] = 0.510010257059264;
   fWeightMatrix2to3[1][6] = 1.81059177665116;
   fWeightMatrix2to3[2][6] = -2.55818429288437;
   fWeightMatrix2to3[0][7] = 0.914306006417116;
   fWeightMatrix2to3[1][7] = -0.131654827687628;
   fWeightMatrix2to3[2][7] = -1.0823754647589;
   fWeightMatrix2to3[0][8] = -0.60478351815069;
   fWeightMatrix2to3[1][8] = -0.687056204338909;
   fWeightMatrix2to3[2][8] = 0.890726669719262;
   fWeightMatrix2to3[0][9] = 0.972882322854195;
   fWeightMatrix2to3[1][9] = 0.860379443206901;
   fWeightMatrix2to3[2][9] = -0.995360852557204;
   fWeightMatrix2to3[0][10] = 0.461229434400377;
   fWeightMatrix2to3[1][10] = -0.183093654295474;
   fWeightMatrix2to3[2][10] = -0.675915716842079;
   fWeightMatrix2to3[0][11] = -3.09199370566701;
   fWeightMatrix2to3[1][11] = -1.056148521637;
   fWeightMatrix2to3[2][11] = 1.58653123145191;
   fWeightMatrix2to3[0][12] = -3.7561598294405;
   fWeightMatrix2to3[1][12] = 5.23389584829878;
   fWeightMatrix2to3[2][12] = 0.657786359970008;
   fWeightMatrix2to3[0][13] = -2.08333182419885;
   fWeightMatrix2to3[1][13] = 1.76760123552704;
   fWeightMatrix2to3[2][13] = 1.00328087368142;
   fWeightMatrix2to3[0][14] = 0.645395684825654;
   fWeightMatrix2to3[1][14] = 3.06005107778855;
   fWeightMatrix2to3[2][14] = 0.394987857460514;
   fWeightMatrix2to3[0][15] = -2.89052693072402;
   fWeightMatrix2to3[1][15] = -0.844908174273537;
   fWeightMatrix2to3[2][15] = 2.66023858082561;
   fWeightMatrix2to3[0][16] = -0.965075965518353;
   fWeightMatrix2to3[1][16] = 0.0420960646843142;
   fWeightMatrix2to3[2][16] = 2.0828550819416;
   fWeightMatrix2to3[0][17] = -0.814581485578329;
   fWeightMatrix2to3[1][17] = 0.125031151190141;
   fWeightMatrix2to3[2][17] = 1.02762008171776;
   fWeightMatrix2to3[0][18] = 1.614933485494;
   fWeightMatrix2to3[1][18] = -0.123496405162141;
   fWeightMatrix2to3[2][18] = -0.692649474952937;
   fWeightMatrix2to3[0][19] = 1.29091244509101;
   fWeightMatrix2to3[1][19] = -0.133613625691521;
   fWeightMatrix2to3[2][19] = -1.69229062493537;
   fWeightMatrix2to3[0][20] = -3.92295312529287;
   fWeightMatrix2to3[1][20] = 1.08887647963851;
   fWeightMatrix2to3[2][20] = 2.75375113832459;
   fWeightMatrix2to3[0][21] = 3.20963075762749;
   fWeightMatrix2to3[1][21] = 2.32529522102545;
   fWeightMatrix2to3[2][21] = -1.92328228897329;
   fWeightMatrix2to3[0][22] = 1.54665916769374;
   fWeightMatrix2to3[1][22] = -1.62433002389781;
   fWeightMatrix2to3[2][22] = -1.05983344885792;
   fWeightMatrix2to3[0][23] = 0.0650372687729517;
   fWeightMatrix2to3[1][23] = -2.48264878904242;
   fWeightMatrix2to3[2][23] = -0.879148295050318;
   fWeightMatrix2to3[0][24] = -1.96352846723678;
   fWeightMatrix2to3[1][24] = -5.46869877751589;
   fWeightMatrix2to3[2][24] = 1.97583236689135;
   fWeightMatrix2to3[0][25] = -2.52497577199324;
   fWeightMatrix2to3[1][25] = -1.78668767902506;
   fWeightMatrix2to3[2][25] = -1.54408159874651;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 6.09229637608502;
   fWeightMatrix3to4[0][1] = -3.02256720998603;
   fWeightMatrix3to4[0][2] = -6.50087874872754;
   fWeightMatrix3to4[0][3] = 0.658069895411633;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 66.8327102661;
   fMax_1[0][0] = 2426.51416016;
   fMin_1[1][0] = 33.2677688599;
   fMax_1[1][0] = 5507.72949219;
   fMin_1[2][0] = 33.2677688599;
   fMax_1[2][0] = 5507.72949219;
   fMin_1[0][1] = 17.2699775696;
   fMax_1[0][1] = 2311.00366211;
   fMin_1[1][1] = 13.9813117981;
   fMax_1[1][1] = 4909.22119141;
   fMin_1[2][1] = 13.9813117981;
   fMax_1[2][1] = 4909.22119141;
   fMin_1[0][2] = 60.0897598267;
   fMax_1[0][2] = 1425.15393066;
   fMin_1[1][2] = 60.0252151489;
   fMax_1[1][2] = 2812.28125;
   fMin_1[2][2] = 60.0252151489;
   fMax_1[2][2] = 2812.28125;
   fMin_1[0][3] = 7.62939453125e-06;
   fMax_1[0][3] = 860.468444824;
   fMin_1[1][3] = 3.81469726562e-06;
   fMax_1[1][3] = 1695.02734375;
   fMin_1[2][3] = 3.81469726562e-06;
   fMax_1[2][3] = 1695.02734375;
   fMin_1[0][4] = 0.395419180393;
   fMax_1[0][4] = 5.1114897728;
   fMin_1[1][4] = 0.379585266113;
   fMax_1[1][4] = 5.68194293976;
   fMin_1[2][4] = 0.379585266113;
   fMax_1[2][4] = 5.68194293976;
   fMin_1[0][5] = 31.8425750732;
   fMax_1[0][5] = 1090.74365234;
   fMin_1[1][5] = 30.3689727783;
   fMax_1[1][5] = 3027.66625977;
   fMin_1[2][5] = 30.3689727783;
   fMax_1[2][5] = 3027.66625977;
   fMin_1[0][6] = -870.999145508;
   fMax_1[0][6] = 862.295288086;
   fMin_1[1][6] = -1362.64111328;
   fMax_1[1][6] = 1719.17687988;
   fMin_1[2][6] = -1362.64111328;
   fMax_1[2][6] = 1719.17687988;
   fMin_1[0][7] = 0.00366772944108;
   fMax_1[0][7] = 8.2374048233;
   fMin_1[1][7] = 0.00215380825102;
   fMax_1[1][7] = 10.4536933899;
   fMin_1[2][7] = 0.00215380825102;
   fMax_1[2][7] = 10.4536933899;
   fMin_1[0][8] = 60.0203704834;
   fMax_1[0][8] = 1295.66699219;
   fMin_1[1][8] = 60.0203704834;
   fMax_1[1][8] = 1963.10424805;
   fMin_1[2][8] = 60.0203704834;
   fMax_1[2][8] = 1963.10424805;
   fMin_1[0][9] = -755.58782959;
   fMax_1[0][9] = 674.663696289;
   fMin_1[1][9] = -961.891723633;
   fMax_1[1][9] = 1489.59179688;
   fMin_1[2][9] = -961.891723633;
   fMax_1[2][9] = 1489.59179688;
   fMin_1[0][10] = 0.500020980835;
   fMax_1[0][10] = 5.5945224762;
   fMin_1[1][10] = 0.500000059605;
   fMax_1[1][10] = 5.66989469528;
   fMin_1[2][10] = 0.500000059605;
   fMax_1[2][10] = 5.66989469528;
   fMin_1[0][11] = 31.4379367828;
   fMax_1[0][11] = 1241.76513672;
   fMin_1[1][11] = 30.1282482147;
   fMax_1[1][11] = 2222.31030273;
   fMin_1[2][11] = 30.1282482147;
   fMax_1[2][11] = 2222.31030273;
   fMin_1[0][12] = -791.472106934;
   fMax_1[0][12] = 840.090026855;
   fMin_1[1][12] = -895.672058105;
   fMax_1[1][12] = 1644.93835449;
   fMin_1[2][12] = -895.672058105;
   fMax_1[2][12] = 1644.93835449;
   fMin_1[0][13] = 0.0018430177588;
   fMax_1[0][13] = 8.91576004028;
   fMin_1[1][13] = 0.00147921941243;
   fMax_1[1][13] = 10.1729364395;
   fMin_1[2][13] = 0.00147921941243;
   fMax_1[2][13] = 10.1729364395;
   fMin_1[0][14] = -3.14159107208;
   fMax_1[0][14] = 3.14159178734;
   fMin_1[1][14] = -3.14159226418;
   fMax_1[1][14] = 3.14159178734;
   fMin_1[2][14] = -3.14159226418;
   fMax_1[2][14] = 3.14159178734;
   fMin_1[0][15] = 31.2111606598;
   fMax_1[0][15] = 1194.1036377;
   fMin_1[1][15] = 30.5801753998;
   fMax_1[1][15] = 2064.86572266;
   fMin_1[2][15] = 30.5801753998;
   fMax_1[2][15] = 2064.86572266;
   fMin_1[0][16] = -757.706237793;
   fMax_1[0][16] = 753.565551758;
   fMin_1[1][16] = -985.94921875;
   fMax_1[1][16] = 1453.90917969;
   fMin_1[2][16] = -985.94921875;
   fMax_1[2][16] = 1453.90917969;
   fMin_1[0][17] = -3.14159059525;
   fMax_1[0][17] = 3.14159178734;
   fMin_1[1][17] = -3.14159250259;
   fMax_1[1][17] = 3.14159202576;
   fMin_1[2][17] = -3.14159250259;
   fMax_1[2][17] = 3.14159202576;
   fMin_1[0][18] = 0.611416637897;
   fMax_1[0][18] = 1286.62390137;
   fMin_1[1][18] = 1.36658203602;
   fMax_1[1][18] = 2497.38452148;
   fMin_1[2][18] = 0.611416637897;
   fMax_1[2][18] = 2497.38452148;
   fMin_1[0][19] = -764.301574707;
   fMax_1[0][19] = 775.467712402;
   fMin_1[1][19] = -940.587097168;
   fMax_1[1][19] = 1612.18518066;
   fMin_1[2][19] = -940.587097168;
   fMax_1[2][19] = 1612.18518066;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 20;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<20;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
