// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Fri Jan 10 15:16:40 2020
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 8293545
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "550" [Number of training cycles]
HiddenLayers: "N,N+5,3" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [31.8515205383,5348.45361328]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [13.9813117981,4877.60791016]
j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                                                      'D'    [60.025062561,2697.76367188]
j1j2_absdelPt                 j1j2_absdelPt                 j1j2_absdelPt                 j1j2_absdelPt                                                   'D'    [3.81469726562e-06,1557.57641602]
j1j2_delR                     j1j2_delR                     j1j2_delR                     j1j2_delR                                                       'D'    [0.347917675972,5.68921756744]
whadb_sumPt                   whadb_sumPt                   whadb_sumPt                   whadb_sumPt                                                     'D'    [30.5779666901,2559.47729492]
whadb_delPt                   whadb_delPt                   whadb_delPt                   whadb_delPt                                                     'D'    [-1405.72998047,1577.42077637]
whadb_delR                    whadb_delR                    whadb_delR                    whadb_delR                                                      'D'    [0.0013404173078,9.45198535919]
hadblepton_sumPt              hadblepton_sumPt              hadblepton_sumPt              hadblepton_sumPt                                                'D'    [60.0203704834,1615.55944824]
hadblepton_delPt              hadblepton_delPt              hadblepton_delPt              hadblepton_delPt                                                'D'    [-775.365600586,1340.12573242]
hadblepton_delR               hadblepton_delR               hadblepton_delR               hadblepton_delR                                                 'D'    [0.500000238419,5.59625434875]
hadwlepton_sumPt              hadwlepton_sumPt              hadwlepton_sumPt              hadwlepton_sumPt                                                'D'    [30.4070301056,2222.31030273]
hadwlepton_delPt              hadwlepton_delPt              hadwlepton_delPt              hadwlepton_delPt                                                'D'    [-809.493469238,1631.58105469]
hadwlepton_delR               hadwlepton_delR               hadwlepton_delR               hadwlepton_delR                                                 'D'    [0.0018430177588,9.91743087769]
hadbmet_delPhi                hadbmet_delPhi                hadbmet_delPhi                hadbmet_delPhi                                                  'D'    [-3.14159107208,3.14159250259]
hadbmet_sumPt                 hadbmet_sumPt                 hadbmet_sumPt                 hadbmet_sumPt                                                   'D'    [30.5801753998,2064.86572266]
hadbmet_delPt                 hadbmet_delPt                 hadbmet_delPt                 hadbmet_delPt                                                   'D'    [-985.94921875,1119.99047852]
hadwmet_delPhi                hadwmet_delPhi                hadwmet_delPhi                hadwmet_delPhi                                                  'D'    [-3.14159250259,3.14159178734]
hadwmet_sumPt                 hadwmet_sumPt                 hadwmet_sumPt                 hadwmet_sumPt                                                   'D'    [0.611416637897,2449.66552734]
hadwmet_delPt                 hadwmet_delPt                 hadwmet_delPt                 hadwmet_delPt                                                   'D'    [-940.587097168,1606.44128418]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass", "j1j2_sumPt", "j1j2_absdelPt", "j1j2_delR", "whadb_sumPt", "whadb_delPt", "whadb_delR", "hadblepton_sumPt", "hadblepton_delPt", "hadblepton_delR", "hadwlepton_sumPt", "hadwlepton_delPt", "hadwlepton_delR", "hadbmet_delPhi", "hadbmet_sumPt", "hadbmet_delPt", "hadwmet_delPhi", "hadwmet_sumPt", "hadwmet_delPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 0.99999988079071;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';
      fType[16] = 'D';
      fType[17] = 'D';
      fType[18] = 'D';
      fType[19] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][20];
   double fMax_1[3][20];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[21][21];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[26][21];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[4][26];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][4];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 21; fWeights[0] = new double[21]; 
   fLayerSize[1] = 21; fWeights[1] = new double[21]; 
   fLayerSize[2] = 26; fWeights[2] = new double[26]; 
   fLayerSize[3] = 4; fWeights[3] = new double[4]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 15.3825947009758;
   fWeightMatrix0to1[1][0] = 94.3965598739208;
   fWeightMatrix0to1[2][0] = 0.935790178264567;
   fWeightMatrix0to1[3][0] = 6.11157805082467;
   fWeightMatrix0to1[4][0] = -29.9699259064795;
   fWeightMatrix0to1[5][0] = 18.8339187510419;
   fWeightMatrix0to1[6][0] = 7.45975966069197;
   fWeightMatrix0to1[7][0] = 29.3655397205345;
   fWeightMatrix0to1[8][0] = -65.303649165117;
   fWeightMatrix0to1[9][0] = -1.61038261363128;
   fWeightMatrix0to1[10][0] = -29.1049574708534;
   fWeightMatrix0to1[11][0] = -0.0458043048106467;
   fWeightMatrix0to1[12][0] = 42.7725828309021;
   fWeightMatrix0to1[13][0] = 0.964700261945551;
   fWeightMatrix0to1[14][0] = -22.6868328359436;
   fWeightMatrix0to1[15][0] = 1.18997185079879;
   fWeightMatrix0to1[16][0] = 18.8362032998604;
   fWeightMatrix0to1[17][0] = -20.8537336407374;
   fWeightMatrix0to1[18][0] = 10.3258139040144;
   fWeightMatrix0to1[19][0] = -83.049785896746;
   fWeightMatrix0to1[0][1] = -9.65476605312383;
   fWeightMatrix0to1[1][1] = -45.1715581000309;
   fWeightMatrix0to1[2][1] = -17.3837101482416;
   fWeightMatrix0to1[3][1] = 1.32073431505642;
   fWeightMatrix0to1[4][1] = 21.2439408992259;
   fWeightMatrix0to1[5][1] = -11.2815448805824;
   fWeightMatrix0to1[6][1] = 4.52945993116182;
   fWeightMatrix0to1[7][1] = -14.4930109394615;
   fWeightMatrix0to1[8][1] = 1.27040750362958;
   fWeightMatrix0to1[9][1] = 0.802803115855653;
   fWeightMatrix0to1[10][1] = 30.9056007541929;
   fWeightMatrix0to1[11][1] = 2.22203485971705;
   fWeightMatrix0to1[12][1] = -19.4872806103401;
   fWeightMatrix0to1[13][1] = 1.39515641894658;
   fWeightMatrix0to1[14][1] = -10.0359721956199;
   fWeightMatrix0to1[15][1] = 0.177829933616961;
   fWeightMatrix0to1[16][1] = 7.29693724158866;
   fWeightMatrix0to1[17][1] = -4.34477696569585;
   fWeightMatrix0to1[18][1] = -3.8991046750174;
   fWeightMatrix0to1[19][1] = 53.1762793233931;
   fWeightMatrix0to1[0][2] = 6.27005360071052;
   fWeightMatrix0to1[1][2] = 8.21809667292273;
   fWeightMatrix0to1[2][2] = -9.53439692681325;
   fWeightMatrix0to1[3][2] = -2.9957068397593;
   fWeightMatrix0to1[4][2] = 4.97737924374517;
   fWeightMatrix0to1[5][2] = -35.0871014018617;
   fWeightMatrix0to1[6][2] = -1.91759391048766;
   fWeightMatrix0to1[7][2] = -7.01853619848573;
   fWeightMatrix0to1[8][2] = 30.3352954214999;
   fWeightMatrix0to1[9][2] = 9.78328169401732;
   fWeightMatrix0to1[10][2] = 29.2400276378219;
   fWeightMatrix0to1[11][2] = 2.00494127443464;
   fWeightMatrix0to1[12][2] = 5.91446007002514;
   fWeightMatrix0to1[13][2] = 0.72822963057664;
   fWeightMatrix0to1[14][2] = 9.03150690165216;
   fWeightMatrix0to1[15][2] = 12.7117049522878;
   fWeightMatrix0to1[16][2] = -22.2779448943691;
   fWeightMatrix0to1[17][2] = 6.36145976795577;
   fWeightMatrix0to1[18][2] = -0.278194520726703;
   fWeightMatrix0to1[19][2] = 8.7050084632775;
   fWeightMatrix0to1[0][3] = 1.73018292323824;
   fWeightMatrix0to1[1][3] = 1.0867778449166;
   fWeightMatrix0to1[2][3] = 24.2501861759357;
   fWeightMatrix0to1[3][3] = -0.0640328965861764;
   fWeightMatrix0to1[4][3] = -7.30268898181189;
   fWeightMatrix0to1[5][3] = 15.2642532243383;
   fWeightMatrix0to1[6][3] = -3.44870242154456;
   fWeightMatrix0to1[7][3] = -3.20207308324584;
   fWeightMatrix0to1[8][3] = 24.5252816479674;
   fWeightMatrix0to1[9][3] = 1.05967447183957;
   fWeightMatrix0to1[10][3] = -23.3357137221977;
   fWeightMatrix0to1[11][3] = -0.780062186859183;
   fWeightMatrix0to1[12][3] = -4.57381037297586;
   fWeightMatrix0to1[13][3] = 0.549329446828431;
   fWeightMatrix0to1[14][3] = 1.88970823196503;
   fWeightMatrix0to1[15][3] = -3.03887187341208;
   fWeightMatrix0to1[16][3] = -3.4783792248098;
   fWeightMatrix0to1[17][3] = 3.39918273786959;
   fWeightMatrix0to1[18][3] = 3.42538619781576;
   fWeightMatrix0to1[19][3] = -12.8659483685105;
   fWeightMatrix0to1[0][4] = 4.45990285938676;
   fWeightMatrix0to1[1][4] = 1.42608397908042;
   fWeightMatrix0to1[2][4] = 4.88658372961775;
   fWeightMatrix0to1[3][4] = -1.85383749814863;
   fWeightMatrix0to1[4][4] = 7.4363984807392;
   fWeightMatrix0to1[5][4] = -6.41677447219375;
   fWeightMatrix0to1[6][4] = 0.0182129649280687;
   fWeightMatrix0to1[7][4] = 0.746749981959061;
   fWeightMatrix0to1[8][4] = -0.122702179909868;
   fWeightMatrix0to1[9][4] = -9.4511299292751;
   fWeightMatrix0to1[10][4] = 3.83463035355474;
   fWeightMatrix0to1[11][4] = 0.532239371723722;
   fWeightMatrix0to1[12][4] = -2.52888398553784;
   fWeightMatrix0to1[13][4] = -1.27100161545089;
   fWeightMatrix0to1[14][4] = -2.03231693933736;
   fWeightMatrix0to1[15][4] = 5.08366959973757;
   fWeightMatrix0to1[16][4] = 1.14218307381527;
   fWeightMatrix0to1[17][4] = -6.93706881845162;
   fWeightMatrix0to1[18][4] = -10.44945921565;
   fWeightMatrix0to1[19][4] = 4.60197911158898;
   fWeightMatrix0to1[0][5] = -3.10050001806012;
   fWeightMatrix0to1[1][5] = -2.02531687427505;
   fWeightMatrix0to1[2][5] = -2.89960843087613;
   fWeightMatrix0to1[3][5] = 0.60900816393729;
   fWeightMatrix0to1[4][5] = 3.37740908856491;
   fWeightMatrix0to1[5][5] = -11.0068561628109;
   fWeightMatrix0to1[6][5] = -1.88695168473453;
   fWeightMatrix0to1[7][5] = 4.20013887694133;
   fWeightMatrix0to1[8][5] = -3.74222388228714;
   fWeightMatrix0to1[9][5] = -3.93743628247499;
   fWeightMatrix0to1[10][5] = 2.76682149470501;
   fWeightMatrix0to1[11][5] = 0.845072334416853;
   fWeightMatrix0to1[12][5] = 3.12237954537418;
   fWeightMatrix0to1[13][5] = -0.876764142271536;
   fWeightMatrix0to1[14][5] = 1.70693818609932;
   fWeightMatrix0to1[15][5] = 4.81392223400734;
   fWeightMatrix0to1[16][5] = -4.54246449413955;
   fWeightMatrix0to1[17][5] = -2.31637662599426;
   fWeightMatrix0to1[18][5] = -0.166556249953363;
   fWeightMatrix0to1[19][5] = 4.03424534119122;
   fWeightMatrix0to1[0][6] = 0.272004697071641;
   fWeightMatrix0to1[1][6] = 3.38304763745713;
   fWeightMatrix0to1[2][6] = -3.18457348477865;
   fWeightMatrix0to1[3][6] = 0.196518220510555;
   fWeightMatrix0to1[4][6] = 4.00929059075326;
   fWeightMatrix0to1[5][6] = -13.6174168512536;
   fWeightMatrix0to1[6][6] = 0.111208213808575;
   fWeightMatrix0to1[7][6] = 4.32769103619781;
   fWeightMatrix0to1[8][6] = -7.93595151119324;
   fWeightMatrix0to1[9][6] = -4.37155892734998;
   fWeightMatrix0to1[10][6] = 4.89747803315225;
   fWeightMatrix0to1[11][6] = -1.84627808130055;
   fWeightMatrix0to1[12][6] = 4.04807290724938;
   fWeightMatrix0to1[13][6] = -1.48637289465516;
   fWeightMatrix0to1[14][6] = -6.19613828367494;
   fWeightMatrix0to1[15][6] = 2.61734353419916;
   fWeightMatrix0to1[16][6] = 5.78185400966974;
   fWeightMatrix0to1[17][6] = -12.7969012471968;
   fWeightMatrix0to1[18][6] = 0.0187047599597918;
   fWeightMatrix0to1[19][6] = 5.3230041685272;
   fWeightMatrix0to1[0][7] = 5.97007696548407;
   fWeightMatrix0to1[1][7] = -1.36322696534333;
   fWeightMatrix0to1[2][7] = 0.118970047253065;
   fWeightMatrix0to1[3][7] = -0.839463622524246;
   fWeightMatrix0to1[4][7] = -1.36512539269659;
   fWeightMatrix0to1[5][7] = -0.00744129430841174;
   fWeightMatrix0to1[6][7] = -0.145304085489873;
   fWeightMatrix0to1[7][7] = 1.25415306544309;
   fWeightMatrix0to1[8][7] = 1.05817503149414;
   fWeightMatrix0to1[9][7] = -0.514301631911095;
   fWeightMatrix0to1[10][7] = -0.154478900450733;
   fWeightMatrix0to1[11][7] = 0.944548506762402;
   fWeightMatrix0to1[12][7] = 7.23036873742529;
   fWeightMatrix0to1[13][7] = -1.2347366829415;
   fWeightMatrix0to1[14][7] = 1.53956739845089;
   fWeightMatrix0to1[15][7] = 0.58636580380915;
   fWeightMatrix0to1[16][7] = 1.48677389793827;
   fWeightMatrix0to1[17][7] = 2.11409138204107;
   fWeightMatrix0to1[18][7] = 1.44702400143133;
   fWeightMatrix0to1[19][7] = -0.546690166500398;
   fWeightMatrix0to1[0][8] = -0.244294896196976;
   fWeightMatrix0to1[1][8] = 2.06989246490616;
   fWeightMatrix0to1[2][8] = 0.167585370634779;
   fWeightMatrix0to1[3][8] = -0.918562992929744;
   fWeightMatrix0to1[4][8] = 2.3411833252537;
   fWeightMatrix0to1[5][8] = -1.78365123476736;
   fWeightMatrix0to1[6][8] = 2.20033898141004;
   fWeightMatrix0to1[7][8] = 2.69304386589144;
   fWeightMatrix0to1[8][8] = 0.972516651733785;
   fWeightMatrix0to1[9][8] = 0.610918536324088;
   fWeightMatrix0to1[10][8] = 1.63137958117354;
   fWeightMatrix0to1[11][8] = 1.46927758076979;
   fWeightMatrix0to1[12][8] = 1.75211438794646;
   fWeightMatrix0to1[13][8] = 0.565077344392772;
   fWeightMatrix0to1[14][8] = 17.8761668811606;
   fWeightMatrix0to1[15][8] = -8.25651760380236;
   fWeightMatrix0to1[16][8] = 3.24572202063578;
   fWeightMatrix0to1[17][8] = 6.49275976210643;
   fWeightMatrix0to1[18][8] = 0.283451100363138;
   fWeightMatrix0to1[19][8] = -2.77015168301825;
   fWeightMatrix0to1[0][9] = -3.36497544312417;
   fWeightMatrix0to1[1][9] = -0.987675787323954;
   fWeightMatrix0to1[2][9] = 0.539732297319798;
   fWeightMatrix0to1[3][9] = 0.0319349793956433;
   fWeightMatrix0to1[4][9] = 0.17686304504588;
   fWeightMatrix0to1[5][9] = -0.277215666833163;
   fWeightMatrix0to1[6][9] = -3.67893703158829;
   fWeightMatrix0to1[7][9] = 2.06889579598304;
   fWeightMatrix0to1[8][9] = 0.797879514275372;
   fWeightMatrix0to1[9][9] = 0.25878591811525;
   fWeightMatrix0to1[10][9] = -0.352143738119713;
   fWeightMatrix0to1[11][9] = 1.38579607833029;
   fWeightMatrix0to1[12][9] = 1.35749900660018;
   fWeightMatrix0to1[13][9] = 0.135702372370928;
   fWeightMatrix0to1[14][9] = 1.6620824192033;
   fWeightMatrix0to1[15][9] = 5.98028964836011;
   fWeightMatrix0to1[16][9] = -15.12800475215;
   fWeightMatrix0to1[17][9] = 8.39280888470569;
   fWeightMatrix0to1[18][9] = -0.190456594143866;
   fWeightMatrix0to1[19][9] = -1.05077195774221;
   fWeightMatrix0to1[0][10] = -0.11182421285884;
   fWeightMatrix0to1[1][10] = -0.0206142244128336;
   fWeightMatrix0to1[2][10] = -0.29186099219571;
   fWeightMatrix0to1[3][10] = 1.34286619574718;
   fWeightMatrix0to1[4][10] = 0.409574288438919;
   fWeightMatrix0to1[5][10] = 0.120502111340767;
   fWeightMatrix0to1[6][10] = -6.36438779808683;
   fWeightMatrix0to1[7][10] = -0.0370272629251272;
   fWeightMatrix0to1[8][10] = 0.187672224880385;
   fWeightMatrix0to1[9][10] = 0.204986717059273;
   fWeightMatrix0to1[10][10] = -0.246725338694268;
   fWeightMatrix0to1[11][10] = 0.254607388184311;
   fWeightMatrix0to1[12][10] = 0.302165509244456;
   fWeightMatrix0to1[13][10] = 1.43013429344828;
   fWeightMatrix0to1[14][10] = 4.92939866626777;
   fWeightMatrix0to1[15][10] = 0.245225455086809;
   fWeightMatrix0to1[16][10] = -0.115918200572794;
   fWeightMatrix0to1[17][10] = 0.527543454265883;
   fWeightMatrix0to1[18][10] = 0.0295776546995903;
   fWeightMatrix0to1[19][10] = -0.0566128276793057;
   fWeightMatrix0to1[0][11] = -2.02368529125031;
   fWeightMatrix0to1[1][11] = -3.19759526812699;
   fWeightMatrix0to1[2][11] = -2.94887374161946;
   fWeightMatrix0to1[3][11] = -1.55719386918375;
   fWeightMatrix0to1[4][11] = 5.97553141871645;
   fWeightMatrix0to1[5][11] = -10.4161851048326;
   fWeightMatrix0to1[6][11] = 3.73616527881466;
   fWeightMatrix0to1[7][11] = 3.6153628810282;
   fWeightMatrix0to1[8][11] = -5.09027984522028;
   fWeightMatrix0to1[9][11] = -5.56455766099444;
   fWeightMatrix0to1[10][11] = 3.13968420154601;
   fWeightMatrix0to1[11][11] = 0.459103504159133;
   fWeightMatrix0to1[12][11] = 1.25551571650292;
   fWeightMatrix0to1[13][11] = -1.62644072058809;
   fWeightMatrix0to1[14][11] = 3.24039851872888;
   fWeightMatrix0to1[15][11] = -5.64630773505488;
   fWeightMatrix0to1[16][11] = 7.54278538167826;
   fWeightMatrix0to1[17][11] = -6.46304860703024;
   fWeightMatrix0to1[18][11] = -1.83773465167379;
   fWeightMatrix0to1[19][11] = 5.75039995208032;
   fWeightMatrix0to1[0][12] = -1.60163868464707;
   fWeightMatrix0to1[1][12] = 0.10496950851237;
   fWeightMatrix0to1[2][12] = -5.96391308108839;
   fWeightMatrix0to1[3][12] = -1.85345887140913;
   fWeightMatrix0to1[4][12] = 2.18041637394408;
   fWeightMatrix0to1[5][12] = -14.37949651753;
   fWeightMatrix0to1[6][12] = -3.85527090776202;
   fWeightMatrix0to1[7][12] = 3.17698972977898;
   fWeightMatrix0to1[8][12] = -4.35546207223038;
   fWeightMatrix0to1[9][12] = -6.45206299790014;
   fWeightMatrix0to1[10][12] = 5.73946410995121;
   fWeightMatrix0to1[11][12] = -0.79092329231113;
   fWeightMatrix0to1[12][12] = 3.03096693597734;
   fWeightMatrix0to1[13][12] = 1.04409557626727;
   fWeightMatrix0to1[14][12] = -5.33915625363248;
   fWeightMatrix0to1[15][12] = 6.49947582116569;
   fWeightMatrix0to1[16][12] = -8.10994609880236;
   fWeightMatrix0to1[17][12] = -7.37506430476985;
   fWeightMatrix0to1[18][12] = -1.80624511315586;
   fWeightMatrix0to1[19][12] = 3.79514433803191;
   fWeightMatrix0to1[0][13] = 1.63381647538981;
   fWeightMatrix0to1[1][13] = -0.00491811087772633;
   fWeightMatrix0to1[2][13] = 0.375579124819479;
   fWeightMatrix0to1[3][13] = 0.613071785271904;
   fWeightMatrix0to1[4][13] = -2.06164379681883;
   fWeightMatrix0to1[5][13] = -0.372170147936787;
   fWeightMatrix0to1[6][13] = -0.161734134261962;
   fWeightMatrix0to1[7][13] = -1.05027465124385;
   fWeightMatrix0to1[8][13] = -0.486443159137123;
   fWeightMatrix0to1[9][13] = -0.665540217398727;
   fWeightMatrix0to1[10][13] = 0.330673591851716;
   fWeightMatrix0to1[11][13] = 0.888332481244105;
   fWeightMatrix0to1[12][13] = 0.473754021364276;
   fWeightMatrix0to1[13][13] = 0.732589770180934;
   fWeightMatrix0to1[14][13] = 1.83283949270417;
   fWeightMatrix0to1[15][13] = -4.05469176064987;
   fWeightMatrix0to1[16][13] = -3.38670994870752;
   fWeightMatrix0to1[17][13] = -1.72713068169349;
   fWeightMatrix0to1[18][13] = -0.145929359874994;
   fWeightMatrix0to1[19][13] = -0.0205116226843518;
   fWeightMatrix0to1[0][14] = -0.0307451893565154;
   fWeightMatrix0to1[1][14] = -0.00407666285137991;
   fWeightMatrix0to1[2][14] = 0.00368625520653822;
   fWeightMatrix0to1[3][14] = -0.887604662446488;
   fWeightMatrix0to1[4][14] = 0.0179681425266142;
   fWeightMatrix0to1[5][14] = 0.00328651051372486;
   fWeightMatrix0to1[6][14] = 0.00544018848919279;
   fWeightMatrix0to1[7][14] = 0.00507551093785919;
   fWeightMatrix0to1[8][14] = 0.00282702782954756;
   fWeightMatrix0to1[9][14] = 0.000498040573822054;
   fWeightMatrix0to1[10][14] = -0.00506767959386091;
   fWeightMatrix0to1[11][14] = 0.387886307165264;
   fWeightMatrix0to1[12][14] = -0.00348573616968857;
   fWeightMatrix0to1[13][14] = 0.678673594659584;
   fWeightMatrix0to1[14][14] = 0.00800234436041982;
   fWeightMatrix0to1[15][14] = 0.0106156065022591;
   fWeightMatrix0to1[16][14] = 0.0158673923281611;
   fWeightMatrix0to1[17][14] = 0.0194590637864455;
   fWeightMatrix0to1[18][14] = -0.00706094044078249;
   fWeightMatrix0to1[19][14] = -0.00659761799609782;
   fWeightMatrix0to1[0][15] = -3.2384720764299;
   fWeightMatrix0to1[1][15] = -1.53648049331263;
   fWeightMatrix0to1[2][15] = 1.20361837168422;
   fWeightMatrix0to1[3][15] = -0.614366382879567;
   fWeightMatrix0to1[4][15] = 0.585978882424688;
   fWeightMatrix0to1[5][15] = 0.785494597825078;
   fWeightMatrix0to1[6][15] = -2.24262221379169;
   fWeightMatrix0to1[7][15] = -0.391012844474823;
   fWeightMatrix0to1[8][15] = 0.597374591226469;
   fWeightMatrix0to1[9][15] = 0.506078840461636;
   fWeightMatrix0to1[10][15] = 0.559375419551686;
   fWeightMatrix0to1[11][15] = -0.814881110199662;
   fWeightMatrix0to1[12][15] = -1.7752745953196;
   fWeightMatrix0to1[13][15] = -1.81173285520792;
   fWeightMatrix0to1[14][15] = 9.99423416538298;
   fWeightMatrix0to1[15][15] = -0.181907920875151;
   fWeightMatrix0to1[16][15] = 4.73046624630582;
   fWeightMatrix0to1[17][15] = 5.01557145466546;
   fWeightMatrix0to1[18][15] = 0.561188297550759;
   fWeightMatrix0to1[19][15] = 0.372794848526886;
   fWeightMatrix0to1[0][16] = -2.65601575324009;
   fWeightMatrix0to1[1][16] = -1.05879224428397;
   fWeightMatrix0to1[2][16] = -0.960086579700913;
   fWeightMatrix0to1[3][16] = -0.478409587830897;
   fWeightMatrix0to1[4][16] = 1.57444274763488;
   fWeightMatrix0to1[5][16] = -0.568663235242992;
   fWeightMatrix0to1[6][16] = 0.387435075549711;
   fWeightMatrix0to1[7][16] = 1.90368857339051;
   fWeightMatrix0to1[8][16] = -0.439916769077992;
   fWeightMatrix0to1[9][16] = 0.764858799965954;
   fWeightMatrix0to1[10][16] = -0.663459555365634;
   fWeightMatrix0to1[11][16] = 0.754323987167432;
   fWeightMatrix0to1[12][16] = 0.229865741013504;
   fWeightMatrix0to1[13][16] = -0.0682432099569611;
   fWeightMatrix0to1[14][16] = 3.84618210170302;
   fWeightMatrix0to1[15][16] = 3.1204099338926;
   fWeightMatrix0to1[16][16] = -13.5961449973049;
   fWeightMatrix0to1[17][16] = 6.49984481758268;
   fWeightMatrix0to1[18][16] = 0.254102681168863;
   fWeightMatrix0to1[19][16] = -0.129852672262159;
   fWeightMatrix0to1[0][17] = 0.037395097142361;
   fWeightMatrix0to1[1][17] = -0.0020946357472943;
   fWeightMatrix0to1[2][17] = 0.000912497751878058;
   fWeightMatrix0to1[3][17] = -6.56153868934657;
   fWeightMatrix0to1[4][17] = 0.00260008766586575;
   fWeightMatrix0to1[5][17] = -0.000159974392160889;
   fWeightMatrix0to1[6][17] = -0.0158692965509378;
   fWeightMatrix0to1[7][17] = 0.00731571448081616;
   fWeightMatrix0to1[8][17] = -0.00105549606441026;
   fWeightMatrix0to1[9][17] = 0.00203616268604189;
   fWeightMatrix0to1[10][17] = -0.0267906535493079;
   fWeightMatrix0to1[11][17] = 0.71973800887293;
   fWeightMatrix0to1[12][17] = -0.0425850090650839;
   fWeightMatrix0to1[13][17] = 5.90437479286301;
   fWeightMatrix0to1[14][17] = 0.0208521554748543;
   fWeightMatrix0to1[15][17] = 0.0446096319734313;
   fWeightMatrix0to1[16][17] = -0.0208353829452729;
   fWeightMatrix0to1[17][17] = 0.0451369572327191;
   fWeightMatrix0to1[18][17] = 0.00552768575984585;
   fWeightMatrix0to1[19][17] = -0.0273257174105284;
   fWeightMatrix0to1[0][18] = 0.716744083102644;
   fWeightMatrix0to1[1][18] = -1.74965309618648;
   fWeightMatrix0to1[2][18] = -4.12089965100271;
   fWeightMatrix0to1[3][18] = -3.32595538016173;
   fWeightMatrix0to1[4][18] = 4.76234247943753;
   fWeightMatrix0to1[5][18] = -12.3948689662898;
   fWeightMatrix0to1[6][18] = -1.91983474296921;
   fWeightMatrix0to1[7][18] = 4.3472184344525;
   fWeightMatrix0to1[8][18] = -5.63662365365566;
   fWeightMatrix0to1[9][18] = -5.82497583930808;
   fWeightMatrix0to1[10][18] = 4.89098807556913;
   fWeightMatrix0to1[11][18] = -0.957172452923232;
   fWeightMatrix0to1[12][18] = 0.0889228452149352;
   fWeightMatrix0to1[13][18] = -1.1801217762609;
   fWeightMatrix0to1[14][18] = 0.441822019965204;
   fWeightMatrix0to1[15][18] = 1.80487199992309;
   fWeightMatrix0to1[16][18] = 7.10378873175948;
   fWeightMatrix0to1[17][18] = -4.77904393740444;
   fWeightMatrix0to1[18][18] = 0.717251211001022;
   fWeightMatrix0to1[19][18] = 5.69414007849052;
   fWeightMatrix0to1[0][19] = -1.61938853450238;
   fWeightMatrix0to1[1][19] = -3.55617156737911;
   fWeightMatrix0to1[2][19] = -3.84846744730115;
   fWeightMatrix0to1[3][19] = 0.170692762343572;
   fWeightMatrix0to1[4][19] = 4.78782553656958;
   fWeightMatrix0to1[5][19] = -10.1212124438663;
   fWeightMatrix0to1[6][19] = 1.11312607630917;
   fWeightMatrix0to1[7][19] = 3.74970213881498;
   fWeightMatrix0to1[8][19] = -1.99143659034308;
   fWeightMatrix0to1[9][19] = -6.34678874767376;
   fWeightMatrix0to1[10][19] = 4.98683479618164;
   fWeightMatrix0to1[11][19] = 0.945700826653813;
   fWeightMatrix0to1[12][19] = -0.81082910849077;
   fWeightMatrix0to1[13][19] = 1.3359212951951;
   fWeightMatrix0to1[14][19] = -6.16126013208646;
   fWeightMatrix0to1[15][19] = 3.12705086267165;
   fWeightMatrix0to1[16][19] = -6.8892350689286;
   fWeightMatrix0to1[17][19] = -4.42206494899819;
   fWeightMatrix0to1[18][19] = 1.58993350860267;
   fWeightMatrix0to1[19][19] = 6.10257133460142;
   fWeightMatrix0to1[0][20] = 12.5408248208653;
   fWeightMatrix0to1[1][20] = 47.3216118423597;
   fWeightMatrix0to1[2][20] = -13.834851224497;
   fWeightMatrix0to1[3][20] = -5.105546692949;
   fWeightMatrix0to1[4][20] = 7.62148379738101;
   fWeightMatrix0to1[5][20] = -56.9080165529285;
   fWeightMatrix0to1[6][20] = -1.27117526627842;
   fWeightMatrix0to1[7][20] = 18.3278399558279;
   fWeightMatrix0to1[8][20] = -20.189320972378;
   fWeightMatrix0to1[9][20] = -12.002361342081;
   fWeightMatrix0to1[10][20] = 23.6558330077815;
   fWeightMatrix0to1[11][20] = -2.0817032710728;
   fWeightMatrix0to1[12][20] = 31.9092419731881;
   fWeightMatrix0to1[13][20] = -3.43735983033474;
   fWeightMatrix0to1[14][20] = 7.25060062694345;
   fWeightMatrix0to1[15][20] = 7.05570209215743;
   fWeightMatrix0to1[16][20] = 4.9021455783097;
   fWeightMatrix0to1[17][20] = -18.796726218348;
   fWeightMatrix0to1[18][20] = 0.295126927204679;
   fWeightMatrix0to1[19][20] = -14.898679604978;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.879627821103933;
   fWeightMatrix1to2[1][0] = -1.20096068873813;
   fWeightMatrix1to2[2][0] = -0.00259049853719847;
   fWeightMatrix1to2[3][0] = -3.08407775082135;
   fWeightMatrix1to2[4][0] = -2.95970475469183;
   fWeightMatrix1to2[5][0] = 0.530315621053135;
   fWeightMatrix1to2[6][0] = 0.953784624244236;
   fWeightMatrix1to2[7][0] = -0.841575515781494;
   fWeightMatrix1to2[8][0] = 0.776046879112591;
   fWeightMatrix1to2[9][0] = -0.252130938348629;
   fWeightMatrix1to2[10][0] = 1.57941270987886;
   fWeightMatrix1to2[11][0] = 2.73316476220932;
   fWeightMatrix1to2[12][0] = -1.31438908002515;
   fWeightMatrix1to2[13][0] = -3.51372777914528;
   fWeightMatrix1to2[14][0] = 0.0514609185604535;
   fWeightMatrix1to2[15][0] = 0.349318871088023;
   fWeightMatrix1to2[16][0] = -0.905151567846975;
   fWeightMatrix1to2[17][0] = 4.22059794255019;
   fWeightMatrix1to2[18][0] = -1.32456358461313;
   fWeightMatrix1to2[19][0] = 0.068218847229534;
   fWeightMatrix1to2[20][0] = -1.66269567187381;
   fWeightMatrix1to2[21][0] = -2.73479655721497;
   fWeightMatrix1to2[22][0] = 0.664838881158018;
   fWeightMatrix1to2[23][0] = -0.200436395409333;
   fWeightMatrix1to2[24][0] = -0.428591974333754;
   fWeightMatrix1to2[0][1] = 1.55031863834894;
   fWeightMatrix1to2[1][1] = 4.63833923069745;
   fWeightMatrix1to2[2][1] = -0.0171561745185408;
   fWeightMatrix1to2[3][1] = -2.75747184625756;
   fWeightMatrix1to2[4][1] = -1.34216710723374;
   fWeightMatrix1to2[5][1] = 4.09416335815536;
   fWeightMatrix1to2[6][1] = -1.85223442533473;
   fWeightMatrix1to2[7][1] = 1.41098361727461;
   fWeightMatrix1to2[8][1] = -0.346846311255303;
   fWeightMatrix1to2[9][1] = -2.84783008634913;
   fWeightMatrix1to2[10][1] = -1.78930766405639;
   fWeightMatrix1to2[11][1] = 1.18915330793907;
   fWeightMatrix1to2[12][1] = -5.6519307078883;
   fWeightMatrix1to2[13][1] = -2.09541701091823;
   fWeightMatrix1to2[14][1] = 3.25582330742207;
   fWeightMatrix1to2[15][1] = -5.0401357380835;
   fWeightMatrix1to2[16][1] = 1.70901581474119;
   fWeightMatrix1to2[17][1] = -0.949651349622449;
   fWeightMatrix1to2[18][1] = -5.98827339097706;
   fWeightMatrix1to2[19][1] = 0.288584544162761;
   fWeightMatrix1to2[20][1] = -1.96200198893341;
   fWeightMatrix1to2[21][1] = -1.88101650202869;
   fWeightMatrix1to2[22][1] = -9.07968554515714;
   fWeightMatrix1to2[23][1] = 5.27150109158694;
   fWeightMatrix1to2[24][1] = 0.30304063699547;
   fWeightMatrix1to2[0][2] = 3.09069825803783;
   fWeightMatrix1to2[1][2] = 5.31257125811734;
   fWeightMatrix1to2[2][2] = 0.369417475109267;
   fWeightMatrix1to2[3][2] = 3.59284918623841;
   fWeightMatrix1to2[4][2] = -0.0427662593952426;
   fWeightMatrix1to2[5][2] = -0.508138496131334;
   fWeightMatrix1to2[6][2] = 1.20814254159768;
   fWeightMatrix1to2[7][2] = -2.14605082749246;
   fWeightMatrix1to2[8][2] = 2.01831794455429;
   fWeightMatrix1to2[9][2] = 0.560823968096579;
   fWeightMatrix1to2[10][2] = -2.10096117719209;
   fWeightMatrix1to2[11][2] = -1.23316891589789;
   fWeightMatrix1to2[12][2] = -1.92857816230818;
   fWeightMatrix1to2[13][2] = 2.74677841412052;
   fWeightMatrix1to2[14][2] = -3.9222514255625;
   fWeightMatrix1to2[15][2] = 0.115245569586869;
   fWeightMatrix1to2[16][2] = 1.84096878028929;
   fWeightMatrix1to2[17][2] = -1.58959299316541;
   fWeightMatrix1to2[18][2] = 0.204914975661737;
   fWeightMatrix1to2[19][2] = -0.316851876581723;
   fWeightMatrix1to2[20][2] = -0.750454236674609;
   fWeightMatrix1to2[21][2] = -6.56307596885023;
   fWeightMatrix1to2[22][2] = -1.93533390148651;
   fWeightMatrix1to2[23][2] = 4.32914469866806;
   fWeightMatrix1to2[24][2] = -0.461573546397592;
   fWeightMatrix1to2[0][3] = -0.14755870388752;
   fWeightMatrix1to2[1][3] = 0.140139857859627;
   fWeightMatrix1to2[2][3] = -0.0729574214972324;
   fWeightMatrix1to2[3][3] = -0.119906644914229;
   fWeightMatrix1to2[4][3] = -0.13161093231214;
   fWeightMatrix1to2[5][3] = 0.324220986912957;
   fWeightMatrix1to2[6][3] = -0.339584271591179;
   fWeightMatrix1to2[7][3] = 0.0294416421629764;
   fWeightMatrix1to2[8][3] = 0.404240357557825;
   fWeightMatrix1to2[9][3] = 2.23005770812659;
   fWeightMatrix1to2[10][3] = 0.234127187371858;
   fWeightMatrix1to2[11][3] = 0.152352775982632;
   fWeightMatrix1to2[12][3] = -0.0658719178116923;
   fWeightMatrix1to2[13][3] = -1.56518552157494;
   fWeightMatrix1to2[14][3] = -0.637737934250401;
   fWeightMatrix1to2[15][3] = 4.52336349221115;
   fWeightMatrix1to2[16][3] = -0.806109576493222;
   fWeightMatrix1to2[17][3] = 0.836537752046778;
   fWeightMatrix1to2[18][3] = -0.2645749066212;
   fWeightMatrix1to2[19][3] = -0.184661105373407;
   fWeightMatrix1to2[20][3] = 0.304871058291403;
   fWeightMatrix1to2[21][3] = 0.845260914588748;
   fWeightMatrix1to2[22][3] = 0.902095613618158;
   fWeightMatrix1to2[23][3] = 0.29958401884279;
   fWeightMatrix1to2[24][3] = -2.19337991189331;
   fWeightMatrix1to2[0][4] = 0.55946022897229;
   fWeightMatrix1to2[1][4] = -1.40599889631023;
   fWeightMatrix1to2[2][4] = 1.32628260130121;
   fWeightMatrix1to2[3][4] = -4.52603084018569;
   fWeightMatrix1to2[4][4] = 0.697995008268649;
   fWeightMatrix1to2[5][4] = -0.0621582556213508;
   fWeightMatrix1to2[6][4] = 1.03928003246277;
   fWeightMatrix1to2[7][4] = 3.123049990557;
   fWeightMatrix1to2[8][4] = 0.124183591945373;
   fWeightMatrix1to2[9][4] = -0.802368166780999;
   fWeightMatrix1to2[10][4] = -3.21856345919382;
   fWeightMatrix1to2[11][4] = -3.85559375114096;
   fWeightMatrix1to2[12][4] = 1.42660368155168;
   fWeightMatrix1to2[13][4] = -1.85894499145564;
   fWeightMatrix1to2[14][4] = -0.449135531584791;
   fWeightMatrix1to2[15][4] = -0.441436868479849;
   fWeightMatrix1to2[16][4] = 1.94581007865243;
   fWeightMatrix1to2[17][4] = 1.42325455961118;
   fWeightMatrix1to2[18][4] = 1.00865226203396;
   fWeightMatrix1to2[19][4] = -3.59233733868537;
   fWeightMatrix1to2[20][4] = 2.10632606518373;
   fWeightMatrix1to2[21][4] = -0.380375676356857;
   fWeightMatrix1to2[22][4] = 2.34911166527927;
   fWeightMatrix1to2[23][4] = -4.66523420537699;
   fWeightMatrix1to2[24][4] = 0.720280008085808;
   fWeightMatrix1to2[0][5] = -8.94961871136592;
   fWeightMatrix1to2[1][5] = 4.8370988794538;
   fWeightMatrix1to2[2][5] = -2.93344902759269;
   fWeightMatrix1to2[3][5] = 4.4793789689689;
   fWeightMatrix1to2[4][5] = -10.2399284240621;
   fWeightMatrix1to2[5][5] = -8.79292819887188;
   fWeightMatrix1to2[6][5] = -4.94112258390486;
   fWeightMatrix1to2[7][5] = -2.0389151988387;
   fWeightMatrix1to2[8][5] = 2.51902637259838;
   fWeightMatrix1to2[9][5] = 0.0355050468125895;
   fWeightMatrix1to2[10][5] = -3.64504657127684;
   fWeightMatrix1to2[11][5] = 0.502774143788474;
   fWeightMatrix1to2[12][5] = -4.59763377473394;
   fWeightMatrix1to2[13][5] = 2.88542792642513;
   fWeightMatrix1to2[14][5] = -10.4621875809708;
   fWeightMatrix1to2[15][5] = -0.0219751771758072;
   fWeightMatrix1to2[16][5] = -0.5485597211447;
   fWeightMatrix1to2[17][5] = 0.841762142621825;
   fWeightMatrix1to2[18][5] = 1.52218494914602;
   fWeightMatrix1to2[19][5] = -0.60176581834827;
   fWeightMatrix1to2[20][5] = 1.28920841738629;
   fWeightMatrix1to2[21][5] = -1.48631011935676;
   fWeightMatrix1to2[22][5] = -0.0198815365303929;
   fWeightMatrix1to2[23][5] = -0.34484448540845;
   fWeightMatrix1to2[24][5] = -8.56821451643076;
   fWeightMatrix1to2[0][6] = 0.177769002379113;
   fWeightMatrix1to2[1][6] = 0.0287626941541619;
   fWeightMatrix1to2[2][6] = -0.152005161210002;
   fWeightMatrix1to2[3][6] = 0.617776615155252;
   fWeightMatrix1to2[4][6] = 0.236547179329888;
   fWeightMatrix1to2[5][6] = -0.135212741058371;
   fWeightMatrix1to2[6][6] = -2.00613571122056;
   fWeightMatrix1to2[7][6] = -4.84116995955091;
   fWeightMatrix1to2[8][6] = 0.63784774820095;
   fWeightMatrix1to2[9][6] = 0.694872354171903;
   fWeightMatrix1to2[10][6] = -3.54291608899015;
   fWeightMatrix1to2[11][6] = -1.91545425975803;
   fWeightMatrix1to2[12][6] = 0.172500751403657;
   fWeightMatrix1to2[13][6] = -1.64473652600342;
   fWeightMatrix1to2[14][6] = 0.0194233108418179;
   fWeightMatrix1to2[15][6] = -0.602840166394305;
   fWeightMatrix1to2[16][6] = 4.59863918406028;
   fWeightMatrix1to2[17][6] = 4.73177882862007;
   fWeightMatrix1to2[18][6] = 0.364290416552493;
   fWeightMatrix1to2[19][6] = 4.80961251547283;
   fWeightMatrix1to2[20][6] = -1.3595816938624;
   fWeightMatrix1to2[21][6] = -0.0873505609021451;
   fWeightMatrix1to2[22][6] = 0.404511119365804;
   fWeightMatrix1to2[23][6] = 0.0420897194519699;
   fWeightMatrix1to2[24][6] = -0.0856159207050311;
   fWeightMatrix1to2[0][7] = -4.18800236140331;
   fWeightMatrix1to2[1][7] = 3.55395410717065;
   fWeightMatrix1to2[2][7] = -2.2116847587206;
   fWeightMatrix1to2[3][7] = 1.89706213914979;
   fWeightMatrix1to2[4][7] = -1.81760346249372;
   fWeightMatrix1to2[5][7] = 1.07318525723592;
   fWeightMatrix1to2[6][7] = 2.52607628940693;
   fWeightMatrix1to2[7][7] = 1.17884038954089;
   fWeightMatrix1to2[8][7] = 0.26403353670757;
   fWeightMatrix1to2[9][7] = -5.33869954819781;
   fWeightMatrix1to2[10][7] = 0.744685365057061;
   fWeightMatrix1to2[11][7] = -1.36769889906402;
   fWeightMatrix1to2[12][7] = -3.44424694388008;
   fWeightMatrix1to2[13][7] = -3.0599247566952;
   fWeightMatrix1to2[14][7] = 3.58441664194466;
   fWeightMatrix1to2[15][7] = 0.0873047121843483;
   fWeightMatrix1to2[16][7] = 0.462955419346724;
   fWeightMatrix1to2[17][7] = 3.21960595376204;
   fWeightMatrix1to2[18][7] = -4.79426456538112;
   fWeightMatrix1to2[19][7] = -2.00086095448713;
   fWeightMatrix1to2[20][7] = -2.69757624217723;
   fWeightMatrix1to2[21][7] = 1.30111146534528;
   fWeightMatrix1to2[22][7] = -0.178739016938873;
   fWeightMatrix1to2[23][7] = 3.54174050857807;
   fWeightMatrix1to2[24][7] = -1.82017717046498;
   fWeightMatrix1to2[0][8] = 10.5047057756131;
   fWeightMatrix1to2[1][8] = -3.03874221608995;
   fWeightMatrix1to2[2][8] = 1.50143285019391;
   fWeightMatrix1to2[3][8] = -2.97144303255551;
   fWeightMatrix1to2[4][8] = 0.30380125241776;
   fWeightMatrix1to2[5][8] = -0.436541929783553;
   fWeightMatrix1to2[6][8] = -0.796062453085293;
   fWeightMatrix1to2[7][8] = 0.697192766745226;
   fWeightMatrix1to2[8][8] = -3.35065900188638;
   fWeightMatrix1to2[9][8] = -0.85242266504368;
   fWeightMatrix1to2[10][8] = 2.0864760125971;
   fWeightMatrix1to2[11][8] = 0.228542290754047;
   fWeightMatrix1to2[12][8] = 2.06528662511023;
   fWeightMatrix1to2[13][8] = -1.43375781624952;
   fWeightMatrix1to2[14][8] = 2.35206344647322;
   fWeightMatrix1to2[15][8] = -0.195820100756297;
   fWeightMatrix1to2[16][8] = 1.52445500876654;
   fWeightMatrix1to2[17][8] = 0.905804897907814;
   fWeightMatrix1to2[18][8] = 0.845970873528433;
   fWeightMatrix1to2[19][8] = 0.691786999960947;
   fWeightMatrix1to2[20][8] = -0.575135377705373;
   fWeightMatrix1to2[21][8] = -0.0497244673939463;
   fWeightMatrix1to2[22][8] = 0.380861806542847;
   fWeightMatrix1to2[23][8] = -0.212370625525256;
   fWeightMatrix1to2[24][8] = -0.208639656267444;
   fWeightMatrix1to2[0][9] = -3.13152488016792;
   fWeightMatrix1to2[1][9] = 1.77366705556191;
   fWeightMatrix1to2[2][9] = 0.0952094531390353;
   fWeightMatrix1to2[3][9] = -2.40448490614433;
   fWeightMatrix1to2[4][9] = -5.23823626030562;
   fWeightMatrix1to2[5][9] = -4.54423330202104;
   fWeightMatrix1to2[6][9] = -5.69056963742639;
   fWeightMatrix1to2[7][9] = -1.05510012517313;
   fWeightMatrix1to2[8][9] = -2.1667510288526;
   fWeightMatrix1to2[9][9] = 2.2791600144162;
   fWeightMatrix1to2[10][9] = -1.16922459041715;
   fWeightMatrix1to2[11][9] = -2.28510699011269;
   fWeightMatrix1to2[12][9] = -4.2866736218898;
   fWeightMatrix1to2[13][9] = 2.87686664216666;
   fWeightMatrix1to2[14][9] = -1.60933287146729;
   fWeightMatrix1to2[15][9] = -1.19562901516073;
   fWeightMatrix1to2[16][9] = 1.01924129719176;
   fWeightMatrix1to2[17][9] = 3.96200353434351;
   fWeightMatrix1to2[18][9] = 0.378306625099273;
   fWeightMatrix1to2[19][9] = -0.218360881201549;
   fWeightMatrix1to2[20][9] = -3.08686720778055;
   fWeightMatrix1to2[21][9] = -1.88823467436946;
   fWeightMatrix1to2[22][9] = -0.35701765277344;
   fWeightMatrix1to2[23][9] = 2.51441451063205;
   fWeightMatrix1to2[24][9] = 0.631358247978659;
   fWeightMatrix1to2[0][10] = -2.89825875006699;
   fWeightMatrix1to2[1][10] = -1.8663851083891;
   fWeightMatrix1to2[2][10] = -10.5026452975318;
   fWeightMatrix1to2[3][10] = -6.60502879926138;
   fWeightMatrix1to2[4][10] = -0.154687132754133;
   fWeightMatrix1to2[5][10] = 1.81296900963579;
   fWeightMatrix1to2[6][10] = -1.13887126248673;
   fWeightMatrix1to2[7][10] = 1.35668428428284;
   fWeightMatrix1to2[8][10] = -1.90060764916505;
   fWeightMatrix1to2[9][10] = -0.0629063245596433;
   fWeightMatrix1to2[10][10] = 1.95509298245536;
   fWeightMatrix1to2[11][10] = 1.86661889726901;
   fWeightMatrix1to2[12][10] = 3.08531784498955;
   fWeightMatrix1to2[13][10] = -0.536507342625102;
   fWeightMatrix1to2[14][10] = 2.92773759242593;
   fWeightMatrix1to2[15][10] = -2.05988236083621;
   fWeightMatrix1to2[16][10] = 0.947034087508317;
   fWeightMatrix1to2[17][10] = -2.05187828330736;
   fWeightMatrix1to2[18][10] = -0.578373934945462;
   fWeightMatrix1to2[19][10] = 0.430819717538149;
   fWeightMatrix1to2[20][10] = 0.248010866985453;
   fWeightMatrix1to2[21][10] = 0.49513903400463;
   fWeightMatrix1to2[22][10] = 0.888620851557657;
   fWeightMatrix1to2[23][10] = -0.518778454910094;
   fWeightMatrix1to2[24][10] = -0.0294570508183026;
   fWeightMatrix1to2[0][11] = -0.528798565520591;
   fWeightMatrix1to2[1][11] = 1.08664328538404;
   fWeightMatrix1to2[2][11] = 0.823104963989957;
   fWeightMatrix1to2[3][11] = -1.77347954114015;
   fWeightMatrix1to2[4][11] = 0.564600038498904;
   fWeightMatrix1to2[5][11] = 1.05069429981663;
   fWeightMatrix1to2[6][11] = 1.93259298354046;
   fWeightMatrix1to2[7][11] = 0.898724382058301;
   fWeightMatrix1to2[8][11] = -0.813048497971604;
   fWeightMatrix1to2[9][11] = -0.899577721915972;
   fWeightMatrix1to2[10][11] = -0.919675875126521;
   fWeightMatrix1to2[11][11] = -0.835832086828428;
   fWeightMatrix1to2[12][11] = -0.808852706883355;
   fWeightMatrix1to2[13][11] = 0.487682987423473;
   fWeightMatrix1to2[14][11] = 0.917922311714768;
   fWeightMatrix1to2[15][11] = -0.66256869664179;
   fWeightMatrix1to2[16][11] = 1.23857184993601;
   fWeightMatrix1to2[17][11] = 1.37224729469235;
   fWeightMatrix1to2[18][11] = 0.152716572819884;
   fWeightMatrix1to2[19][11] = -0.305618934663801;
   fWeightMatrix1to2[20][11] = 0.514597571576865;
   fWeightMatrix1to2[21][11] = 1.01077937806886;
   fWeightMatrix1to2[22][11] = -1.51566931945485;
   fWeightMatrix1to2[23][11] = 1.79199818701887;
   fWeightMatrix1to2[24][11] = -0.182714262161341;
   fWeightMatrix1to2[0][12] = -0.419544488475505;
   fWeightMatrix1to2[1][12] = 1.84327562310957;
   fWeightMatrix1to2[2][12] = -0.49575015425868;
   fWeightMatrix1to2[3][12] = -0.0560037637673827;
   fWeightMatrix1to2[4][12] = 0.239960725802449;
   fWeightMatrix1to2[5][12] = 1.11862789501529;
   fWeightMatrix1to2[6][12] = -1.42911508314214;
   fWeightMatrix1to2[7][12] = -0.673173695227665;
   fWeightMatrix1to2[8][12] = -1.24466995797376;
   fWeightMatrix1to2[9][12] = -0.380212042823781;
   fWeightMatrix1to2[10][12] = 1.65006930609312;
   fWeightMatrix1to2[11][12] = 2.92290129086949;
   fWeightMatrix1to2[12][12] = -1.10005450696239;
   fWeightMatrix1to2[13][12] = 1.77329244924952;
   fWeightMatrix1to2[14][12] = -0.248002955262423;
   fWeightMatrix1to2[15][12] = 2.38153641575013;
   fWeightMatrix1to2[16][12] = -1.12334733356039;
   fWeightMatrix1to2[17][12] = 0.864017926992466;
   fWeightMatrix1to2[18][12] = -1.32324841206908;
   fWeightMatrix1to2[19][12] = 0.0662813455113981;
   fWeightMatrix1to2[20][12] = -0.129252964943462;
   fWeightMatrix1to2[21][12] = 1.6572463701481;
   fWeightMatrix1to2[22][12] = -4.38755012794319;
   fWeightMatrix1to2[23][12] = 1.23506525877774;
   fWeightMatrix1to2[24][12] = -2.44130451279789;
   fWeightMatrix1to2[0][13] = -0.105691324503517;
   fWeightMatrix1to2[1][13] = 0.0911758826859336;
   fWeightMatrix1to2[2][13] = -0.0886632797660348;
   fWeightMatrix1to2[3][13] = -0.0891466039902956;
   fWeightMatrix1to2[4][13] = -0.00532472664911904;
   fWeightMatrix1to2[5][13] = 0.293596022052273;
   fWeightMatrix1to2[6][13] = -0.482328473544036;
   fWeightMatrix1to2[7][13] = 0.0325490416775507;
   fWeightMatrix1to2[8][13] = 0.390738229230412;
   fWeightMatrix1to2[9][13] = 2.31636428550453;
   fWeightMatrix1to2[10][13] = 0.313013349878674;
   fWeightMatrix1to2[11][13] = 0.25952575463683;
   fWeightMatrix1to2[12][13] = 0.0195810835464958;
   fWeightMatrix1to2[13][13] = -1.48114894211673;
   fWeightMatrix1to2[14][13] = -0.595968402006303;
   fWeightMatrix1to2[15][13] = 4.75136274951044;
   fWeightMatrix1to2[16][13] = -0.788756154457256;
   fWeightMatrix1to2[17][13] = 0.880899402861223;
   fWeightMatrix1to2[18][13] = -0.267606758297133;
   fWeightMatrix1to2[19][13] = -0.18601086780434;
   fWeightMatrix1to2[20][13] = 0.328372205793473;
   fWeightMatrix1to2[21][13] = 0.957955653134651;
   fWeightMatrix1to2[22][13] = 0.821107269523357;
   fWeightMatrix1to2[23][13] = 0.292471368218825;
   fWeightMatrix1to2[24][13] = -2.08743419367454;
   fWeightMatrix1to2[0][14] = 0.339875368250723;
   fWeightMatrix1to2[1][14] = -0.236254604377224;
   fWeightMatrix1to2[2][14] = 0.280276972196573;
   fWeightMatrix1to2[3][14] = 1.60975207854169;
   fWeightMatrix1to2[4][14] = 0.498544989863115;
   fWeightMatrix1to2[5][14] = -0.343314091346394;
   fWeightMatrix1to2[6][14] = 1.85321164588197;
   fWeightMatrix1to2[7][14] = 3.76803944562481;
   fWeightMatrix1to2[8][14] = -0.360288146590473;
   fWeightMatrix1to2[9][14] = -0.58873646149628;
   fWeightMatrix1to2[10][14] = -0.562682694947916;
   fWeightMatrix1to2[11][14] = -0.975360232616441;
   fWeightMatrix1to2[12][14] = -0.0854662036790789;
   fWeightMatrix1to2[13][14] = 0.0256906887300401;
   fWeightMatrix1to2[14][14] = 1.17995333516635;
   fWeightMatrix1to2[15][14] = -6.84854885429732;
   fWeightMatrix1to2[16][14] = -1.11204926174929;
   fWeightMatrix1to2[17][14] = -6.8455051623425;
   fWeightMatrix1to2[18][14] = -0.334894989867295;
   fWeightMatrix1to2[19][14] = -13.2513471140656;
   fWeightMatrix1to2[20][14] = -0.329896187541612;
   fWeightMatrix1to2[21][14] = -0.196693080721073;
   fWeightMatrix1to2[22][14] = -0.212525454638196;
   fWeightMatrix1to2[23][14] = -0.400193743627188;
   fWeightMatrix1to2[24][14] = 0.476350777567126;
   fWeightMatrix1to2[0][15] = 0.0250128276797461;
   fWeightMatrix1to2[1][15] = -0.375936940660691;
   fWeightMatrix1to2[2][15] = -0.630875693855542;
   fWeightMatrix1to2[3][15] = 0.317857748163014;
   fWeightMatrix1to2[4][15] = 0.0520878600314979;
   fWeightMatrix1to2[5][15] = 0.303945776984249;
   fWeightMatrix1to2[6][15] = 1.42979157090473;
   fWeightMatrix1to2[7][15] = -1.85259756448976;
   fWeightMatrix1to2[8][15] = -0.613312609453847;
   fWeightMatrix1to2[9][15] = -5.47026699992283;
   fWeightMatrix1to2[10][15] = -2.62159217591037;
   fWeightMatrix1to2[11][15] = -0.27647041547395;
   fWeightMatrix1to2[12][15] = -0.591403643358686;
   fWeightMatrix1to2[13][15] = 0.529236388003952;
   fWeightMatrix1to2[14][15] = 0.510316000003836;
   fWeightMatrix1to2[15][15] = 2.47667542909993;
   fWeightMatrix1to2[16][15] = -4.42166705112352;
   fWeightMatrix1to2[17][15] = -0.241642224657479;
   fWeightMatrix1to2[18][15] = 0.110768749126856;
   fWeightMatrix1to2[19][15] = 1.59678267422822;
   fWeightMatrix1to2[20][15] = -2.45423037427475;
   fWeightMatrix1to2[21][15] = -0.594597455480634;
   fWeightMatrix1to2[22][15] = -0.612877353689;
   fWeightMatrix1to2[23][15] = -0.572743773395295;
   fWeightMatrix1to2[24][15] = -3.60237219190121;
   fWeightMatrix1to2[0][16] = 0.0268863614074105;
   fWeightMatrix1to2[1][16] = -0.474566517253805;
   fWeightMatrix1to2[2][16] = -0.23178951554357;
   fWeightMatrix1to2[3][16] = 1.57293761574918;
   fWeightMatrix1to2[4][16] = 0.365927351949325;
   fWeightMatrix1to2[5][16] = 0.817068157275374;
   fWeightMatrix1to2[6][16] = -0.0413787549189622;
   fWeightMatrix1to2[7][16] = 1.14288646929471;
   fWeightMatrix1to2[8][16] = -0.544622689124734;
   fWeightMatrix1to2[9][16] = 1.08864280087095;
   fWeightMatrix1to2[10][16] = -6.64956415443388;
   fWeightMatrix1to2[11][16] = 1.83510635377715;
   fWeightMatrix1to2[12][16] = -0.315900647949563;
   fWeightMatrix1to2[13][16] = -0.653953400322834;
   fWeightMatrix1to2[14][16] = -0.105476734158637;
   fWeightMatrix1to2[15][16] = 1.69831707719479;
   fWeightMatrix1to2[16][16] = 5.1953640779072;
   fWeightMatrix1to2[17][16] = 1.00266650342601;
   fWeightMatrix1to2[18][16] = 0.385448836574451;
   fWeightMatrix1to2[19][16] = -0.24843474316773;
   fWeightMatrix1to2[20][16] = -1.71853446454712;
   fWeightMatrix1to2[21][16] = 0.0369380736947305;
   fWeightMatrix1to2[22][16] = -1.53960438828664;
   fWeightMatrix1to2[23][16] = 0.348193750682115;
   fWeightMatrix1to2[24][16] = -0.0672017030306042;
   fWeightMatrix1to2[0][17] = -1.54196274273023;
   fWeightMatrix1to2[1][17] = 0.701573405084316;
   fWeightMatrix1to2[2][17] = -1.51919597234812;
   fWeightMatrix1to2[3][17] = 0.662165283052087;
   fWeightMatrix1to2[4][17] = -0.304505472404482;
   fWeightMatrix1to2[5][17] = -0.831150971209383;
   fWeightMatrix1to2[6][17] = -3.69540406115844;
   fWeightMatrix1to2[7][17] = 0.0807904064791249;
   fWeightMatrix1to2[8][17] = 1.88774066542815;
   fWeightMatrix1to2[9][17] = -3.26316074666594;
   fWeightMatrix1to2[10][17] = 0.962118682364977;
   fWeightMatrix1to2[11][17] = -1.55305776003536;
   fWeightMatrix1to2[12][17] = 2.08129432232933;
   fWeightMatrix1to2[13][17] = -0.88208041482662;
   fWeightMatrix1to2[14][17] = -1.19989967686862;
   fWeightMatrix1to2[15][17] = 0.568812370587778;
   fWeightMatrix1to2[16][17] = 2.24553498174599;
   fWeightMatrix1to2[17][17] = -1.1122774058111;
   fWeightMatrix1to2[18][17] = 1.44618661505006;
   fWeightMatrix1to2[19][17] = -1.11268158253321;
   fWeightMatrix1to2[20][17] = 3.66481076172562;
   fWeightMatrix1to2[21][17] = 0.0359548349673962;
   fWeightMatrix1to2[22][17] = 1.52818885648897;
   fWeightMatrix1to2[23][17] = 2.05998103050851;
   fWeightMatrix1to2[24][17] = 1.11940057937933;
   fWeightMatrix1to2[0][18] = -5.15265998674304;
   fWeightMatrix1to2[1][18] = 3.56631149028349;
   fWeightMatrix1to2[2][18] = 0.388696446730033;
   fWeightMatrix1to2[3][18] = 5.65664705183094;
   fWeightMatrix1to2[4][18] = -14.7880799928626;
   fWeightMatrix1to2[5][18] = -3.33588346665374;
   fWeightMatrix1to2[6][18] = 3.3311725632475;
   fWeightMatrix1to2[7][18] = -4.22755459901478;
   fWeightMatrix1to2[8][18] = -0.693692122422867;
   fWeightMatrix1to2[9][18] = 0.745420387800836;
   fWeightMatrix1to2[10][18] = 0.114645753706809;
   fWeightMatrix1to2[11][18] = 3.02134973166056;
   fWeightMatrix1to2[12][18] = -3.54550818561135;
   fWeightMatrix1to2[13][18] = 1.28683497792943;
   fWeightMatrix1to2[14][18] = -9.38166827326185;
   fWeightMatrix1to2[15][18] = 1.07178846000225;
   fWeightMatrix1to2[16][18] = -0.148550281461294;
   fWeightMatrix1to2[17][18] = 1.09382131679316;
   fWeightMatrix1to2[18][18] = 3.77998219145119;
   fWeightMatrix1to2[19][18] = -0.284132539097082;
   fWeightMatrix1to2[20][18] = 2.7798837545708;
   fWeightMatrix1to2[21][18] = -3.80731247525097;
   fWeightMatrix1to2[22][18] = 3.87592480647216;
   fWeightMatrix1to2[23][18] = 8.56851315621953;
   fWeightMatrix1to2[24][18] = 0.471206563726913;
   fWeightMatrix1to2[0][19] = -0.682966296571664;
   fWeightMatrix1to2[1][19] = -3.60508648356109;
   fWeightMatrix1to2[2][19] = -2.4131166397437;
   fWeightMatrix1to2[3][19] = 3.90654799396764;
   fWeightMatrix1to2[4][19] = 4.14975084529956;
   fWeightMatrix1to2[5][19] = -4.69400116891472;
   fWeightMatrix1to2[6][19] = 2.82778379617728;
   fWeightMatrix1to2[7][19] = -1.92364611384745;
   fWeightMatrix1to2[8][19] = -6.9617759329546;
   fWeightMatrix1to2[9][19] = -1.60210092124769;
   fWeightMatrix1to2[10][19] = -0.149450234262334;
   fWeightMatrix1to2[11][19] = -2.21925362683544;
   fWeightMatrix1to2[12][19] = 2.47918060000308;
   fWeightMatrix1to2[13][19] = 2.80781125287514;
   fWeightMatrix1to2[14][19] = 2.1334390249509;
   fWeightMatrix1to2[15][19] = 0.270810510272066;
   fWeightMatrix1to2[16][19] = -0.81774252187875;
   fWeightMatrix1to2[17][19] = 2.30405418759827;
   fWeightMatrix1to2[18][19] = 1.50534696964971;
   fWeightMatrix1to2[19][19] = 0.462192105802281;
   fWeightMatrix1to2[20][19] = -4.84134299771119;
   fWeightMatrix1to2[21][19] = 4.36772316043132;
   fWeightMatrix1to2[22][19] = 0.702364745219503;
   fWeightMatrix1to2[23][19] = -2.63747290637331;
   fWeightMatrix1to2[24][19] = 3.87308156596434;
   fWeightMatrix1to2[0][20] = -7.28699479742997;
   fWeightMatrix1to2[1][20] = -3.04697433229512;
   fWeightMatrix1to2[2][20] = 1.35340796671898;
   fWeightMatrix1to2[3][20] = 2.54327473735418;
   fWeightMatrix1to2[4][20] = 0.173289546843242;
   fWeightMatrix1to2[5][20] = -3.1294748812814;
   fWeightMatrix1to2[6][20] = -2.95031783466494;
   fWeightMatrix1to2[7][20] = -1.03881471995436;
   fWeightMatrix1to2[8][20] = 1.15796854643911;
   fWeightMatrix1to2[9][20] = 1.01640466123306;
   fWeightMatrix1to2[10][20] = -4.95344451361351;
   fWeightMatrix1to2[11][20] = -5.96063063886518;
   fWeightMatrix1to2[12][20] = -0.366263893406818;
   fWeightMatrix1to2[13][20] = -1.46711173725284;
   fWeightMatrix1to2[14][20] = -5.12846069319939;
   fWeightMatrix1to2[15][20] = -4.98757738886001;
   fWeightMatrix1to2[16][20] = -4.16890437514571;
   fWeightMatrix1to2[17][20] = -6.95231289125319;
   fWeightMatrix1to2[18][20] = 2.85655977294361;
   fWeightMatrix1to2[19][20] = -1.23416949532041;
   fWeightMatrix1to2[20][20] = 0.0574154207558568;
   fWeightMatrix1to2[21][20] = -2.01054213084617;
   fWeightMatrix1to2[22][20] = -1.95162631699284;
   fWeightMatrix1to2[23][20] = -3.97811667346834;
   fWeightMatrix1to2[24][20] = -2.92869803566844;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -2.25629512840355;
   fWeightMatrix2to3[1][0] = -4.05833526639634;
   fWeightMatrix2to3[2][0] = -1.56824053120756;
   fWeightMatrix2to3[0][1] = 1.41367295006999;
   fWeightMatrix2to3[1][1] = 1.54013980995985;
   fWeightMatrix2to3[2][1] = 1.013574746211;
   fWeightMatrix2to3[0][2] = -0.0848707799023392;
   fWeightMatrix2to3[1][2] = 2.34399807517835;
   fWeightMatrix2to3[2][2] = 2.30687610498667;
   fWeightMatrix2to3[0][3] = 1.60797148072377;
   fWeightMatrix2to3[1][3] = 1.25511185004708;
   fWeightMatrix2to3[2][3] = 0.890535307550911;
   fWeightMatrix2to3[0][4] = -0.926747358349635;
   fWeightMatrix2to3[1][4] = 3.76404745136917;
   fWeightMatrix2to3[2][4] = 2.04544072377863;
   fWeightMatrix2to3[0][5] = -2.57336488155346;
   fWeightMatrix2to3[1][5] = 5.55878796310476;
   fWeightMatrix2to3[2][5] = 1.27829267146837;
   fWeightMatrix2to3[0][6] = 1.98019238161486;
   fWeightMatrix2to3[1][6] = -0.458301158279133;
   fWeightMatrix2to3[2][6] = 1.19754508498018;
   fWeightMatrix2to3[0][7] = 2.89279829564903;
   fWeightMatrix2to3[1][7] = -0.702176540231674;
   fWeightMatrix2to3[2][7] = -1.09844308016143;
   fWeightMatrix2to3[0][8] = 1.29785974208666;
   fWeightMatrix2to3[1][8] = 3.15416651638842;
   fWeightMatrix2to3[2][8] = 1.31183205764721;
   fWeightMatrix2to3[0][9] = -0.318890321479123;
   fWeightMatrix2to3[1][9] = 2.227456966777;
   fWeightMatrix2to3[2][9] = 2.51593880379839;
   fWeightMatrix2to3[0][10] = 2.54471201808686;
   fWeightMatrix2to3[1][10] = -1.48983912754307;
   fWeightMatrix2to3[2][10] = -2.76569504594257;
   fWeightMatrix2to3[0][11] = -1.3624678472219;
   fWeightMatrix2to3[1][11] = 1.87405307123512;
   fWeightMatrix2to3[2][11] = 1.00900667770595;
   fWeightMatrix2to3[0][12] = 1.69532349741349;
   fWeightMatrix2to3[1][12] = 1.40660643730397;
   fWeightMatrix2to3[2][12] = 1.62918284990051;
   fWeightMatrix2to3[0][13] = 0.66679055961076;
   fWeightMatrix2to3[1][13] = 0.879846662003259;
   fWeightMatrix2to3[2][13] = 2.29548299675261;
   fWeightMatrix2to3[0][14] = 1.15551607042667;
   fWeightMatrix2to3[1][14] = 2.7644456857133;
   fWeightMatrix2to3[2][14] = 0.250379392005794;
   fWeightMatrix2to3[0][15] = 2.5287096881797;
   fWeightMatrix2to3[1][15] = -0.359414279169979;
   fWeightMatrix2to3[2][15] = -0.914090053689033;
   fWeightMatrix2to3[0][16] = 1.36507231910441;
   fWeightMatrix2to3[1][16] = 0.605564335290176;
   fWeightMatrix2to3[2][16] = 0.835504255409932;
   fWeightMatrix2to3[0][17] = 1.27336719394224;
   fWeightMatrix2to3[1][17] = 0.904413451621461;
   fWeightMatrix2to3[2][17] = 0.643144656043619;
   fWeightMatrix2to3[0][18] = 1.40381939660632;
   fWeightMatrix2to3[1][18] = -0.433690830296163;
   fWeightMatrix2to3[2][18] = -2.02948275076097;
   fWeightMatrix2to3[0][19] = -2.0520736473023;
   fWeightMatrix2to3[1][19] = -1.65858178094319;
   fWeightMatrix2to3[2][19] = -1.72559322111577;
   fWeightMatrix2to3[0][20] = -0.605727861391026;
   fWeightMatrix2to3[1][20] = -2.98421640542584;
   fWeightMatrix2to3[2][20] = -1.30185193785341;
   fWeightMatrix2to3[0][21] = 0.948826069681787;
   fWeightMatrix2to3[1][21] = -1.58846366070279;
   fWeightMatrix2to3[2][21] = -1.7192344535342;
   fWeightMatrix2to3[0][22] = 1.8234194702417;
   fWeightMatrix2to3[1][22] = 2.13948186965142;
   fWeightMatrix2to3[2][22] = 1.73226016092353;
   fWeightMatrix2to3[0][23] = 0.608080372457926;
   fWeightMatrix2to3[1][23] = -0.582245597035204;
   fWeightMatrix2to3[2][23] = -1.21802906566433;
   fWeightMatrix2to3[0][24] = -0.90355359781788;
   fWeightMatrix2to3[1][24] = -1.87945773975786;
   fWeightMatrix2to3[2][24] = -0.645663382232206;
   fWeightMatrix2to3[0][25] = 2.30721332719155;
   fWeightMatrix2to3[1][25] = 0.67904571055016;
   fWeightMatrix2to3[2][25] = -1.2309774240912;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 3.38073921390451;
   fWeightMatrix3to4[0][1] = -8.24765945139871;
   fWeightMatrix3to4[0][2] = -8.49690944379364;
   fWeightMatrix3to4[0][3] = 4.88870993536364;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 66.8327102661;
   fMax_1[0][0] = 2426.51416016;
   fMin_1[1][0] = 31.8515205383;
   fMax_1[1][0] = 5348.45361328;
   fMin_1[2][0] = 31.8515205383;
   fMax_1[2][0] = 5348.45361328;
   fMin_1[0][1] = 17.2699775696;
   fMax_1[0][1] = 2311.00366211;
   fMin_1[1][1] = 13.9813117981;
   fMax_1[1][1] = 4877.60791016;
   fMin_1[2][1] = 13.9813117981;
   fMax_1[2][1] = 4877.60791016;
   fMin_1[0][2] = 60.0897598267;
   fMax_1[0][2] = 1425.15393066;
   fMin_1[1][2] = 60.025062561;
   fMax_1[1][2] = 2697.76367188;
   fMin_1[2][2] = 60.025062561;
   fMax_1[2][2] = 2697.76367188;
   fMin_1[0][3] = 7.62939453125e-06;
   fMax_1[0][3] = 860.468444824;
   fMin_1[1][3] = 3.81469726562e-06;
   fMax_1[1][3] = 1557.57641602;
   fMin_1[2][3] = 3.81469726562e-06;
   fMax_1[2][3] = 1557.57641602;
   fMin_1[0][4] = 0.395419180393;
   fMax_1[0][4] = 5.1114897728;
   fMin_1[1][4] = 0.347917675972;
   fMax_1[1][4] = 5.68921756744;
   fMin_1[2][4] = 0.347917675972;
   fMax_1[2][4] = 5.68921756744;
   fMin_1[0][5] = 31.8425750732;
   fMax_1[0][5] = 1090.74365234;
   fMin_1[1][5] = 30.5779666901;
   fMax_1[1][5] = 2559.47729492;
   fMin_1[2][5] = 30.5779666901;
   fMax_1[2][5] = 2559.47729492;
   fMin_1[0][6] = -870.999145508;
   fMax_1[0][6] = 862.295288086;
   fMin_1[1][6] = -1405.72998047;
   fMax_1[1][6] = 1577.42077637;
   fMin_1[2][6] = -1405.72998047;
   fMax_1[2][6] = 1577.42077637;
   fMin_1[0][7] = 0.00366772944108;
   fMax_1[0][7] = 8.2374048233;
   fMin_1[1][7] = 0.0013404173078;
   fMax_1[1][7] = 9.45198535919;
   fMin_1[2][7] = 0.0013404173078;
   fMax_1[2][7] = 9.45198535919;
   fMin_1[0][8] = 60.0203704834;
   fMax_1[0][8] = 1295.66699219;
   fMin_1[1][8] = 60.0203704834;
   fMax_1[1][8] = 1615.55944824;
   fMin_1[2][8] = 60.0203704834;
   fMax_1[2][8] = 1615.55944824;
   fMin_1[0][9] = -755.58782959;
   fMax_1[0][9] = 674.663696289;
   fMin_1[1][9] = -775.365600586;
   fMax_1[1][9] = 1340.12573242;
   fMin_1[2][9] = -775.365600586;
   fMax_1[2][9] = 1340.12573242;
   fMin_1[0][10] = 0.500020980835;
   fMax_1[0][10] = 5.5945224762;
   fMin_1[1][10] = 0.500000238419;
   fMax_1[1][10] = 5.59625434875;
   fMin_1[2][10] = 0.500000238419;
   fMax_1[2][10] = 5.59625434875;
   fMin_1[0][11] = 31.4379367828;
   fMax_1[0][11] = 1241.76513672;
   fMin_1[1][11] = 30.4070301056;
   fMax_1[1][11] = 2222.31030273;
   fMin_1[2][11] = 30.4070301056;
   fMax_1[2][11] = 2222.31030273;
   fMin_1[0][12] = -791.472106934;
   fMax_1[0][12] = 840.090026855;
   fMin_1[1][12] = -809.493469238;
   fMax_1[1][12] = 1631.58105469;
   fMin_1[2][12] = -809.493469238;
   fMax_1[2][12] = 1631.58105469;
   fMin_1[0][13] = 0.0018430177588;
   fMax_1[0][13] = 8.91576004028;
   fMin_1[1][13] = 0.0018430177588;
   fMax_1[1][13] = 9.91743087769;
   fMin_1[2][13] = 0.0018430177588;
   fMax_1[2][13] = 9.91743087769;
   fMin_1[0][14] = -3.14159107208;
   fMax_1[0][14] = 3.14159178734;
   fMin_1[1][14] = -3.14159059525;
   fMax_1[1][14] = 3.14159250259;
   fMin_1[2][14] = -3.14159107208;
   fMax_1[2][14] = 3.14159250259;
   fMin_1[0][15] = 31.2111606598;
   fMax_1[0][15] = 1194.1036377;
   fMin_1[1][15] = 30.5801753998;
   fMax_1[1][15] = 2064.86572266;
   fMin_1[2][15] = 30.5801753998;
   fMax_1[2][15] = 2064.86572266;
   fMin_1[0][16] = -757.706237793;
   fMax_1[0][16] = 753.565551758;
   fMin_1[1][16] = -985.94921875;
   fMax_1[1][16] = 1119.99047852;
   fMin_1[2][16] = -985.94921875;
   fMax_1[2][16] = 1119.99047852;
   fMin_1[0][17] = -3.14159059525;
   fMax_1[0][17] = 3.14159178734;
   fMin_1[1][17] = -3.14159250259;
   fMax_1[1][17] = 3.14159178734;
   fMin_1[2][17] = -3.14159250259;
   fMax_1[2][17] = 3.14159178734;
   fMin_1[0][18] = 0.611416637897;
   fMax_1[0][18] = 1286.62390137;
   fMin_1[1][18] = 1.36658203602;
   fMax_1[1][18] = 2449.66552734;
   fMin_1[2][18] = 0.611416637897;
   fMax_1[2][18] = 2449.66552734;
   fMin_1[0][19] = -764.301574707;
   fMax_1[0][19] = 775.467712402;
   fMin_1[1][19] = -940.587097168;
   fMax_1[1][19] = 1606.44128418;
   fMin_1[2][19] = -940.587097168;
   fMax_1[2][19] = 1606.44128418;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 20;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<20;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
