// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Tue Jan  7 15:46:28 2020
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 2617521
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "550" [Number of training cycles]
HiddenLayers: "N,N+5,3" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [35.7156524658,5135.92919922]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [15.6709527969,4321.85888672]
j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                                                      'D'    [60.0363311768,2697.76367188]
j1j2_absdelPt                 j1j2_absdelPt                 j1j2_absdelPt                 j1j2_absdelPt                                                   'D'    [1.52587890625e-05,1557.57641602]
j1j2_delR                     j1j2_delR                     j1j2_delR                     j1j2_delR                                                       'D'    [0.372943520546,5.66675138474]
whadb_sumPt                   whadb_sumPt                   whadb_sumPt                   whadb_sumPt                                                     'D'    [30.6295623779,2559.47729492]
whadb_delPt                   whadb_delPt                   whadb_delPt                   whadb_delPt                                                     'D'    [-1010.5993042,1398.72265625]
whadb_delR                    whadb_delR                    whadb_delR                    whadb_delR                                                      'D'    [0.00573204737157,8.96139144897]
hadblepton_sumPt              hadblepton_sumPt              hadblepton_sumPt              hadblepton_sumPt                                                'D'    [60.0203704834,1431.1965332]
hadblepton_delPt              hadblepton_delPt              hadblepton_delPt              hadblepton_delPt                                                'D'    [-773.499450684,1060.76464844]
hadblepton_delR               hadblepton_delR               hadblepton_delR               hadblepton_delR                                                 'D'    [0.500000238419,5.58469629288]
hadwlepton_sumPt              hadwlepton_sumPt              hadwlepton_sumPt              hadwlepton_sumPt                                                'D'    [31.0787239075,1935.83288574]
hadwlepton_delPt              hadwlepton_delPt              hadwlepton_delPt              hadwlepton_delPt                                                'D'    [-809.493469238,1498.68908691]
hadwlepton_delR               hadwlepton_delR               hadwlepton_delR               hadwlepton_delR                                                 'D'    [0.00712582096457,9.17821788788]
hadbmet_delPhi                hadbmet_delPhi                hadbmet_delPhi                hadbmet_delPhi                                                  'D'    [-3.1415822506,3.14159250259]
hadbmet_sumPt                 hadbmet_sumPt                 hadbmet_sumPt                 hadbmet_sumPt                                                   'D'    [31.2111606598,1386.0456543]
hadbmet_delPt                 hadbmet_delPt                 hadbmet_delPt                 hadbmet_delPt                                                   'D'    [-859.980834961,1050.97570801]
hadwmet_delPhi                hadwmet_delPhi                hadwmet_delPhi                hadwmet_delPhi                                                  'D'    [-3.14158701897,3.14159178734]
hadwmet_sumPt                 hadwmet_sumPt                 hadwmet_sumPt                 hadwmet_sumPt                                                   'D'    [0.611416637897,2022.60778809]
hadwmet_delPt                 hadwmet_delPt                 hadwmet_delPt                 hadwmet_delPt                                                   'D'    [-863.287109375,1526.7520752]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass", "j1j2_sumPt", "j1j2_absdelPt", "j1j2_delR", "whadb_sumPt", "whadb_delPt", "whadb_delR", "hadblepton_sumPt", "hadblepton_delPt", "hadblepton_delR", "hadwlepton_sumPt", "hadwlepton_delPt", "hadwlepton_delR", "hadbmet_delPhi", "hadbmet_sumPt", "hadbmet_delPt", "hadwmet_delPhi", "hadwmet_sumPt", "hadwmet_delPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 0.99999988079071;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';
      fType[16] = 'D';
      fType[17] = 'D';
      fType[18] = 'D';
      fType[19] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][20];
   double fMax_1[3][20];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[21][21];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[26][21];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[4][26];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][4];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 21; fWeights[0] = new double[21]; 
   fLayerSize[1] = 21; fWeights[1] = new double[21]; 
   fLayerSize[2] = 26; fWeights[2] = new double[26]; 
   fLayerSize[3] = 4; fWeights[3] = new double[4]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 14.8991098099096;
   fWeightMatrix0to1[1][0] = 47.2007706085466;
   fWeightMatrix0to1[2][0] = 11.8007992605095;
   fWeightMatrix0to1[3][0] = 4.66805069710951;
   fWeightMatrix0to1[4][0] = -20.2648777786419;
   fWeightMatrix0to1[5][0] = -2.15533691961055;
   fWeightMatrix0to1[6][0] = 8.38006362548067;
   fWeightMatrix0to1[7][0] = 2.04658571420833;
   fWeightMatrix0to1[8][0] = -33.5020537504353;
   fWeightMatrix0to1[9][0] = -6.37132322734331;
   fWeightMatrix0to1[10][0] = -13.5946199769289;
   fWeightMatrix0to1[11][0] = -10.1333541374114;
   fWeightMatrix0to1[12][0] = 4.96836068674365;
   fWeightMatrix0to1[13][0] = -0.453838170107344;
   fWeightMatrix0to1[14][0] = -16.1444916848978;
   fWeightMatrix0to1[15][0] = -5.5643078866472;
   fWeightMatrix0to1[16][0] = 82.3282170677712;
   fWeightMatrix0to1[17][0] = -7.06758705944144;
   fWeightMatrix0to1[18][0] = 4.83350265292411;
   fWeightMatrix0to1[19][0] = -30.9132291615965;
   fWeightMatrix0to1[0][1] = 3.56562485140957;
   fWeightMatrix0to1[1][1] = -17.5605134181514;
   fWeightMatrix0to1[2][1] = -12.5415215094128;
   fWeightMatrix0to1[3][1] = 1.28637524620228;
   fWeightMatrix0to1[4][1] = 8.89992609860635;
   fWeightMatrix0to1[5][1] = -6.30488214574951;
   fWeightMatrix0to1[6][1] = 3.62673917896454;
   fWeightMatrix0to1[7][1] = -0.642199987580342;
   fWeightMatrix0to1[8][1] = -4.7999174068064;
   fWeightMatrix0to1[9][1] = 8.03746720417967;
   fWeightMatrix0to1[10][1] = 10.5105740453441;
   fWeightMatrix0to1[11][1] = 9.40122899301526;
   fWeightMatrix0to1[12][1] = -6.1280658550963;
   fWeightMatrix0to1[13][1] = -0.671403952895554;
   fWeightMatrix0to1[14][1] = -7.21091158260797;
   fWeightMatrix0to1[15][1] = 8.28470440302287;
   fWeightMatrix0to1[16][1] = -42.3755466898677;
   fWeightMatrix0to1[17][1] = -5.35158644871868;
   fWeightMatrix0to1[18][1] = -2.75489043030577;
   fWeightMatrix0to1[19][1] = 15.9798822627141;
   fWeightMatrix0to1[0][2] = -14.0390687444328;
   fWeightMatrix0to1[1][2] = 6.94037669412659;
   fWeightMatrix0to1[2][2] = -8.05566143988099;
   fWeightMatrix0to1[3][2] = -1.56496507214051;
   fWeightMatrix0to1[4][2] = 6.49600309214232;
   fWeightMatrix0to1[5][2] = -22.4707185090395;
   fWeightMatrix0to1[6][2] = -2.34556241367144;
   fWeightMatrix0to1[7][2] = 0.498131260387771;
   fWeightMatrix0to1[8][2] = 3.85036552723858;
   fWeightMatrix0to1[9][2] = 0.941028089593822;
   fWeightMatrix0to1[10][2] = 4.85088819096088;
   fWeightMatrix0to1[11][2] = 9.78624529542031;
   fWeightMatrix0to1[12][2] = -1.67613696474488;
   fWeightMatrix0to1[13][2] = 0.742212755817494;
   fWeightMatrix0to1[14][2] = 6.31498697017307;
   fWeightMatrix0to1[15][2] = 4.81824460946905;
   fWeightMatrix0to1[16][2] = -22.3446905929818;
   fWeightMatrix0to1[17][2] = 1.4109807339457;
   fWeightMatrix0to1[18][2] = 2.29112322419739;
   fWeightMatrix0to1[19][2] = -9.89967680345847;
   fWeightMatrix0to1[0][3] = -1.28090813427673;
   fWeightMatrix0to1[1][3] = -1.30349946451558;
   fWeightMatrix0to1[2][3] = 14.5170257646995;
   fWeightMatrix0to1[3][3] = -0.270687755670887;
   fWeightMatrix0to1[4][3] = -3.16447397300479;
   fWeightMatrix0to1[5][3] = 8.44981962704099;
   fWeightMatrix0to1[6][3] = -2.64324733139484;
   fWeightMatrix0to1[7][3] = -2.01024297861934;
   fWeightMatrix0to1[8][3] = 17.3543087715199;
   fWeightMatrix0to1[9][3] = -6.71148650324787;
   fWeightMatrix0to1[10][3] = -9.0875708823293;
   fWeightMatrix0to1[11][3] = -3.1124048839377;
   fWeightMatrix0to1[12][3] = 1.68974375731982;
   fWeightMatrix0to1[13][3] = 0.332520550739554;
   fWeightMatrix0to1[14][3] = 6.44295561233794;
   fWeightMatrix0to1[15][3] = -6.457576238938;
   fWeightMatrix0to1[16][3] = 8.08188524221846;
   fWeightMatrix0to1[17][3] = 4.08809852936628;
   fWeightMatrix0to1[18][3] = 3.67060374382715;
   fWeightMatrix0to1[19][3] = 0.473681918837519;
   fWeightMatrix0to1[0][4] = -0.704478804486333;
   fWeightMatrix0to1[1][4] = 0.863555401194618;
   fWeightMatrix0to1[2][4] = 2.78013964238582;
   fWeightMatrix0to1[3][4] = -0.942446666068543;
   fWeightMatrix0to1[4][4] = 9.368894516677;
   fWeightMatrix0to1[5][4] = -5.08785315848955;
   fWeightMatrix0to1[6][4] = 0.925303342075304;
   fWeightMatrix0to1[7][4] = 0.13819650454622;
   fWeightMatrix0to1[8][4] = -2.08813701038912;
   fWeightMatrix0to1[9][4] = -7.22387582155777;
   fWeightMatrix0to1[10][4] = 4.25451490459941;
   fWeightMatrix0to1[11][4] = -0.0308252977622243;
   fWeightMatrix0to1[12][4] = 6.10849785258025;
   fWeightMatrix0to1[13][4] = -1.12187120243909;
   fWeightMatrix0to1[14][4] = -1.90910353656198;
   fWeightMatrix0to1[15][4] = 5.11896500830446;
   fWeightMatrix0to1[16][4] = -0.448469007832411;
   fWeightMatrix0to1[17][4] = -11.364199082407;
   fWeightMatrix0to1[18][4] = -9.46682314198836;
   fWeightMatrix0to1[19][4] = 3.06968434605565;
   fWeightMatrix0to1[0][5] = -5.86652216850145;
   fWeightMatrix0to1[1][5] = -4.69187282981277;
   fWeightMatrix0to1[2][5] = -1.67129997781852;
   fWeightMatrix0to1[3][5] = 1.36502746035093;
   fWeightMatrix0to1[4][5] = 0.952579750568516;
   fWeightMatrix0to1[5][5] = 2.09281327741685;
   fWeightMatrix0to1[6][5] = -1.00485712850404;
   fWeightMatrix0to1[7][5] = -1.31025135200814;
   fWeightMatrix0to1[8][5] = 0.29597796677597;
   fWeightMatrix0to1[9][5] = 1.02076549979442;
   fWeightMatrix0to1[10][5] = 0.0230394133321835;
   fWeightMatrix0to1[11][5] = -1.2956395510461;
   fWeightMatrix0to1[12][5] = -1.42151099981249;
   fWeightMatrix0to1[13][5] = 0.48671741785747;
   fWeightMatrix0to1[14][5] = -1.50503485224142;
   fWeightMatrix0to1[15][5] = 4.28823579070753;
   fWeightMatrix0to1[16][5] = -3.14902820483899;
   fWeightMatrix0to1[17][5] = 1.01749986751895;
   fWeightMatrix0to1[18][5] = 0.551487719818846;
   fWeightMatrix0to1[19][5] = 2.83353325124509;
   fWeightMatrix0to1[0][6] = 0.00934243944451424;
   fWeightMatrix0to1[1][6] = 1.85801467456331;
   fWeightMatrix0to1[2][6] = -3.73623726269425;
   fWeightMatrix0to1[3][6] = 1.33326567841836;
   fWeightMatrix0to1[4][6] = 3.12141059388208;
   fWeightMatrix0to1[5][6] = -7.09776121308813;
   fWeightMatrix0to1[6][6] = 0.0409394452674019;
   fWeightMatrix0to1[7][6] = -0.354705173408309;
   fWeightMatrix0to1[8][6] = -7.21363770843341;
   fWeightMatrix0to1[9][6] = -0.320737306854675;
   fWeightMatrix0to1[10][6] = -0.0552291056215709;
   fWeightMatrix0to1[11][6] = 0.341214054248838;
   fWeightMatrix0to1[12][6] = 0.55898774129724;
   fWeightMatrix0to1[13][6] = -1.85775483177342;
   fWeightMatrix0to1[14][6] = -4.78394846616397;
   fWeightMatrix0to1[15][6] = 2.62320466699525;
   fWeightMatrix0to1[16][6] = 1.23839895864716;
   fWeightMatrix0to1[17][6] = -10.4703934363366;
   fWeightMatrix0to1[18][6] = 0.139891519512059;
   fWeightMatrix0to1[19][6] = 1.97103999061971;
   fWeightMatrix0to1[0][7] = 1.1733292054691;
   fWeightMatrix0to1[1][7] = -1.75217370991656;
   fWeightMatrix0to1[2][7] = 0.333260205854629;
   fWeightMatrix0to1[3][7] = -0.0133837262268497;
   fWeightMatrix0to1[4][7] = -2.50831534744589;
   fWeightMatrix0to1[5][7] = 1.2868796236226;
   fWeightMatrix0to1[6][7] = -0.51654826927478;
   fWeightMatrix0to1[7][7] = -0.182882370827352;
   fWeightMatrix0to1[8][7] = 0.698851852311314;
   fWeightMatrix0to1[9][7] = -1.94849637943341;
   fWeightMatrix0to1[10][7] = -0.488889903479909;
   fWeightMatrix0to1[11][7] = 2.82004490981651;
   fWeightMatrix0to1[12][7] = 8.05064943555822;
   fWeightMatrix0to1[13][7] = 0.144669473015929;
   fWeightMatrix0to1[14][7] = 0.662149374751417;
   fWeightMatrix0to1[15][7] = -0.760781537849418;
   fWeightMatrix0to1[16][7] = -0.813183019110017;
   fWeightMatrix0to1[17][7] = 5.28412593656817;
   fWeightMatrix0to1[18][7] = 0.591175455655168;
   fWeightMatrix0to1[19][7] = -4.07715583607494;
   fWeightMatrix0to1[0][8] = 5.69579048987715;
   fWeightMatrix0to1[1][8] = 1.26348203911768;
   fWeightMatrix0to1[2][8] = -0.973928517385671;
   fWeightMatrix0to1[3][8] = -0.793782705854122;
   fWeightMatrix0to1[4][8] = -0.200062189265676;
   fWeightMatrix0to1[5][8] = 1.26210350442144;
   fWeightMatrix0to1[6][8] = 2.83368204424868;
   fWeightMatrix0to1[7][8] = 1.03578152817165;
   fWeightMatrix0to1[8][8] = 1.03462640306389;
   fWeightMatrix0to1[9][8] = -1.26057763413196;
   fWeightMatrix0to1[10][8] = 6.86750526762048;
   fWeightMatrix0to1[11][8] = -2.37733081956158;
   fWeightMatrix0to1[12][8] = 0.00866991435918507;
   fWeightMatrix0to1[13][8] = 1.8495870964381;
   fWeightMatrix0to1[14][8] = 11.7358060878299;
   fWeightMatrix0to1[15][8] = -1.90252066825563;
   fWeightMatrix0to1[16][8] = -1.07185903628671;
   fWeightMatrix0to1[17][8] = 5.54358243623303;
   fWeightMatrix0to1[18][8] = 0.249464021370213;
   fWeightMatrix0to1[19][8] = -1.86682286068511;
   fWeightMatrix0to1[0][9] = -12.1051321079654;
   fWeightMatrix0to1[1][9] = 1.27831022177508;
   fWeightMatrix0to1[2][9] = 0.773012874511502;
   fWeightMatrix0to1[3][9] = -1.11097892267671;
   fWeightMatrix0to1[4][9] = 1.51221130650428;
   fWeightMatrix0to1[5][9] = -0.436333713720197;
   fWeightMatrix0to1[6][9] = -2.85753050917929;
   fWeightMatrix0to1[7][9] = 1.61330462384399;
   fWeightMatrix0to1[8][9] = -1.18788636446546;
   fWeightMatrix0to1[9][9] = -0.943350105118662;
   fWeightMatrix0to1[10][9] = -0.730751636351038;
   fWeightMatrix0to1[11][9] = -0.592350445073623;
   fWeightMatrix0to1[12][9] = 0.926596619458789;
   fWeightMatrix0to1[13][9] = 1.57696329089685;
   fWeightMatrix0to1[14][9] = -0.00197303506067294;
   fWeightMatrix0to1[15][9] = 2.6426294174562;
   fWeightMatrix0to1[16][9] = -1.85543140359375;
   fWeightMatrix0to1[17][9] = 8.56550928216431;
   fWeightMatrix0to1[18][9] = 0.109049670816621;
   fWeightMatrix0to1[19][9] = -1.19384401308067;
   fWeightMatrix0to1[0][10] = -0.730809346012436;
   fWeightMatrix0to1[1][10] = 0.194554954636307;
   fWeightMatrix0to1[2][10] = -0.000868303287077522;
   fWeightMatrix0to1[3][10] = 0.491860876841739;
   fWeightMatrix0to1[4][10] = -0.0987953261278305;
   fWeightMatrix0to1[5][10] = 0.323691110426225;
   fWeightMatrix0to1[6][10] = -7.6788386522916;
   fWeightMatrix0to1[7][10] = 0.369560620945299;
   fWeightMatrix0to1[8][10] = -0.0799419162721214;
   fWeightMatrix0to1[9][10] = -0.160997090967764;
   fWeightMatrix0to1[10][10] = 0.100203312905436;
   fWeightMatrix0to1[11][10] = 0.0409490599504735;
   fWeightMatrix0to1[12][10] = 0.271076063537496;
   fWeightMatrix0to1[13][10] = -2.80485647715322;
   fWeightMatrix0to1[14][10] = 4.03537934006121;
   fWeightMatrix0to1[15][10] = 0.723426563074943;
   fWeightMatrix0to1[16][10] = 0.0127290339534405;
   fWeightMatrix0to1[17][10] = 0.205347839429859;
   fWeightMatrix0to1[18][10] = 0.271284369168159;
   fWeightMatrix0to1[19][10] = 0.0250896455067856;
   fWeightMatrix0to1[0][11] = 3.69246408276072;
   fWeightMatrix0to1[1][11] = 1.05008933603834;
   fWeightMatrix0to1[2][11] = -6.14498444166659;
   fWeightMatrix0to1[3][11] = -0.496740747292725;
   fWeightMatrix0to1[4][11] = 3.63179590784001;
   fWeightMatrix0to1[5][11] = -7.17607445523419;
   fWeightMatrix0to1[6][11] = 3.74902753699808;
   fWeightMatrix0to1[7][11] = -0.779614175372261;
   fWeightMatrix0to1[8][11] = -5.79738718035424;
   fWeightMatrix0to1[9][11] = -2.57830274954903;
   fWeightMatrix0to1[10][11] = 4.27244300507477;
   fWeightMatrix0to1[11][11] = 0.164467806938655;
   fWeightMatrix0to1[12][11] = 0.753331733074941;
   fWeightMatrix0to1[13][11] = -1.48879566393306;
   fWeightMatrix0to1[14][11] = 2.50584527142782;
   fWeightMatrix0to1[15][11] = -0.323835785677364;
   fWeightMatrix0to1[16][11] = -1.67015095806346;
   fWeightMatrix0to1[17][11] = -6.31966375787521;
   fWeightMatrix0to1[18][11] = -1.84181567681772;
   fWeightMatrix0to1[19][11] = 0.0711783060774493;
   fWeightMatrix0to1[0][12] = -8.64769704541847;
   fWeightMatrix0to1[1][12] = 1.30884451606263;
   fWeightMatrix0to1[2][12] = -6.16556680022281;
   fWeightMatrix0to1[3][12] = -1.53913354440218;
   fWeightMatrix0to1[4][12] = 1.89508359753682;
   fWeightMatrix0to1[5][12] = -7.01010554765231;
   fWeightMatrix0to1[6][12] = -3.13399617731759;
   fWeightMatrix0to1[7][12] = -2.24979138977739;
   fWeightMatrix0to1[8][12] = -4.6831241061724;
   fWeightMatrix0to1[9][12] = -2.55924154575024;
   fWeightMatrix0to1[10][12] = 0.163742150264107;
   fWeightMatrix0to1[11][12] = -0.145949048125854;
   fWeightMatrix0to1[12][12] = -0.481033065683894;
   fWeightMatrix0to1[13][12] = 1.82093786400984;
   fWeightMatrix0to1[14][12] = -3.94543672323425;
   fWeightMatrix0to1[15][12] = 3.31046307527914;
   fWeightMatrix0to1[16][12] = -2.03807765192122;
   fWeightMatrix0to1[17][12] = -4.02997598122212;
   fWeightMatrix0to1[18][12] = -1.37225402812238;
   fWeightMatrix0to1[19][12] = -0.898686226242728;
   fWeightMatrix0to1[0][13] = -1.57694924320184;
   fWeightMatrix0to1[1][13] = -0.629270968330873;
   fWeightMatrix0to1[2][13] = 0.225133222498277;
   fWeightMatrix0to1[3][13] = -0.559791712683454;
   fWeightMatrix0to1[4][13] = -0.609072459689008;
   fWeightMatrix0to1[5][13] = -0.662934319754639;
   fWeightMatrix0to1[6][13] = -0.732403878639171;
   fWeightMatrix0to1[7][13] = 2.35776194064707;
   fWeightMatrix0to1[8][13] = -0.727204013589769;
   fWeightMatrix0to1[9][13] = -1.14943755999958;
   fWeightMatrix0to1[10][13] = -1.04460872907688;
   fWeightMatrix0to1[11][13] = -0.635064739518556;
   fWeightMatrix0to1[12][13] = -0.0438842431788388;
   fWeightMatrix0to1[13][13] = 1.54503746365408;
   fWeightMatrix0to1[14][13] = 1.07842532158319;
   fWeightMatrix0to1[15][13] = -2.11954411933387;
   fWeightMatrix0to1[16][13] = 0.107628583642082;
   fWeightMatrix0to1[17][13] = -0.385643806265662;
   fWeightMatrix0to1[18][13] = 0.00718926544401614;
   fWeightMatrix0to1[19][13] = -0.005410964575792;
   fWeightMatrix0to1[0][14] = -0.0310561349654102;
   fWeightMatrix0to1[1][14] = -0.01790048508267;
   fWeightMatrix0to1[2][14] = -0.0058498057383693;
   fWeightMatrix0to1[3][14] = -0.762083748973879;
   fWeightMatrix0to1[4][14] = -0.0325447277265116;
   fWeightMatrix0to1[5][14] = 0.0559235367444599;
   fWeightMatrix0to1[6][14] = 0.0128636787993878;
   fWeightMatrix0to1[7][14] = 0.055650393637389;
   fWeightMatrix0to1[8][14] = -0.0185581377765593;
   fWeightMatrix0to1[9][14] = -0.027933539443207;
   fWeightMatrix0to1[10][14] = -0.00998453038304311;
   fWeightMatrix0to1[11][14] = -0.0605433934786804;
   fWeightMatrix0to1[12][14] = -0.0474009281945772;
   fWeightMatrix0to1[13][14] = 0.360555896300129;
   fWeightMatrix0to1[14][14] = 0.00941099387513223;
   fWeightMatrix0to1[15][14] = 0.0487458928510977;
   fWeightMatrix0to1[16][14] = -0.0128592941653811;
   fWeightMatrix0to1[17][14] = 0.00445905272656227;
   fWeightMatrix0to1[18][14] = 0.0167092325962256;
   fWeightMatrix0to1[19][14] = -0.00497707031932007;
   fWeightMatrix0to1[0][15] = 2.3284263016481;
   fWeightMatrix0to1[1][15] = 2.38978497070063;
   fWeightMatrix0to1[2][15] = -1.57606666412121;
   fWeightMatrix0to1[3][15] = -1.18860303799209;
   fWeightMatrix0to1[4][15] = 1.30019937764735;
   fWeightMatrix0to1[5][15] = -0.358885964107027;
   fWeightMatrix0to1[6][15] = -2.41179686481285;
   fWeightMatrix0to1[7][15] = -1.08798303921895;
   fWeightMatrix0to1[8][15] = -1.4012695876182;
   fWeightMatrix0to1[9][15] = -1.35406455967577;
   fWeightMatrix0to1[10][15] = 1.80477316208248;
   fWeightMatrix0to1[11][15] = -1.89400309281916;
   fWeightMatrix0to1[12][15] = -1.63299961436757;
   fWeightMatrix0to1[13][15] = 1.97837256003296;
   fWeightMatrix0to1[14][15] = 6.80776795451978;
   fWeightMatrix0to1[15][15] = 1.25259872116374;
   fWeightMatrix0to1[16][15] = 1.45348051381721;
   fWeightMatrix0to1[17][15] = 4.58185573551791;
   fWeightMatrix0to1[18][15] = 0.376500711871596;
   fWeightMatrix0to1[19][15] = -0.86520645357789;
   fWeightMatrix0to1[0][16] = -11.0252346825664;
   fWeightMatrix0to1[1][16] = 0.0821255593559892;
   fWeightMatrix0to1[2][16] = -0.888707185174093;
   fWeightMatrix0to1[3][16] = -1.35166895718831;
   fWeightMatrix0to1[4][16] = 0.912253970765259;
   fWeightMatrix0to1[5][16] = -0.23152035359134;
   fWeightMatrix0to1[6][16] = 1.6060239754127;
   fWeightMatrix0to1[7][16] = 0.917782037206326;
   fWeightMatrix0to1[8][16] = -3.1380704857643;
   fWeightMatrix0to1[9][16] = -1.36651357781988;
   fWeightMatrix0to1[10][16] = 2.17046242533486;
   fWeightMatrix0to1[11][16] = -2.7093429904256;
   fWeightMatrix0to1[12][16] = -1.18710481845149;
   fWeightMatrix0to1[13][16] = -1.24153172792139;
   fWeightMatrix0to1[14][16] = 2.47979954276399;
   fWeightMatrix0to1[15][16] = 4.10549244263118;
   fWeightMatrix0to1[16][16] = 0.762377319803571;
   fWeightMatrix0to1[17][16] = 6.7654756286444;
   fWeightMatrix0to1[18][16] = 0.296623195500008;
   fWeightMatrix0to1[19][16] = -0.640745357780879;
   fWeightMatrix0to1[0][17] = 0.0739513538219728;
   fWeightMatrix0to1[1][17] = -0.117331585512041;
   fWeightMatrix0to1[2][17] = 0.00641012227004732;
   fWeightMatrix0to1[3][17] = -6.86687398684433;
   fWeightMatrix0to1[4][17] = -0.00419766473725293;
   fWeightMatrix0to1[5][17] = 0.00466812650990276;
   fWeightMatrix0to1[6][17] = -0.102156887104449;
   fWeightMatrix0to1[7][17] = 0.209033430800725;
   fWeightMatrix0to1[8][17] = -0.0698687579774495;
   fWeightMatrix0to1[9][17] = 0.0418479264376331;
   fWeightMatrix0to1[10][17] = -0.203683232644733;
   fWeightMatrix0to1[11][17] = -0.811954470498437;
   fWeightMatrix0to1[12][17] = -0.176210753099413;
   fWeightMatrix0to1[13][17] = 0.898954061973071;
   fWeightMatrix0to1[14][17] = -0.174960592060696;
   fWeightMatrix0to1[15][17] = 0.051269261261561;
   fWeightMatrix0to1[16][17] = -0.0209768428800661;
   fWeightMatrix0to1[17][17] = -0.145388069272626;
   fWeightMatrix0to1[18][17] = 0.0427158572019351;
   fWeightMatrix0to1[19][17] = 0.0328424921080329;
   fWeightMatrix0to1[0][18] = 5.09230019829691;
   fWeightMatrix0to1[1][18] = -0.735964342854352;
   fWeightMatrix0to1[2][18] = -5.97560871464952;
   fWeightMatrix0to1[3][18] = -2.31840551121623;
   fWeightMatrix0to1[4][18] = 4.03160409241945;
   fWeightMatrix0to1[5][18] = -5.49903656530423;
   fWeightMatrix0to1[6][18] = -2.09500619686125;
   fWeightMatrix0to1[7][18] = -0.708161644753068;
   fWeightMatrix0to1[8][18] = -4.45331195172851;
   fWeightMatrix0to1[9][18] = -1.49891191285047;
   fWeightMatrix0to1[10][18] = 0.830928405951811;
   fWeightMatrix0to1[11][18] = 0.406664699993671;
   fWeightMatrix0to1[12][18] = -2.44783038731082;
   fWeightMatrix0to1[13][18] = 1.31008220404689;
   fWeightMatrix0to1[14][18] = -1.26712381926013;
   fWeightMatrix0to1[15][18] = 2.29446435874449;
   fWeightMatrix0to1[16][18] = -2.21542349306278;
   fWeightMatrix0to1[17][18] = -3.49012907014411;
   fWeightMatrix0to1[18][18] = 0.993838475509573;
   fWeightMatrix0to1[19][18] = 2.00219511190596;
   fWeightMatrix0to1[0][19] = -7.33035156457974;
   fWeightMatrix0to1[1][19] = 0.684410620867248;
   fWeightMatrix0to1[2][19] = -5.34398847814249;
   fWeightMatrix0to1[3][19] = 0.398030255946729;
   fWeightMatrix0to1[4][19] = 3.49776196060862;
   fWeightMatrix0to1[5][19] = -7.48019172353255;
   fWeightMatrix0to1[6][19] = 1.70858254914974;
   fWeightMatrix0to1[7][19] = -0.0744796968209746;
   fWeightMatrix0to1[8][19] = -4.17888129656274;
   fWeightMatrix0to1[9][19] = -4.08350827148936;
   fWeightMatrix0to1[10][19] = 4.5709653644826;
   fWeightMatrix0to1[11][19] = 0.152160194110535;
   fWeightMatrix0to1[12][19] = -1.88673618946592;
   fWeightMatrix0to1[13][19] = -0.255888634854123;
   fWeightMatrix0to1[14][19] = -4.04882743308934;
   fWeightMatrix0to1[15][19] = 4.35407276835527;
   fWeightMatrix0to1[16][19] = -0.261366300641541;
   fWeightMatrix0to1[17][19] = -2.70031964021926;
   fWeightMatrix0to1[18][19] = 1.67636657621541;
   fWeightMatrix0to1[19][19] = 0.387824772060596;
   fWeightMatrix0to1[0][20] = 2.17589113776268;
   fWeightMatrix0to1[1][20] = 31.7739891161123;
   fWeightMatrix0to1[2][20] = -14.0161435760361;
   fWeightMatrix0to1[3][20] = -3.77695994805531;
   fWeightMatrix0to1[4][20] = 5.94031038283471;
   fWeightMatrix0to1[5][20] = -38.2879443475098;
   fWeightMatrix0to1[6][20] = 0.549430799515076;
   fWeightMatrix0to1[7][20] = 1.06213595432769;
   fWeightMatrix0to1[8][20] = -30.4300227957173;
   fWeightMatrix0to1[9][20] = -16.9944948207679;
   fWeightMatrix0to1[10][20] = 6.50616725017487;
   fWeightMatrix0to1[11][20] = 2.1745914447767;
   fWeightMatrix0to1[12][20] = 8.11272427062079;
   fWeightMatrix0to1[13][20] = -1.28980841878706;
   fWeightMatrix0to1[14][20] = 3.88436629343654;
   fWeightMatrix0to1[15][20] = 8.42728933019709;
   fWeightMatrix0to1[16][20] = 14.5589024555295;
   fWeightMatrix0to1[17][20] = -9.07145378336267;
   fWeightMatrix0to1[18][20] = -0.346253080515334;
   fWeightMatrix0to1[19][20] = -21.0585432478242;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -3.33633987758763;
   fWeightMatrix1to2[1][0] = -0.221338580407386;
   fWeightMatrix1to2[2][0] = 0.9087653903195;
   fWeightMatrix1to2[3][0] = -1.71256952754669;
   fWeightMatrix1to2[4][0] = 1.27283818812798;
   fWeightMatrix1to2[5][0] = 0.202941646022781;
   fWeightMatrix1to2[6][0] = 1.30625703879761;
   fWeightMatrix1to2[7][0] = 1.08137294435665;
   fWeightMatrix1to2[8][0] = -0.410936762498773;
   fWeightMatrix1to2[9][0] = 2.58299863019089;
   fWeightMatrix1to2[10][0] = -3.41234142643131;
   fWeightMatrix1to2[11][0] = -0.733098123008111;
   fWeightMatrix1to2[12][0] = -1.06778386664657;
   fWeightMatrix1to2[13][0] = -3.66960995431739;
   fWeightMatrix1to2[14][0] = 0.4307914765996;
   fWeightMatrix1to2[15][0] = -1.39790616362273;
   fWeightMatrix1to2[16][0] = 0.378041692775323;
   fWeightMatrix1to2[17][0] = -0.119779643387952;
   fWeightMatrix1to2[18][0] = 0.561595521702485;
   fWeightMatrix1to2[19][0] = 1.47735355228007;
   fWeightMatrix1to2[20][0] = -2.48840677016279;
   fWeightMatrix1to2[21][0] = -0.515079838233812;
   fWeightMatrix1to2[22][0] = 0.0489624223081866;
   fWeightMatrix1to2[23][0] = -2.25716604710514;
   fWeightMatrix1to2[24][0] = 0.260653982983498;
   fWeightMatrix1to2[0][1] = -2.33123941324465;
   fWeightMatrix1to2[1][1] = 5.71555510718076;
   fWeightMatrix1to2[2][1] = 0.194142023405093;
   fWeightMatrix1to2[3][1] = -5.04110124329824;
   fWeightMatrix1to2[4][1] = -4.0943566513182;
   fWeightMatrix1to2[5][1] = 1.76883446624592;
   fWeightMatrix1to2[6][1] = -1.37464726471564;
   fWeightMatrix1to2[7][1] = 0.12356013881533;
   fWeightMatrix1to2[8][1] = 4.02625326114222;
   fWeightMatrix1to2[9][1] = -2.60176014628704;
   fWeightMatrix1to2[10][1] = -3.71353429690295;
   fWeightMatrix1to2[11][1] = 1.66172422653204;
   fWeightMatrix1to2[12][1] = -2.39701438496612;
   fWeightMatrix1to2[13][1] = 2.17421659783009;
   fWeightMatrix1to2[14][1] = -3.63120510238233;
   fWeightMatrix1to2[15][1] = 0.760465211691852;
   fWeightMatrix1to2[16][1] = -2.50022709442309;
   fWeightMatrix1to2[17][1] = -0.617251644272116;
   fWeightMatrix1to2[18][1] = -2.74799828891722;
   fWeightMatrix1to2[19][1] = -2.76626942393299;
   fWeightMatrix1to2[20][1] = -2.57316131043637;
   fWeightMatrix1to2[21][1] = 1.89074195422514;
   fWeightMatrix1to2[22][1] = -4.72404782625778;
   fWeightMatrix1to2[23][1] = -2.89377267841806;
   fWeightMatrix1to2[24][1] = 0.218506991302867;
   fWeightMatrix1to2[0][2] = 1.25362731978373;
   fWeightMatrix1to2[1][2] = 4.53920392049071;
   fWeightMatrix1to2[2][2] = -2.62519509070158;
   fWeightMatrix1to2[3][2] = 3.51570266242288;
   fWeightMatrix1to2[4][2] = 1.48364430751064;
   fWeightMatrix1to2[5][2] = -3.64071656581842;
   fWeightMatrix1to2[6][2] = 0.514039668939104;
   fWeightMatrix1to2[7][2] = -4.19154321942026;
   fWeightMatrix1to2[8][2] = 3.20421444689423;
   fWeightMatrix1to2[9][2] = 3.05702209623523;
   fWeightMatrix1to2[10][2] = -2.59268309481499;
   fWeightMatrix1to2[11][2] = 0.67541430861014;
   fWeightMatrix1to2[12][2] = 2.65950125959032;
   fWeightMatrix1to2[13][2] = 2.16144237317925;
   fWeightMatrix1to2[14][2] = -2.24013250844746;
   fWeightMatrix1to2[15][2] = 0.836169118765122;
   fWeightMatrix1to2[16][2] = -0.61089820630342;
   fWeightMatrix1to2[17][2] = 1.43550227290516;
   fWeightMatrix1to2[18][2] = 7.43796622000617;
   fWeightMatrix1to2[19][2] = 2.71355043827563;
   fWeightMatrix1to2[20][2] = 0.89816688248097;
   fWeightMatrix1to2[21][2] = -0.259669730242804;
   fWeightMatrix1to2[22][2] = -1.36352073994505;
   fWeightMatrix1to2[23][2] = -2.96184047034099;
   fWeightMatrix1to2[24][2] = -1.01933087987632;
   fWeightMatrix1to2[0][3] = 0.311985803913475;
   fWeightMatrix1to2[1][3] = 0.356040552154086;
   fWeightMatrix1to2[2][3] = -0.768094645992033;
   fWeightMatrix1to2[3][3] = 0.075445585074539;
   fWeightMatrix1to2[4][3] = 0.198585364045292;
   fWeightMatrix1to2[5][3] = -0.364071724267739;
   fWeightMatrix1to2[6][3] = -0.0154722314385554;
   fWeightMatrix1to2[7][3] = 0.0950604057553082;
   fWeightMatrix1to2[8][3] = -0.091401134758937;
   fWeightMatrix1to2[9][3] = 1.39834209604806;
   fWeightMatrix1to2[10][3] = 0.177658207145578;
   fWeightMatrix1to2[11][3] = 0.863460340054864;
   fWeightMatrix1to2[12][3] = 0.335195766169785;
   fWeightMatrix1to2[13][3] = 0.329272095566792;
   fWeightMatrix1to2[14][3] = -1.87157048092897;
   fWeightMatrix1to2[15][3] = 0.528344966395841;
   fWeightMatrix1to2[16][3] = 0.733220812748764;
   fWeightMatrix1to2[17][3] = 0.0941045492502237;
   fWeightMatrix1to2[18][3] = 0.137906627283453;
   fWeightMatrix1to2[19][3] = -0.724028597115811;
   fWeightMatrix1to2[20][3] = 0.0889699227163199;
   fWeightMatrix1to2[21][3] = 0.0698000125806573;
   fWeightMatrix1to2[22][3] = 1.25319766249214;
   fWeightMatrix1to2[23][3] = 0.573253964911686;
   fWeightMatrix1to2[24][3] = 1.23244362432836;
   fWeightMatrix1to2[0][4] = 1.16421915943594;
   fWeightMatrix1to2[1][4] = -3.4465943442243;
   fWeightMatrix1to2[2][4] = 1.60948530260462;
   fWeightMatrix1to2[3][4] = 1.05369661076069;
   fWeightMatrix1to2[4][4] = 0.186651013009056;
   fWeightMatrix1to2[5][4] = 3.78005286943935;
   fWeightMatrix1to2[6][4] = 4.19110295747285;
   fWeightMatrix1to2[7][4] = 5.02762875932896;
   fWeightMatrix1to2[8][4] = -1.77236650701971;
   fWeightMatrix1to2[9][4] = -4.4560564782306;
   fWeightMatrix1to2[10][4] = -1.53343857539926;
   fWeightMatrix1to2[11][4] = 0.294028037705601;
   fWeightMatrix1to2[12][4] = 0.452332561773934;
   fWeightMatrix1to2[13][4] = 2.9780174447594;
   fWeightMatrix1to2[14][4] = 0.116867467223614;
   fWeightMatrix1to2[15][4] = -1.18959085771217;
   fWeightMatrix1to2[16][4] = -3.96059856294984;
   fWeightMatrix1to2[17][4] = -1.26781157043675;
   fWeightMatrix1to2[18][4] = -1.04578447357406;
   fWeightMatrix1to2[19][4] = -3.64384397714569;
   fWeightMatrix1to2[20][4] = -2.26704782672695;
   fWeightMatrix1to2[21][4] = -0.00615324535398083;
   fWeightMatrix1to2[22][4] = 1.2006961585706;
   fWeightMatrix1to2[23][4] = -1.59250722411564;
   fWeightMatrix1to2[24][4] = 0.735248811556396;
   fWeightMatrix1to2[0][5] = -0.264680083613077;
   fWeightMatrix1to2[1][5] = 1.50138167436827;
   fWeightMatrix1to2[2][5] = -2.27572206772945;
   fWeightMatrix1to2[3][5] = 2.35598895717429;
   fWeightMatrix1to2[4][5] = 5.98910879480465;
   fWeightMatrix1to2[5][5] = -6.63121322631842;
   fWeightMatrix1to2[6][5] = -5.62314371965677;
   fWeightMatrix1to2[7][5] = 0.801195965136116;
   fWeightMatrix1to2[8][5] = 0.662194167838516;
   fWeightMatrix1to2[9][5] = -0.951427714118429;
   fWeightMatrix1to2[10][5] = -1.40031489187444;
   fWeightMatrix1to2[11][5] = -0.992420862234737;
   fWeightMatrix1to2[12][5] = -2.29685965344694;
   fWeightMatrix1to2[13][5] = -2.66535170965777;
   fWeightMatrix1to2[14][5] = -1.22388178536043;
   fWeightMatrix1to2[15][5] = 2.05884347325122;
   fWeightMatrix1to2[16][5] = 0.0441000138379537;
   fWeightMatrix1to2[17][5] = 0.175481802023923;
   fWeightMatrix1to2[18][5] = 3.00269216720812;
   fWeightMatrix1to2[19][5] = -1.65155069257043;
   fWeightMatrix1to2[20][5] = -1.80242257463511;
   fWeightMatrix1to2[21][5] = 0.292777255440767;
   fWeightMatrix1to2[22][5] = -1.48989906475521;
   fWeightMatrix1to2[23][5] = -3.13571038282684;
   fWeightMatrix1to2[24][5] = -2.63367623039445;
   fWeightMatrix1to2[0][6] = 0.454745567474267;
   fWeightMatrix1to2[1][6] = -0.298687092072078;
   fWeightMatrix1to2[2][6] = -0.486805481176889;
   fWeightMatrix1to2[3][6] = 0.790129814029279;
   fWeightMatrix1to2[4][6] = 0.390528248716927;
   fWeightMatrix1to2[5][6] = 0.471648485294721;
   fWeightMatrix1to2[6][6] = -0.204600123598539;
   fWeightMatrix1to2[7][6] = -0.896521337900712;
   fWeightMatrix1to2[8][6] = 1.3388621411539;
   fWeightMatrix1to2[9][6] = -0.154911892782562;
   fWeightMatrix1to2[10][6] = 0.707721129930458;
   fWeightMatrix1to2[11][6] = 0.587279105519608;
   fWeightMatrix1to2[12][6] = -0.0139569783934404;
   fWeightMatrix1to2[13][6] = 0.136627158870036;
   fWeightMatrix1to2[14][6] = 0.35612600857521;
   fWeightMatrix1to2[15][6] = -2.53020856477452;
   fWeightMatrix1to2[16][6] = -1.04947695680544;
   fWeightMatrix1to2[17][6] = 7.31234699709307;
   fWeightMatrix1to2[18][6] = -0.921654340025923;
   fWeightMatrix1to2[19][6] = 4.07521265142131;
   fWeightMatrix1to2[20][6] = -4.10677674076255;
   fWeightMatrix1to2[21][6] = -0.390978205662766;
   fWeightMatrix1to2[22][6] = 0.313965950749579;
   fWeightMatrix1to2[23][6] = -0.207723018841523;
   fWeightMatrix1to2[24][6] = -1.62702905685394;
   fWeightMatrix1to2[0][7] = 1.39828480684406;
   fWeightMatrix1to2[1][7] = -1.38132556514412;
   fWeightMatrix1to2[2][7] = -3.11019840186454;
   fWeightMatrix1to2[3][7] = -3.50029635011005;
   fWeightMatrix1to2[4][7] = -2.98395341553511;
   fWeightMatrix1to2[5][7] = -0.424952816009258;
   fWeightMatrix1to2[6][7] = -1.04197876790985;
   fWeightMatrix1to2[7][7] = 2.61091509760604;
   fWeightMatrix1to2[8][7] = -4.80189964960085;
   fWeightMatrix1to2[9][7] = 0.460334188343523;
   fWeightMatrix1to2[10][7] = 0.0739537321319625;
   fWeightMatrix1to2[11][7] = -0.695654210056483;
   fWeightMatrix1to2[12][7] = -3.31500121118491;
   fWeightMatrix1to2[13][7] = -1.60786918610845;
   fWeightMatrix1to2[14][7] = -2.03807096446777;
   fWeightMatrix1to2[15][7] = -0.880789398289412;
   fWeightMatrix1to2[16][7] = 1.48664093736131;
   fWeightMatrix1to2[17][7] = -1.95456330884414;
   fWeightMatrix1to2[18][7] = -1.7256780473557;
   fWeightMatrix1to2[19][7] = -0.703418003282247;
   fWeightMatrix1to2[20][7] = 2.58598228543973;
   fWeightMatrix1to2[21][7] = -0.0873196830420783;
   fWeightMatrix1to2[22][7] = 0.337657058963148;
   fWeightMatrix1to2[23][7] = -0.962950379437217;
   fWeightMatrix1to2[24][7] = -1.00628973309237;
   fWeightMatrix1to2[0][8] = -0.387923950997454;
   fWeightMatrix1to2[1][8] = -0.932842711187614;
   fWeightMatrix1to2[2][8] = 0.608952158777545;
   fWeightMatrix1to2[3][8] = 0.586299064038142;
   fWeightMatrix1to2[4][8] = -3.16408776814163;
   fWeightMatrix1to2[5][8] = -4.77132868599781;
   fWeightMatrix1to2[6][8] = -7.96560487441699;
   fWeightMatrix1to2[7][8] = -0.414344409018757;
   fWeightMatrix1to2[8][8] = -5.16883660229904;
   fWeightMatrix1to2[9][8] = 0.941434494008152;
   fWeightMatrix1to2[10][8] = 2.3250532414684;
   fWeightMatrix1to2[11][8] = -2.75123319090182;
   fWeightMatrix1to2[12][8] = -2.19178417975112;
   fWeightMatrix1to2[13][8] = -0.521208292830461;
   fWeightMatrix1to2[14][8] = 0.688364946852116;
   fWeightMatrix1to2[15][8] = 0.878622147134188;
   fWeightMatrix1to2[16][8] = -4.05447609535055;
   fWeightMatrix1to2[17][8] = 1.53409111817155;
   fWeightMatrix1to2[18][8] = 2.41402238267485;
   fWeightMatrix1to2[19][8] = -0.00872276010051526;
   fWeightMatrix1to2[20][8] = -2.95047834015621;
   fWeightMatrix1to2[21][8] = -3.46024242381637;
   fWeightMatrix1to2[22][8] = -0.287146079614798;
   fWeightMatrix1to2[23][8] = -1.19948721422799;
   fWeightMatrix1to2[24][8] = -2.71135943703308;
   fWeightMatrix1to2[0][9] = -1.60079810974773;
   fWeightMatrix1to2[1][9] = -0.205761066450713;
   fWeightMatrix1to2[2][9] = 0.618590735086452;
   fWeightMatrix1to2[3][9] = 3.38082738819737;
   fWeightMatrix1to2[4][9] = -0.194184177374071;
   fWeightMatrix1to2[5][9] = -3.26101320823311;
   fWeightMatrix1to2[6][9] = -8.75336532900035;
   fWeightMatrix1to2[7][9] = -1.75460718881401;
   fWeightMatrix1to2[8][9] = -1.71964898317093;
   fWeightMatrix1to2[9][9] = -2.00712709940994;
   fWeightMatrix1to2[10][9] = 4.50423627507251;
   fWeightMatrix1to2[11][9] = -0.317015943874717;
   fWeightMatrix1to2[12][9] = -4.79695342919586;
   fWeightMatrix1to2[13][9] = 2.38597906531162;
   fWeightMatrix1to2[14][9] = -2.93584789672919;
   fWeightMatrix1to2[15][9] = 0.0888542016688147;
   fWeightMatrix1to2[16][9] = 2.63740111410516;
   fWeightMatrix1to2[17][9] = 0.537459943476017;
   fWeightMatrix1to2[18][9] = 3.91811672121213;
   fWeightMatrix1to2[19][9] = -1.21319244302741;
   fWeightMatrix1to2[20][9] = -4.44734347213207;
   fWeightMatrix1to2[21][9] = 0.537667054491563;
   fWeightMatrix1to2[22][9] = -0.299977718798882;
   fWeightMatrix1to2[23][9] = 0.0717143647643499;
   fWeightMatrix1to2[24][9] = -0.150517094987154;
   fWeightMatrix1to2[0][10] = -5.0685727962638;
   fWeightMatrix1to2[1][10] = 0.0171792403791209;
   fWeightMatrix1to2[2][10] = -0.566283957804728;
   fWeightMatrix1to2[3][10] = 0.91383513259734;
   fWeightMatrix1to2[4][10] = -0.521774059585118;
   fWeightMatrix1to2[5][10] = 0.464890788073185;
   fWeightMatrix1to2[6][10] = 0.572413457815542;
   fWeightMatrix1to2[7][10] = 0.161230626143343;
   fWeightMatrix1to2[8][10] = 0.535122633920162;
   fWeightMatrix1to2[9][10] = -3.22322355571626;
   fWeightMatrix1to2[10][10] = 0.195046773293578;
   fWeightMatrix1to2[11][10] = 0.144266191488038;
   fWeightMatrix1to2[12][10] = 0.133322305384504;
   fWeightMatrix1to2[13][10] = -0.558836652415411;
   fWeightMatrix1to2[14][10] = 2.47041728370192;
   fWeightMatrix1to2[15][10] = -0.107935517825197;
   fWeightMatrix1to2[16][10] = 0.423451254569029;
   fWeightMatrix1to2[17][10] = -3.94278815557613;
   fWeightMatrix1to2[18][10] = -2.20786898986662;
   fWeightMatrix1to2[19][10] = -2.83059825932973;
   fWeightMatrix1to2[20][10] = 2.34287176004375;
   fWeightMatrix1to2[21][10] = 0.176736048056086;
   fWeightMatrix1to2[22][10] = 0.0980600656030503;
   fWeightMatrix1to2[23][10] = 1.04937518899383;
   fWeightMatrix1to2[24][10] = -0.848053630436281;
   fWeightMatrix1to2[0][11] = 0.841388563884466;
   fWeightMatrix1to2[1][11] = -2.37671782585107;
   fWeightMatrix1to2[2][11] = 1.01395044575222;
   fWeightMatrix1to2[3][11] = -0.715802419961187;
   fWeightMatrix1to2[4][11] = 0.134623122638435;
   fWeightMatrix1to2[5][11] = 0.750053155006983;
   fWeightMatrix1to2[6][11] = 0.859744901369611;
   fWeightMatrix1to2[7][11] = 0.688114020003447;
   fWeightMatrix1to2[8][11] = -1.71785322742308;
   fWeightMatrix1to2[9][11] = -2.4596746365307;
   fWeightMatrix1to2[10][11] = -0.85813974788025;
   fWeightMatrix1to2[11][11] = -4.0079073784607;
   fWeightMatrix1to2[12][11] = -1.17610768172628;
   fWeightMatrix1to2[13][11] = -1.6575836998801;
   fWeightMatrix1to2[14][11] = 4.30294456490661;
   fWeightMatrix1to2[15][11] = -0.00353712125460785;
   fWeightMatrix1to2[16][11] = 0.135150294071929;
   fWeightMatrix1to2[17][11] = 1.81925285312768;
   fWeightMatrix1to2[18][11] = 0.459760780018252;
   fWeightMatrix1to2[19][11] = 1.33066634684143;
   fWeightMatrix1to2[20][11] = -0.786096665164232;
   fWeightMatrix1to2[21][11] = -0.430517235746778;
   fWeightMatrix1to2[22][11] = -2.54619313491874;
   fWeightMatrix1to2[23][11] = -1.34302009529641;
   fWeightMatrix1to2[24][11] = -1.50894704959329;
   fWeightMatrix1to2[0][12] = -0.0669248631588838;
   fWeightMatrix1to2[1][12] = 2.49702548708568;
   fWeightMatrix1to2[2][12] = -3.37515144002692;
   fWeightMatrix1to2[3][12] = -0.263987067923177;
   fWeightMatrix1to2[4][12] = -0.109053922884003;
   fWeightMatrix1to2[5][12] = 1.90498801191823;
   fWeightMatrix1to2[6][12] = 0.770317102412864;
   fWeightMatrix1to2[7][12] = 1.18826771023726;
   fWeightMatrix1to2[8][12] = 2.54799496757496;
   fWeightMatrix1to2[9][12] = 1.79749277382425;
   fWeightMatrix1to2[10][12] = -1.78150759526431;
   fWeightMatrix1to2[11][12] = -1.33923956389131;
   fWeightMatrix1to2[12][12] = 0.164151692814874;
   fWeightMatrix1to2[13][12] = -2.16246492362503;
   fWeightMatrix1to2[14][12] = 1.10503945194854;
   fWeightMatrix1to2[15][12] = 1.44565842100571;
   fWeightMatrix1to2[16][12] = -1.34434948202102;
   fWeightMatrix1to2[17][12] = 4.12062123159318;
   fWeightMatrix1to2[18][12] = -2.06284217229466;
   fWeightMatrix1to2[19][12] = 0.341642486629642;
   fWeightMatrix1to2[20][12] = -2.42582056335243;
   fWeightMatrix1to2[21][12] = 1.26505646561263;
   fWeightMatrix1to2[22][12] = -4.76390506553961;
   fWeightMatrix1to2[23][12] = 1.39016728667975;
   fWeightMatrix1to2[24][12] = -0.0945621815971539;
   fWeightMatrix1to2[0][13] = 0.256415478613804;
   fWeightMatrix1to2[1][13] = 1.56870623292109;
   fWeightMatrix1to2[2][13] = 1.50740013483097;
   fWeightMatrix1to2[3][13] = -1.34965952006978;
   fWeightMatrix1to2[4][13] = -0.571668329874217;
   fWeightMatrix1to2[5][13] = -0.0976300791494095;
   fWeightMatrix1to2[6][13] = 1.04458293791634;
   fWeightMatrix1to2[7][13] = 1.00503638726332;
   fWeightMatrix1to2[8][13] = 1.4046685252621;
   fWeightMatrix1to2[9][13] = 2.03103491116893;
   fWeightMatrix1to2[10][13] = -0.261992033395245;
   fWeightMatrix1to2[11][13] = 0.879810618389485;
   fWeightMatrix1to2[12][13] = -0.124361624369127;
   fWeightMatrix1to2[13][13] = -1.35054738532698;
   fWeightMatrix1to2[14][13] = 1.2831131027991;
   fWeightMatrix1to2[15][13] = 0.757601505282314;
   fWeightMatrix1to2[16][13] = 0.851054745417843;
   fWeightMatrix1to2[17][13] = 1.36223191865859;
   fWeightMatrix1to2[18][13] = -0.878460408964949;
   fWeightMatrix1to2[19][13] = 1.21642395894407;
   fWeightMatrix1to2[20][13] = 0.208062708893862;
   fWeightMatrix1to2[21][13] = -1.130956322138;
   fWeightMatrix1to2[22][13] = -0.614929513564916;
   fWeightMatrix1to2[23][13] = -1.28321491488783;
   fWeightMatrix1to2[24][13] = -1.25823586281324;
   fWeightMatrix1to2[0][14] = -4.23287904988123;
   fWeightMatrix1to2[1][14] = -0.281626788263915;
   fWeightMatrix1to2[2][14] = 0.305725537005707;
   fWeightMatrix1to2[3][14] = 0.0763674059005269;
   fWeightMatrix1to2[4][14] = 0.0114827334404758;
   fWeightMatrix1to2[5][14] = 0.407614990594338;
   fWeightMatrix1to2[6][14] = -0.417554033949493;
   fWeightMatrix1to2[7][14] = -0.244855187768062;
   fWeightMatrix1to2[8][14] = -0.357155879490459;
   fWeightMatrix1to2[9][14] = 0.41167672349501;
   fWeightMatrix1to2[10][14] = 0.375180609192787;
   fWeightMatrix1to2[11][14] = 0.499040102107871;
   fWeightMatrix1to2[12][14] = 0.178369321847597;
   fWeightMatrix1to2[13][14] = 0.32068071565472;
   fWeightMatrix1to2[14][14] = -0.514035299078363;
   fWeightMatrix1to2[15][14] = 0.170706248617953;
   fWeightMatrix1to2[16][14] = -1.30652735889349;
   fWeightMatrix1to2[17][14] = -5.38849414442044;
   fWeightMatrix1to2[18][14] = 0.104729663888811;
   fWeightMatrix1to2[19][14] = -6.89588129573388;
   fWeightMatrix1to2[20][14] = 3.40652158246929;
   fWeightMatrix1to2[21][14] = -1.07357946006148;
   fWeightMatrix1to2[22][14] = -0.142471332503346;
   fWeightMatrix1to2[23][14] = -0.852434798900076;
   fWeightMatrix1to2[24][14] = -0.24245730756045;
   fWeightMatrix1to2[0][15] = 0.416040213116028;
   fWeightMatrix1to2[1][15] = -1.6172883362809;
   fWeightMatrix1to2[2][15] = 1.96510144984203;
   fWeightMatrix1to2[3][15] = -1.78718939155086;
   fWeightMatrix1to2[4][15] = -2.39368393309844;
   fWeightMatrix1to2[5][15] = 0.357207400424776;
   fWeightMatrix1to2[6][15] = 0.564555467821625;
   fWeightMatrix1to2[7][15] = 3.30702859351779;
   fWeightMatrix1to2[8][15] = -1.03269205158793;
   fWeightMatrix1to2[9][15] = -5.86769962523951;
   fWeightMatrix1to2[10][15] = -0.499342897932652;
   fWeightMatrix1to2[11][15] = -0.212762267947417;
   fWeightMatrix1to2[12][15] = -2.43836638798236;
   fWeightMatrix1to2[13][15] = -2.00546810002084;
   fWeightMatrix1to2[14][15] = -0.992176079068589;
   fWeightMatrix1to2[15][15] = -0.0310037714269449;
   fWeightMatrix1to2[16][15] = -4.83201487184043;
   fWeightMatrix1to2[17][15] = 1.73427849981249;
   fWeightMatrix1to2[18][15] = 0.407181656781903;
   fWeightMatrix1to2[19][15] = -3.10285078887276;
   fWeightMatrix1to2[20][15] = -4.80663643502045;
   fWeightMatrix1to2[21][15] = -1.60987752785543;
   fWeightMatrix1to2[22][15] = 0.881191695490781;
   fWeightMatrix1to2[23][15] = -1.05713615548895;
   fWeightMatrix1to2[24][15] = -1.17272497886673;
   fWeightMatrix1to2[0][16] = -2.47503664583296;
   fWeightMatrix1to2[1][16] = 8.56697607851745;
   fWeightMatrix1to2[2][16] = 0.548762656128698;
   fWeightMatrix1to2[3][16] = -5.0446033751961;
   fWeightMatrix1to2[4][16] = 5.9605594055846;
   fWeightMatrix1to2[5][16] = -2.34332114079999;
   fWeightMatrix1to2[6][16] = -3.34271636798249;
   fWeightMatrix1to2[7][16] = -0.935142083497193;
   fWeightMatrix1to2[8][16] = 5.48474117036562;
   fWeightMatrix1to2[9][16] = 1.55106161238275;
   fWeightMatrix1to2[10][16] = -3.65702506003864;
   fWeightMatrix1to2[11][16] = 1.94154432652976;
   fWeightMatrix1to2[12][16] = 4.82294530428611;
   fWeightMatrix1to2[13][16] = -0.0586346161192163;
   fWeightMatrix1to2[14][16] = -8.14075628430749;
   fWeightMatrix1to2[15][16] = 2.4382895073424;
   fWeightMatrix1to2[16][16] = 0.658605430248325;
   fWeightMatrix1to2[17][16] = -0.600890222950878;
   fWeightMatrix1to2[18][16] = -3.84221518924235;
   fWeightMatrix1to2[19][16] = -2.66816395317796;
   fWeightMatrix1to2[20][16] = -2.56556044354302;
   fWeightMatrix1to2[21][16] = -1.53454800171443;
   fWeightMatrix1to2[22][16] = -8.77163550398148;
   fWeightMatrix1to2[23][16] = -5.6729936215348;
   fWeightMatrix1to2[24][16] = -5.0398765281741;
   fWeightMatrix1to2[0][17] = 1.57550594186086;
   fWeightMatrix1to2[1][17] = 0.796102575506963;
   fWeightMatrix1to2[2][17] = -1.05992927344328;
   fWeightMatrix1to2[3][17] = -0.447024840467158;
   fWeightMatrix1to2[4][17] = 0.215196759540949;
   fWeightMatrix1to2[5][17] = -0.672388166690569;
   fWeightMatrix1to2[6][17] = -0.193570029183326;
   fWeightMatrix1to2[7][17] = -4.50550457161849;
   fWeightMatrix1to2[8][17] = 1.72468563112601;
   fWeightMatrix1to2[9][17] = -2.51697689813751;
   fWeightMatrix1to2[10][17] = 1.84726930221224;
   fWeightMatrix1to2[11][17] = -0.938619620969239;
   fWeightMatrix1to2[12][17] = 1.18658123123665;
   fWeightMatrix1to2[13][17] = 0.596786575341291;
   fWeightMatrix1to2[14][17] = 0.550535008078899;
   fWeightMatrix1to2[15][17] = 1.31063738195266;
   fWeightMatrix1to2[16][17] = -0.498684161027947;
   fWeightMatrix1to2[17][17] = -0.470841443454832;
   fWeightMatrix1to2[18][17] = 2.27034099218452;
   fWeightMatrix1to2[19][17] = -2.074411052565;
   fWeightMatrix1to2[20][17] = 1.4409887494469;
   fWeightMatrix1to2[21][17] = 3.46661933076272;
   fWeightMatrix1to2[22][17] = 0.755867348576456;
   fWeightMatrix1to2[23][17] = 0.0125843736762556;
   fWeightMatrix1to2[24][17] = -0.690609573247518;
   fWeightMatrix1to2[0][18] = -0.184308390219894;
   fWeightMatrix1to2[1][18] = 3.44282031608778;
   fWeightMatrix1to2[2][18] = 1.39993561292632;
   fWeightMatrix1to2[3][18] = 2.36755896907139;
   fWeightMatrix1to2[4][18] = -1.95116720810168;
   fWeightMatrix1to2[5][18] = -5.49993268890474;
   fWeightMatrix1to2[6][18] = -3.52452430293026;
   fWeightMatrix1to2[7][18] = -5.05991901172345;
   fWeightMatrix1to2[8][18] = 3.08590609350731;
   fWeightMatrix1to2[9][18] = 2.9434368702654;
   fWeightMatrix1to2[10][18] = 2.98198793487845;
   fWeightMatrix1to2[11][18] = -0.115589688853523;
   fWeightMatrix1to2[12][18] = -1.33074982606569;
   fWeightMatrix1to2[13][18] = -2.10849913329446;
   fWeightMatrix1to2[14][18] = -4.96995153415568;
   fWeightMatrix1to2[15][18] = -0.832667012364697;
   fWeightMatrix1to2[16][18] = -1.04422034532013;
   fWeightMatrix1to2[17][18] = 1.08825156437871;
   fWeightMatrix1to2[18][18] = 2.45918651267916;
   fWeightMatrix1to2[19][18] = 0.53965637688986;
   fWeightMatrix1to2[20][18] = 0.273795582444468;
   fWeightMatrix1to2[21][18] = 2.68516153493382;
   fWeightMatrix1to2[22][18] = -1.38925855818095;
   fWeightMatrix1to2[23][18] = 0.203444093110567;
   fWeightMatrix1to2[24][18] = 0.419559091402511;
   fWeightMatrix1to2[0][19] = -0.567901557520096;
   fWeightMatrix1to2[1][19] = -5.46787295072731;
   fWeightMatrix1to2[2][19] = -1.85745470871084;
   fWeightMatrix1to2[3][19] = 1.2962645144893;
   fWeightMatrix1to2[4][19] = 3.26515636834414;
   fWeightMatrix1to2[5][19] = -3.33209821852471;
   fWeightMatrix1to2[6][19] = 1.21940551139367;
   fWeightMatrix1to2[7][19] = 1.26203533127694;
   fWeightMatrix1to2[8][19] = -1.46106505525799;
   fWeightMatrix1to2[9][19] = 0.35597426228531;
   fWeightMatrix1to2[10][19] = -1.26897607299544;
   fWeightMatrix1to2[11][19] = 2.63391284299907;
   fWeightMatrix1to2[12][19] = 0.449957248485801;
   fWeightMatrix1to2[13][19] = -0.233933677879256;
   fWeightMatrix1to2[14][19] = 1.62254998807328;
   fWeightMatrix1to2[15][19] = 2.47455786938338;
   fWeightMatrix1to2[16][19] = -0.454411467555729;
   fWeightMatrix1to2[17][19] = 0.704603783477812;
   fWeightMatrix1to2[18][19] = 3.16556589599817;
   fWeightMatrix1to2[19][19] = 0.517143275519905;
   fWeightMatrix1to2[20][19] = -0.650265332908594;
   fWeightMatrix1to2[21][19] = -2.88765436364075;
   fWeightMatrix1to2[22][19] = 7.15480381430447;
   fWeightMatrix1to2[23][19] = -1.25064894156338;
   fWeightMatrix1to2[24][19] = -1.40996721263308;
   fWeightMatrix1to2[0][20] = 0.511829897622222;
   fWeightMatrix1to2[1][20] = -1.85920799243318;
   fWeightMatrix1to2[2][20] = -0.109195519572393;
   fWeightMatrix1to2[3][20] = -0.552324874185563;
   fWeightMatrix1to2[4][20] = -3.34441120467763;
   fWeightMatrix1to2[5][20] = 0.34099248576566;
   fWeightMatrix1to2[6][20] = -3.51938005043965;
   fWeightMatrix1to2[7][20] = 1.7785178254591;
   fWeightMatrix1to2[8][20] = -1.76695093193937;
   fWeightMatrix1to2[9][20] = -0.228283567972343;
   fWeightMatrix1to2[10][20] = -1.55589294214645;
   fWeightMatrix1to2[11][20] = -1.91908112127317;
   fWeightMatrix1to2[12][20] = 0.0694809684854161;
   fWeightMatrix1to2[13][20] = 0.519147732298703;
   fWeightMatrix1to2[14][20] = -2.81948921292206;
   fWeightMatrix1to2[15][20] = 0.71365995595863;
   fWeightMatrix1to2[16][20] = -0.153060981446101;
   fWeightMatrix1to2[17][20] = -0.724802518528578;
   fWeightMatrix1to2[18][20] = -2.67653771042243;
   fWeightMatrix1to2[19][20] = 1.47302382529949;
   fWeightMatrix1to2[20][20] = 2.30368277754365;
   fWeightMatrix1to2[21][20] = -2.17646054503209;
   fWeightMatrix1to2[22][20] = -0.456699198178318;
   fWeightMatrix1to2[23][20] = 1.07038188860221;
   fWeightMatrix1to2[24][20] = -0.0742107030128633;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.438232519453038;
   fWeightMatrix2to3[1][0] = -0.56427310604419;
   fWeightMatrix2to3[2][0] = -1.55580165645542;
   fWeightMatrix2to3[0][1] = 1.1771034206458;
   fWeightMatrix2to3[1][1] = 1.7370225506244;
   fWeightMatrix2to3[2][1] = 0.935357121094651;
   fWeightMatrix2to3[0][2] = 0.570015201606649;
   fWeightMatrix2to3[1][2] = -0.0275320542023086;
   fWeightMatrix2to3[2][2] = 0.0929823912392202;
   fWeightMatrix2to3[0][3] = -0.462239573238169;
   fWeightMatrix2to3[1][3] = 1.58270581333421;
   fWeightMatrix2to3[2][3] = 4.81593396298608;
   fWeightMatrix2to3[0][4] = -1.0204379597334;
   fWeightMatrix2to3[1][4] = 3.80233810361984;
   fWeightMatrix2to3[2][4] = 1.10959652967074;
   fWeightMatrix2to3[0][5] = -3.63824663437504;
   fWeightMatrix2to3[1][5] = 2.1207696459099;
   fWeightMatrix2to3[2][5] = 1.00674122352707;
   fWeightMatrix2to3[0][6] = -4.18507175480859;
   fWeightMatrix2to3[1][6] = 4.2255872987355;
   fWeightMatrix2to3[2][6] = 1.23093984842508;
   fWeightMatrix2to3[0][7] = 2.02725042647573;
   fWeightMatrix2to3[1][7] = -1.01080331292058;
   fWeightMatrix2to3[2][7] = -0.12675567455433;
   fWeightMatrix2to3[0][8] = 2.5622322432479;
   fWeightMatrix2to3[1][8] = 2.58211440379866;
   fWeightMatrix2to3[2][8] = 0.597111850693263;
   fWeightMatrix2to3[0][9] = -1.31680276760905;
   fWeightMatrix2to3[1][9] = 0.990090963469224;
   fWeightMatrix2to3[2][9] = 1.57225124819666;
   fWeightMatrix2to3[0][10] = -0.376950098627653;
   fWeightMatrix2to3[1][10] = -0.361073375592902;
   fWeightMatrix2to3[2][10] = -1.55893628196408;
   fWeightMatrix2to3[0][11] = -1.14883731675307;
   fWeightMatrix2to3[1][11] = -1.69827149975875;
   fWeightMatrix2to3[2][11] = 1.23513652248317;
   fWeightMatrix2to3[0][12] = 2.12613204017576;
   fWeightMatrix2to3[1][12] = -0.225438091630225;
   fWeightMatrix2to3[2][12] = 3.67635597575322;
   fWeightMatrix2to3[0][13] = -0.693413807115824;
   fWeightMatrix2to3[1][13] = -0.483934293038682;
   fWeightMatrix2to3[2][13] = -2.92757169943013;
   fWeightMatrix2to3[0][14] = 1.14638442677573;
   fWeightMatrix2to3[1][14] = 4.91398007419936;
   fWeightMatrix2to3[2][14] = 1.3677631491761;
   fWeightMatrix2to3[0][15] = 1.0211164391847;
   fWeightMatrix2to3[1][15] = 1.92848274221752;
   fWeightMatrix2to3[2][15] = 0.872700732659985;
   fWeightMatrix2to3[0][16] = -0.34991742630262;
   fWeightMatrix2to3[1][16] = 2.59332320340236;
   fWeightMatrix2to3[2][16] = 1.06809607171755;
   fWeightMatrix2to3[0][17] = -0.0351620802504236;
   fWeightMatrix2to3[1][17] = 0.771471364698557;
   fWeightMatrix2to3[2][17] = 1.16945181679387;
   fWeightMatrix2to3[0][18] = -3.93425273735416;
   fWeightMatrix2to3[1][18] = -0.445708759733065;
   fWeightMatrix2to3[2][18] = -0.977455348660624;
   fWeightMatrix2to3[0][19] = -1.70019713381246;
   fWeightMatrix2to3[1][19] = -0.868293324318406;
   fWeightMatrix2to3[2][19] = -1.94261011819373;
   fWeightMatrix2to3[0][20] = -2.74984118474711;
   fWeightMatrix2to3[1][20] = -0.835755237355927;
   fWeightMatrix2to3[2][20] = -2.02217524184957;
   fWeightMatrix2to3[0][21] = 3.22927156383277;
   fWeightMatrix2to3[1][21] = -0.921069567265832;
   fWeightMatrix2to3[2][21] = 0.732907027002759;
   fWeightMatrix2to3[0][22] = 2.99624794698034;
   fWeightMatrix2to3[1][22] = 4.48346807881969;
   fWeightMatrix2to3[2][22] = 2.75359342599134;
   fWeightMatrix2to3[0][23] = -0.876944749208626;
   fWeightMatrix2to3[1][23] = -2.55555747833525;
   fWeightMatrix2to3[2][23] = -1.39771990929583;
   fWeightMatrix2to3[0][24] = -0.542085767088371;
   fWeightMatrix2to3[1][24] = -3.92206307144279;
   fWeightMatrix2to3[2][24] = -1.61874627201954;
   fWeightMatrix2to3[0][25] = 1.187341385721;
   fWeightMatrix2to3[1][25] = -1.13414084230718;
   fWeightMatrix2to3[2][25] = -3.60016685504107;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 2.2468426252017;
   fWeightMatrix3to4[0][1] = -7.85480912428217;
   fWeightMatrix3to4[0][2] = -7.27898307919937;
   fWeightMatrix3to4[0][3] = 5.12414018799295;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 61.6185760498;
   fMax_1[0][0] = 1363.18237305;
   fMin_1[1][0] = 35.7156524658;
   fMax_1[1][0] = 5135.92919922;
   fMin_1[2][0] = 35.7156524658;
   fMax_1[2][0] = 5135.92919922;
   fMin_1[0][1] = 18.228761673;
   fMax_1[0][1] = 1240.69482422;
   fMin_1[1][1] = 15.6709527969;
   fMax_1[1][1] = 4321.85888672;
   fMin_1[2][1] = 15.6709527969;
   fMax_1[2][1] = 4321.85888672;
   fMin_1[0][2] = 60.0693969727;
   fMax_1[0][2] = 1425.15393066;
   fMin_1[1][2] = 60.0363311768;
   fMax_1[1][2] = 2697.76367188;
   fMin_1[2][2] = 60.0363311768;
   fMax_1[2][2] = 2697.76367188;
   fMin_1[0][3] = 6.86645507812e-05;
   fMax_1[0][3] = 743.698242188;
   fMin_1[1][3] = 1.52587890625e-05;
   fMax_1[1][3] = 1557.57641602;
   fMin_1[2][3] = 1.52587890625e-05;
   fMax_1[2][3] = 1557.57641602;
   fMin_1[0][4] = 0.395948380232;
   fMax_1[0][4] = 4.98344898224;
   fMin_1[1][4] = 0.372943520546;
   fMax_1[1][4] = 5.66675138474;
   fMin_1[2][4] = 0.372943520546;
   fMax_1[2][4] = 5.66675138474;
   fMin_1[0][5] = 32.6004180908;
   fMax_1[0][5] = 1090.74365234;
   fMin_1[1][5] = 30.6295623779;
   fMax_1[1][5] = 2559.47729492;
   fMin_1[2][5] = 30.6295623779;
   fMax_1[2][5] = 2559.47729492;
   fMin_1[0][6] = -567.190795898;
   fMax_1[0][6] = 730.290893555;
   fMin_1[1][6] = -1010.5993042;
   fMax_1[1][6] = 1398.72265625;
   fMin_1[2][6] = -1010.5993042;
   fMax_1[2][6] = 1398.72265625;
   fMin_1[0][7] = 0.0119671234861;
   fMax_1[0][7] = 7.31500291824;
   fMin_1[1][7] = 0.00573204737157;
   fMax_1[1][7] = 8.96139144897;
   fMin_1[2][7] = 0.00573204737157;
   fMax_1[2][7] = 8.96139144897;
   fMin_1[0][8] = 60.0203704834;
   fMax_1[0][8] = 1271.83166504;
   fMin_1[1][8] = 60.0203704834;
   fMax_1[1][8] = 1431.1965332;
   fMin_1[2][8] = 60.0203704834;
   fMax_1[2][8] = 1431.1965332;
   fMin_1[0][9] = -755.58782959;
   fMax_1[0][9] = 674.663696289;
   fMin_1[1][9] = -773.499450684;
   fMax_1[1][9] = 1060.76464844;
   fMin_1[2][9] = -773.499450684;
   fMax_1[2][9] = 1060.76464844;
   fMin_1[0][10] = 0.500055372715;
   fMax_1[0][10] = 5.409948349;
   fMin_1[1][10] = 0.500000238419;
   fMax_1[1][10] = 5.58469629288;
   fMin_1[2][10] = 0.500000238419;
   fMax_1[2][10] = 5.58469629288;
   fMin_1[0][11] = 31.344997406;
   fMax_1[0][11] = 1343.60876465;
   fMin_1[1][11] = 31.0787239075;
   fMax_1[1][11] = 1935.83288574;
   fMin_1[2][11] = 31.0787239075;
   fMax_1[2][11] = 1935.83288574;
   fMin_1[0][12] = -791.472106934;
   fMax_1[0][12] = 728.864807129;
   fMin_1[1][12] = -809.493469238;
   fMax_1[1][12] = 1498.68908691;
   fMin_1[2][12] = -809.493469238;
   fMax_1[2][12] = 1498.68908691;
   fMin_1[0][13] = 0.0084324311465;
   fMax_1[0][13] = 8.69594860077;
   fMin_1[1][13] = 0.00712582096457;
   fMax_1[1][13] = 9.17821788788;
   fMin_1[2][13] = 0.00712582096457;
   fMax_1[2][13] = 9.17821788788;
   fMin_1[0][14] = -3.14157629013;
   fMax_1[0][14] = 3.14157986641;
   fMin_1[1][14] = -3.1415822506;
   fMax_1[1][14] = 3.14159250259;
   fMin_1[2][14] = -3.1415822506;
   fMax_1[2][14] = 3.14159250259;
   fMin_1[0][15] = 31.2111606598;
   fMax_1[0][15] = 1198.12304688;
   fMin_1[1][15] = 31.4733543396;
   fMax_1[1][15] = 1386.0456543;
   fMin_1[2][15] = 31.2111606598;
   fMax_1[2][15] = 1386.0456543;
   fMin_1[0][16] = -695.302062988;
   fMax_1[0][16] = 722.291870117;
   fMin_1[1][16] = -859.980834961;
   fMax_1[1][16] = 1050.97570801;
   fMin_1[2][16] = -859.980834961;
   fMax_1[2][16] = 1050.97570801;
   fMin_1[0][17] = -3.14157342911;
   fMax_1[0][17] = 3.14159154892;
   fMin_1[1][17] = -3.14158701897;
   fMax_1[1][17] = 3.14159178734;
   fMin_1[2][17] = -3.14158701897;
   fMax_1[2][17] = 3.14159178734;
   fMin_1[0][18] = 0.611416637897;
   fMax_1[0][18] = 1327.86132812;
   fMin_1[1][18] = 0.611416637897;
   fMax_1[1][18] = 2022.60778809;
   fMin_1[2][18] = 0.611416637897;
   fMax_1[2][18] = 2022.60778809;
   fMin_1[0][19] = -647.863342285;
   fMax_1[0][19] = 679.028930664;
   fMin_1[1][19] = -863.287109375;
   fMax_1[1][19] = 1526.7520752;
   fMin_1[2][19] = -863.287109375;
   fMax_1[2][19] = 1526.7520752;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 20;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<20;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
